### ISSUE TITLE
iGPU periodically fails on boot after using purge-wrangler

### ISSUE THREAD

**Issue by johnkeates** [mayankk2308/purge-wrangler#10]
### Problem
Every now and then, when rebooting or cold-booting, after FileVault login, the system doesn't finish booting. The post-authentication screen loads, bar finishes loading, but nothing happens. When I SSH into the machine all normal processes have started, but no logged in WindowServer session can be seen in there.

### Steps to Reproduce
1. Reboot a few times

### Expected Behavior
Normally, the system would boot, and the iGPU would be used by the WindowServer to start a console session, or the eGPU would be detected and WindowServer would use that and the connected display instead.

### System Configuration
 - OS: 10.4 (Mojave, but this happens on 10.13.6 too, just upgraded to test)
 - eGPU Box: Akitio Thunder 3
 - GPU: Radeon RX570
 - Connection: TB3 to TB3-TB2 converter to MBP 13" 2015

### More Context
After some experiments, it seems that 'sanitize system' fixes this until the problem is triggered again.
At first I recovered the system and re-purged it (only using enable TB2 option for the AMD GPU), but that didn't make sense as it's clearly not the enabling of the driver and TB2, but something with the cache or some other temporal system. Since I can SSH in, I can apply this, and I could do this in single user mode as well.

In addition, I tend to turn off SIP to run purge-wrangler, but then I reboot and enable it again. As far as I'm aware, purge-wrangler only runs when manually invoked, and SIP doesn't do some sort of file content check and is more of an access control element instead.

**Comment by mayankk2308** [comment]
Does this issue occur only with eGPU plugged in or in general?
Either way, I would suggest not re-enabling SIP (or maybe enable without kext) while using. Please test without re-enabling SIP.

**Comment by johnkeates** [comment]
I just hit the same issue after a few reboots, so I'm turning off SIP again and rebooting; instant success. I wonder what might be happening, is it kext signing that is also checked by SIP that fails?

**Comment by mayankk2308** [comment]
Yes - SIP prevents unsigned kexts or kexts with invalid signatures to load. I presume the issue is resolved. The recommended state is to keep SIP disabled (I understand it’s not ideal though, so maybe test with the without-kext option).

**Comment by johnkeates** [comment]
I checked the hex values set for SIP, 0x11 works; it allows you to keep other SIP things on, but allow kexts that are not valid (i.e. unsigned or invalid signature). rEFInd has a nice csr_values option where you can switch CSR/SIP into any mode you'd like at boot time instead of rebooting into Recovery OS and spending 20 minutes booting and rebooting just to flip an NVRAM variable.

Next, I'll probably figure out a way to disable SIP, whitelist the modified kexts and maybe locally sign them, and then re-enable SIP. Or I might just buy a TB3 MBP.

**Comment by johnkeates** [comment]
Also, you are pretty quick! Thanks.
