### ISSUE TITLE
Purge Wrangler - computer freezes, crashes and restarts  

### ISSUE THREAD

**Issue by mikeyb411** [mayankk2308/purge-wrangler#100]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 13" mid 2012.   
- **macOS Version**: 10.15.7
- **System GPUs**: Intel HD Graphics 4000
- **eGPU**: Sonnet Breakaway 560 
- **Script Version**: Script version you used. unsure installed yesterday.  
- **Script Logs**: Attach logs generated by the script.
[pwlog-2020-10-05-14-58-36.zip](https://github.com/mayankk2308/purge-wrangler/files/5329811/pwlog-2020-10-05-14-58-36.zip)

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
Describe your problem. Does it occur every time?

I use Paralells for work (my work PC is in windows), for no reason, no heavy render or other, machine freezes (only seems to be in windows), and crashes, restarts, during restart CPU fan Revs like crazy and fan runs heavy for a while.   Has happened to me 3x today for no apparent reason.  Happens with external monitor and mbp closed, or with external monitor and mbp open.   Also, fan in general seems to run abnormally high.  My integrated GPU is running hot, but it shouldn't even be engaged with my screen closed, and using an eGPU.  
### Expected Behavior
expect no issues.  
### Screenshots
I've looked at console, and

**Comment by mayankk2308** [comment]
Unfortunately this has nothing to do with the script. All this script does for you is enable eGPU support just like it’d be on a Thunderbolt 3 Mac. The rest is up to the OS and apps. Try looking at the application logs to figure out issues.
