### ISSUE TITLE
purge-wranger.sh Zoom CPU Spikes

### ISSUE THREAD

**Issue by SubArtic15** [mayankk2308/purge-wrangler#101]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 15" Mid-2015
- **macOS Version**: 10.15.7
- **System GPUs**: Intel Iris Pro 1536 MB
- **eGPU**: Radeon RX 570 4 GB
- **Script Version**: 6.3.1
- **Script Logs**: [pwlog-2020-10-08-15-50-57.zip](https://github.com/mayankk2308/purge-wrangler/files/5353411/pwlog-2020-10-08-15-50-57.zip)

### Issue Description
Every time I use zoom with my video on (and 1+ other individuals have their video on) my CPU usage spikes to 80-99% usage, sometimes my machine crashes as a result of this. I believe that it directly correlates to purge-wrangler because one I uninstall it from my machine, the issues disappear. This issue begin in August, has gotten exponentially worse.

### Expected Behavior
I'm fairly certain that my kernel and zoom should not be running up my CPU usage to that degree.

### Screenshots
![Zoom performance](https://user-images.githubusercontent.com/43824611/95558748-6fd52380-09b2-11eb-92b1-41ce4189ea65.png)

**Comment by mayankk2308** [comment]
The script only enables eGPU support and nothing else. Maybe Zoom has an issue working with eGPUs and doesn’t accelerate video encode/decode when eGPU is primary (or some other issue). Flipping a bit to enable eGPU can’t possibly cause CPU spikes. The cause is something else.
