### ISSUE TITLE
why isn't detected my thunderbolt enclosure

### ISSUE THREAD

**Issue by jma-grafik** [mayankk2308/purge-wrangler#102]
Sorry, but I have no much idea about this subject. I'm just trying to enhance my Macbook Pro a little bit, and I'm trying to follow all those famous tutorials out there, but I can't see my exact build hardware, and definitively is not working for me the script as shown in the tutorials, and there's no tutorial or advices if the steps are no following as described in their tutorials… 
I used some money already with the hardware and I would like to see this working.

Macbook Pro 13 mid-2012
Apple's TB/TB2 to TB3 adapter
Apple's TB3 cable

HP OMEN Accelerator
AMD Radeon Pro WX4100

I'm not annoyed yet by the compatibility of the graphics card, as directly there's nothing detected in the Thunderbolt port.

As I read in the beginners guide, I am posting this new issue to share the log I got after trying to set up everything with no luck, as were no any graphics card detected during the process

Many thanks in advance for taking your time and knowledge of all the people helping here
[pwlog-2020-10-09-16-33-16.zip](https://github.com/mayankk2308/purge-wrangler/files/5355859/pwlog-2020-10-09-16-33-16.zip)

**Comment by mayankk2308** [comment]
Please use issue template for opening issues. Anyway: https://github.com/mayankk2308/purge-wrangler/wiki/FAQ#why-did-the-script-fail-to-detect-my-enclosure

Same as #93.
