### ISSUE TITLE
Getting read-only errors in Recovery Terminal (Big Sur)

### ISSUE THREAD

**Issue by Piipperi** [mayankk2308/purge-wrangler#103]
I managed to somehow brick my macOS install but the recovering via Recovery Partition Terminal keeps spitting read-only errors for most commands I enter.

**Comment by mayankk2308** [comment]
Use Time Machine to recover to a previous snapshot: https://github.com/mayankk2308/purge-wrangler/wiki/System-Recovery#quick-recovery

Otherwise remount the volume as writable. Or simply reinstall Big Sur via Recovery - no data will be lost. I will check the commands on the recovery page again.
