### ISSUE TITLE
Unable to get R9 280 to work

### ISSUE THREAD

**Issue by Piipperi** [mayankk2308/purge-wrangler#104]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 13” Mid 2012
- **macOS Version**: 10.15.7
- **System GPUs**: Intel HD 4000
- **eGPU**: Sonnet Breakaway 550 + R9 280
- **Script Version**: 6.3.2
- **Script Logs**: 

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

[pwlog-2020-10-14-14-31-22.zip](https://github.com/mayankk2308/purge-wrangler/files/5377896/pwlog-2020-10-14-14-31-22.zip)

### Issue Description
Describe your problem. Does it occur every time?
I can’t get R9 280 to work with this script in any way, tested on a 2012 13” MacBook Pro (running Catalina) and Late 2013 15” MacBook Pro (running Big Sur). automate-eGPU EFI works.

### Expected Behavior
I’d expect the script to make my eGPU to work like the automate-eGPU EFI does, but it seems like it doesn’t.

**Comment by mayankk2308** [comment]
As mentioned on the forum, automate-eGPU EFI has a better patch for legacy AMD cards. I’ll look into it if I have time - but that doesn’t guarantee I’ll have a solution.

**Comment by Piipperi** [comment]
> As mentioned on the forum, automate-eGPU EFI has a better patch for legacy AMD cards. I’ll look into it if I have time - but that doesn’t guarantee I’ll have a solution.

I currently have the issue that automate-eGPU EFI doesn’t support Big Sur at all, and I kinda want to get my eGPU working on my Big Sur Mac too

**Comment by mayankk2308** [comment]
Yes I understand but I didn't build automate-eGPU EFI - so even if I know what causes the problem I can't fix it. Nor can I guarantee a solution. You will have to wait (with no guarantee) or just get a newer GPU.

**Comment by mayankk2308** [comment]
You are always welcome to figure out the patch and contribute to the script :)

**Comment by Piipperi** [comment]
Hmm... I wonder how that could be done, I have no prior coding knowledge but if you know how I could implement my own patches I’d be happy to take a look

**Comment by mayankk2308** [comment]
You can look at the advanced handbook on the wiki for some more insight into how patching is done in this script. Gathering the necessary knowledge is up to you - which is generally the case with such things.

**Comment by mayankk2308** [comment]
I don’t planning on working on a patch for this in the near future, so closing.
