### ISSUE TITLE
SIP reports wrong in Big Sur Beta 10

### ISSUE THREAD

**Issue by gxalpha** [mayankk2308/purge-wrangler#105]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 15" Late-2013
- **macOS Version**: 11.0 beta 10
- **System GPUs**: Intel Iris
- **eGPU**: Akitio Thunder2 + RX580
- **Script Version**: Unknown, likely newest. Tried as well with newest from Advanced Guide.
- **Script Logs**: Unknown

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
After updating from Big Sur Beta 9 to Beta 10 today, the script asked if I wanted to re-apply the patches, I chose yes and it opened the terminal. I entered my admin password and the script failed, telling me to disable SIP. 
```
purge-wrangler
Password:

Please disable System Integrity Protection.
```
It is disabled though, as reported by System information (See screenshot) as well as `csrutil status` (although I dont know what BaseSystem Verification is)
```
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: disabled
	NVRAM Protections: disabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

The script failed at startup so can't even get into the menu to generate any logs or tell you the version I used.
It ran normally in Beta 4 and 9.

### Expected Behavior
The main menu is supposed to appear.

### Screenshots
<img width="903" alt="Bildschirmfoto 2020-10-16 um 16 28 02" src="https://user-images.githubusercontent.com/59806498/96271583-5abd4d80-0fcd-11eb-9c91-40537c401671.png">

### Additional information
I tried to run `csrutil disable` again, but it appears the recovery doesn't start (it is grey and then nothing happens, this seems to be a Apple bug though), and I'll try downgrading to Beta 9 again, where it worked (although I don't know how thats supposed to work considering I have no recovery :D )

**Comment by mayankk2308** [comment]
Your SIP status is unknown, not disabled. Re-enable and then disable it.
