### ISSUE TITLE
Issue with Delayed 2nd monitor - Mouse works fine. 

### ISSUE THREAD

**Issue by tristanpgraham** [mayankk2308/purge-wrangler#107]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro (Retina, 15-inch, Late 2013)
- **macOS Version**: 11.0
- **System GPUs**: Radeon RX 5700 XT 8 GB, Intel Iris Pro 1536 MB
- **eGPU**: Razer X Core
- **Script Version**:PurgeWrangler (6.3.2)

### Issue Description
Laptop display runs fine but 2nd display is delayed or "slowed down" The mouse moves at normal speed but when I run applications or watch a YouTube video. It is running at like 1fps.

I did have to run these steps to get my graphics card to cooperate and not crash my MacBook Pro. This was found on this article: https://github.com/mayankk2308/purge-wrangler/issues/44

```
>> Setup eGPU
Plug-in eGPU. Press ESC if you are not plugging in eGPU.
eGPU detection skipped. Please provide more information.
Backing up...
Backup refreshed.
Skipping Ti82 support.
 eGPU Vendor
 1. AMD
 2. NVIDIA
 3. Cancel
Patching for AMD eGPUs...
Skipping legacy kext.
Patches applied.
Analyzing system...
No anomalies expected.
Sanitizing system...
System sanitized.
Modifications complete.
Reboot to apply changes
```

eGPU does show up in Activity Monitor.
<img width="955" alt="Screen Shot 2020-11-04 at 1 36 22 AM" src="https://user-images.githubusercontent.com/37854104/98078549-48059e00-1e40-11eb-8af0-030d70e5433d.png">

### Expected Behavior
The 2nd display should work the same as the main laptop display.

**Comment by tristanpgraham** [comment]
<img width="955" alt="Screen Shot 2020-11-04 at 1 36 22 AM" src="https://user-images.githubusercontent.com/37854104/98077473-49ce6200-1e3e-11eb-9558-df22987dac7b.png">


I also noticed that in Activity Monitor, the GPU is at 0%

**Comment by mayankk2308** [comment]
Your screenshot shows the NVIDIA GPU which you don’t mention in the template/system gpus section and that’s the issue. Please read wiki/complications.
