### ISSUE TITLE
Can't detect Sonnet eGFX Breakaway Puck RX 560

### ISSUE THREAD

**Issue by molfetamina** [mayankk2308/purge-wrangler#108]
EDIT: solved, Apple cable + Apple adapter... too much expensive but it work!

### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: iMac14,3
- **macOS Version**: 10.14.6 (18G103)
- **System GPUs**: NVIDIA GeForce GT 750M
- **eGPU**: Sonnet eGFX Breakaway Puck RX 560
- **Script Version**: PurgeWrangler (6.3.2)
- **Script Logs**: Attach logs generated by the script.
[pwlog-2020-11-05-16-08-56.zip](https://github.com/mayankk2308/purge-wrangler/files/5495325/pwlog-2020-11-05-16-08-56.zip)

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
The eGFX box, connected to iMac with STARTECH.COM Adatattore Thunderbolt 3 a Thunderbolt, M/F, Nero (https://www.amazon.it/gp/product/B019FPJDQ2) + Cavo Thunderbolt Apple (0.5 m) (https://www.amazon.it/gp/product/B00B3Y4U4E), is not detected; actually it doesn't even turn on.

### Expected Behavior
The eGFX box should be detected by the iMac.

**Comment by mayankk2308** [comment]
Read the wiki/FAQ. eGPU detection is not controlled by the script. You need to fix the detection issue with your system (whatever the cause) for the eGPU to work.
