### ISSUE TITLE
Could not download AMDLegacySupport.kext.zip: 

### ISSUE THREAD

**Issue by kanexu1985** [mayankk2308/purge-wrangler#109]
Hi Developer,

I've tried the steps on the beginner's guide page, and get a download error and couldn't find it on FAQ's page.
I believe my internet connection is fine, any specific domain I should try to pin for a test?
Below text is copied from the terminal

Thanks.

>> Setup eGPU

Plug-in eGPU. Press ESC if you are not plugging in eGPU.

External GPU	Radeon RX 580 2048SP
GPU Arch	Polaris 20 XL 
Thunderbolt	3

Backing up...
Backup refreshed.

Downloading AMDLegacySupport...
shasum: /Library/Extensions/AMDLegacySupport.kext.zip: 
Could not download.

Patching for AMD eGPUs...
No patch required for this Mac.

Back to menu? [Y/N]:

**Comment by mayankk2308** [comment]
Thanks for reporting. Will test this. Next time please fill in template.

**Comment by mayankk2308** [comment]
I could not reproduce the issue but your GPU should not require the legacy kext anyway. Fix for that will be in next release.

**Comment by OrangeShen** [comment]
I am having the same isuue with rx580 2048sp, the script can detect my egpu, but it's not working since I didn't see any egpu activity in the activity monitor. According to apple's document, I should be able to use this type of egpu once I plug it in, yet nothing works for my situation.

**Comment by mayankk2308** [comment]
Not sure what's going on with the 2048sp. Maybe it requires special drivers that macOS does not have. It is already confirmed that normal RX 580's work well.

**Comment by kanexu1985** [comment]
> I am having the same isuue with rx580 2048sp, the script can detect my egpu, but it's not working since I didn't see any egpu activity in the activity monitor. According to apple's document, I should be able to use this type of egpu once I plug it in, yet nothing works for my situation.

Hi OrangeShen,

I've studied more after I opened this post and the conclusion is, 2048sp is a special edition of RX580, and Apple does NOT support this model.
The workaround is to update the graphic card flash and make it as RX570, and that would recognized by macOS natively and doesn't need 3rd party driver/plug-in like purge-wangler.

However, my 2048sp doesn't work and I gave up...

Hope my info helps.

**Comment by OrangeShen** [comment]
Thank you for your work, I was having doubt that this type of gpu is not compatible with macOS. now &nbsp;you make me more convinced about this issue. I would try the RX580 2304SP and not spending days working to an dead end.&nbsp;


Thanks agian.



发自我的iPhone


------------------ Original ------------------

**Comment by mayankk2308** [comment]
@OrangeShen can you share logs from the script with the eGPU connected (more options > logging in script)? I think I might have an idea to make it work.

**Comment by OrangeShen** [comment]
I am sorry, but I already return the gpu this morning. What's your idea?



发自我的iPhone


------------------ Original ------------------

**Comment by mayankk2308** [comment]
@OrangeShen i believe the issue is that the 2048sp model has a different device ID.

Normal 580: https://devicehunt.com/view/type/pci/vendor/1002/device/67DF
2048sp Model: https://devicehunt.com/view/type/pci/vendor/1002/device/6FDF

My guess is the 6FDF device ID is absent in the macOS AMD drivers. Adding that override should allow the GPU to function.

**Comment by ivancho4** [comment]
Hello, I have problems with a Sonnet 550, with a Saphire rx 580 8-gigabyte video card, before connecting thunderbolt it would crash and restart, now with Big Sur it no longer does, but the message "there is no removable GPU" on a mac mini 2018, I found your fabulous help page and I was able to install your Purge Wrangler, but it tells me that it does not require a patch this mac, I am attaching the message and I hope you can help me please solve this problem greetings and thanks

External GPU	Radeon RX 470/480/570/570X/580/580X/590
GPU Arch	Ellesmere 
Thunderbolt	3

Backing up...
Backup refreshed.

Patching for AMD eGPUs...
No patch required for this Mac.

Analyzing system...
No resolutions to any anomalies if present. See README.

**Comment by ivancho4** [comment]
I am attaching more information about my case .. I connect the cable and the eGpu icon appears then it disappears and tells me that there is no removable gpu

Ti82 Devices      Disabled
TB1/2 AMD eGPUs   Disabled
Legacy AMD eGPUs  Enabled
NVIDIA eGPUs      Disabled
Web Drivers       Absent

System Diagnosis

Analyzing system...
No resolutions to any anomalies if present. See README.

>> System Log

Generating system log...
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
Log generated on the Desktop.

Open an issue on Github and share this file.
[
![Captura de pantalla 2021-02-02 a las 5 10 20 p m](https://user-images.githubusercontent.com/78452392/106677217-fc1cdf00-657d-11eb-9560-a823d27bb214.png)
![Captura de pantalla 2021-02-02 a las 5 10 15 p m](https://user-images.githubusercontent.com/78452392/106677219-fe7f3900-657d-11eb-9b2c-15bd0b0f67c0.png)
![Captura de pantalla 2021-02-02 a las 5 42 33 p m](https://user-images.githubusercontent.com/78452392/106677275-19ea4400-657e-11eb-99d9-7b6b21a96f87.png)


](url)

**Comment by mayankk2308** [comment]
@ivancho4 as the script says, your mac already natively supports eGPUs. Please read the documentation before using the script. If a native configuration isn't working, ask Apple or eGPU.io.

**Comment by ivancho4** [comment]
thanksas I ask in eGPU.io?
