### ISSUE TITLE
External Screen

### ISSUE THREAD

**Issue by Liemaeu** [mayankk2308/purge-wrangler#11]
Do I need an external Screen for my eGPU (Akitio Thunder2 + GTX 1050)? Or can I use the normal Macbook Screen?
Thanks

**Comment by mayankk2308** [comment]
It is possible to use an internal screen using [set-eGPU](https://github.com/mayankk2308/set-egpu), but performance is not guaranteed.

This section is for issues with the script only. Please use the [egpu.io](https://egpu.io) forums for questions like this.
