### ISSUE TITLE
2011 Mac Mini "Unable to patch for TB1/2 AMD eGPUs"

### ISSUE THREAD

**Issue by Jrhere2003** [mayankk2308/purge-wrangler#110]
[pwlog-2020-11-07-12-39-08.zip](https://github.com/mayankk2308/purge-wrangler/files/5505399/pwlog-2020-11-07-12-39-08.zip)

Trying to install this on a 2011 Mac Mini, running Catalina. I have disabled system integrity in order to install Catalina already, but I am unable to get the purge-wrangler to install. Any ideas why?

**Comment by Jrhere2003** [comment]
Never-mind, I see that patched Catalina installs do not work on unsupported Macs

**Comment by ikir83** [comment]
I have this same issue.
