### ISSUE TITLE
Sonnett EGPU issue 

### ISSUE THREAD

**Issue by Dodson7575** [mayankk2308/purge-wrangler#111]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacMini 2011 
- **macOS Version**: 10.13.6 High Sierra
- **System GPUs**: EGPU - Radeon 6970
- **eGPU**: Sonnet Breakaway 350W
- **Script Version**: Most Recent 6.3.2
- **Script Logs**: Attach logs generated by the script.

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
No display from EGPU to Monitors. Power is on, EGPU is running, all connections are correct. Used apple thunderbolt 3 to 2 adapter with apple thunderbolt 2 cable. 

### Expected Behavior
No display form EGPU to Monitors.

**Comment by mayankk2308** [comment]
Older AMD eGPUs are not guaranteed to be supported.
