### ISSUE TITLE
macOS Catalina 10.15.7 (19H2) Won't Boot After Updating to 19H15

### ISSUE THREAD

**Issue by rshinall** [mayankk2308/purge-wrangler#112]
macOS Catalina 10.15.7 (19H2)

Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	162.0.0.0.0
  SMC Version (system):	2.19f12

Razer Core eGPU
Sapphire Radeon 11265-05-20G Pulse RX 580 8GB GDDR5

NVIDIA GeForce GT 750M 2 GB
Intel Iris Pro 1536 MB

Script version 6.3.2

I installed the macOS 19H15 update, and rebooted. Purge wrangler prompted me to repatch the system, so I did. After that, it woudl not restart, even after unplugging the eGPU, and also rebooting into recovery mode and re-enabling SIP. Attempted multiple reboots. It would just hang on the apple logo and the fan would start running. Only solution was to boot into recovery mode and reinstall macOS. Fortunately it reverted to the version that was working fine before. I will hold off on the update for a while. Let me know if you need more info.

**Comment by mayankk2308** [comment]
Please follow template when opening issues. Also read wiki for easy recovery steps. Your system could face the issue if you used purge-nvda as well and somehow the NVRAM settings were restored/erased. This same Mac works on macOS Big Sur as well, so might be an isolated issue with your configuration. Just follow the steps for setup exactly and read up on recovery if things don’t work.
