### ISSUE TITLE
MBP late 2011, 10.13.6

### ISSUE THREAD

**Issue by Jubaca** [mayankk2308/purge-wrangler#113]
### Feature Description
I have installed purgewrangler thousands of times, it does not give me any error messages, however it does not get my eGPU to work. An Akitio Node Duo box with Sapphire Pulse RX550. I appreciate if you can help me. Thank you.

**Comment by mayankk2308** [comment]
RX 550 is not supported on macOS.

**Comment by Jubaca** [comment]
Oh, what a sadness! I bought the card for this information that I found from Sapphire.

[Compatible List_graphics_System_ENG.pdf](https://github.com/mayankk2308/purge-wrangler/files/5540382/Compatible.List_graphics_System_ENG.pdf)

**Comment by Jubaca** [comment]
Ud podría recomendar una de nivel bajo que sea compatible con Davinci Resolve? Please.

**Comment by mayankk2308** [comment]
You should be using: https://support.apple.com/en-us/HT208544

**Comment by Jubaca** [comment]
Thank you!
