### ISSUE TITLE
Help me, please.

### ISSUE THREAD

**Issue by Jubaca** [mayankk2308/purge-wrangler#114]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 13" Late-2011.
- **macOS Version**: 10.13.6
- **System GPUs**: Sapphire Pulse RX 550
- **eGPU**: Akitio Node Duo
- **Script Version**: 6.3.2
- **Script Logs**: Attach logs generated by the script.

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.
[pwlog-2020-11-14-00-41-27.zip](https://github.com/mayankk2308/purge-wrangler/files/5540369/pwlog-2020-11-14-00-41-27.zip)

### Issue Description
I have installed purgewrangler thousands of times, it does not give me any error messages, however it does not get my eGPU to work. An Akitio Node Duo box with Sapphire Pulse RX550. I appreciate if you can help me. Thank you.

### Expected Behavior
I hope that the icon to eject the eGPU appears in the menu bar above and enabled in the system report.

### Screenshots
![Captura de pantalla 2020-11-14 a la(s) 1 45 14 a  m](https://user-images.githubusercontent.com/74446388/99142868-130aff80-2627-11eb-820a-04c3b79ae1c0.png)

![Captura de pantalla 2020-11-14 a la(s) 1 46 04 a  m](https://user-images.githubusercontent.com/74446388/99142880-274efc80-2627-11eb-93df-4a39df370671.png)

**Comment by mayankk2308** [comment]
Please stop re-creating the same issue. As I said, RX 550 is NOT SUPPORTED even if the script goes through and tries to patch - there are no drivers for it in macOS.

**Comment by Jubaca** [comment]
Thank you!
