### ISSUE TITLE
please help me the egpu not working

### ISSUE THREAD

**Issue by janjanjian** [mayankk2308/purge-wrangler#119]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro (Retina, 15-inch, Mid 2015)
- **macOS Version**: 11.0.1 (20B29)
- **System GPUs**: Intel Iris
- **eGPU**: AKiTiO Node Lite + RX580 4GB
- **Script Version**: 6.3.3
- **Script Logs**: Attach logs generated by the script.∂
[pwlog-2020-11-19-12-35-40.zip](https://github.com/mayankk2308/purge-wrangler/files/5564416/pwlog-2020-11-19-12-35-40.zip)

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
when i upgrade to macos 11.0.1,the egpu is not working,i try to up updates Script it still not working.

### Expected Behavior
Please help me solve this problem as soon as possible, thank you

### Screenshots
<img width="1139" alt="QQ20201119-124719@2x" src="https://user-images.githubusercontent.com/32062095/99622609-79e44a80-2a65-11eb-8fa0-b42867ed695c.png">

**Comment by mayankk2308** [comment]
Not sure why that might be happening. The `kmutil` tool is a macOS built-in tool and I can't do much if it is throwing a segmentation fault. Can you try running it manually:
```sh
kmutil install --update-all --force --volume-root /
```

**Comment by janjanjian** [comment]
> Not sure why that might be happening. The `kmutil` tool is a macOS built-in tool and I can't do much if it is throwing a segmentation fault. Can you try running it manually:
> 
> ```shell
> kmutil install --update-all --force --volume-root /
> ```

i try tu running it manually but it fail
<img width="587" alt="QQ20201120-110157@2x" src="https://user-images.githubusercontent.com/32062095/99752797-04898000-2b20-11eb-97d5-f73bd770f6d8.png">

**Comment by mayankk2308** [comment]
It needs to be run with `sudo`. Just add that to the beginning of the command and retry.

**Comment by mayankk2308** [comment]
Still awaiting response. Issue will be closed eventually if no response is received.

**Comment by mayankk2308** [comment]
No response, closed.
