### ISSUE TITLE
Drivers doesn't install

### ISSUE THREAD

**Issue by sigmotoa** [mayankk2308/purge-wrangler#122]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBookPro mid 2012
- **macOS Version**: 10.15.6,
- **System GPUs**: Intel HD Graphics 4000 1536 MB
- **eGPU**: nvidia GFORCE RTX 2070
[pwlog-2020-11-23-19-17-06.zip](https://github.com/mayankk2308/purge-wrangler/files/5587411/pwlog-2020-11-23-19-17-06.zip)

- **Script Version**: Script version you used.
- **Script Logs**: Attach logs generated by the script.

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
Describe your problem. Does it occur every time?

**Comment by mayankk2308** [comment]
Read the wiki before opening issues.
