### ISSUE TITLE
Mac Pro 2013 late Big Sur(11.0.1) EGPU(Vega64+Razer) Thunderbolt 2 issue 

### ISSUE THREAD

**Issue by smacker4141** [mayankk2308/purge-wrangler#123]
### System Configuration

- **Mac**: MacPro (Late 2013)
- **macOS Version**: 11.0.1
- **System GPUs**: AMD FirePro D500 3GB
- **eGPU**: Sonnet Vega64+Razer
- **Script Version**: 6.3.3v

Hello 
A video producer who uses Egpu. We use EGPU using the specifications listed above.
As announced, EGPU works well in Big Sur (11.0.1), but external hard drives using Thunderbolt 2 seem to have a bug that does not recognize the disk when SCRIPT is applied.

Try leaving a LOG file. How can I fix this?

Thanks for the help! 

- **Script Logs**: 

Software:

    System Software Overview:

      System Version: macOS 11.0.1 (20B50)
      Kernel Version: Darwin 20.1.0
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Disabled
      Time since boot: 15 minutes

Hardware:

    Hardware Overview:

      Model Name: Mac Pro
      Model Identifier: MacPro6,1
      Processor Name: 12-Core Intel Xeon E5
      Processor Speed: 2.7 GHz
      Number of Processors: 1
      Total Number of Cores: 12
      L2 Cache (per Core): 256 KB
      L3 Cache: 30 MB
      Hyper-Threading Technology: Enabled
      Memory: 64 GB
      System Firmware Version: 132.0.0.0.0
      SMC Version (system): 2.20f18
      Panel Illumination Version: 1.4a6
      Provisioning UDID: B7158ABF-935D-5175-962A-3346DFA0F5CD

PCI:

    AMD FirePro D500:

      Name: ATY,KaniS
      Type: Display Controller
      Driver Installed: Yes
      MSI: Yes
      Bus: PCI
      Slot: Slot-2
      Vendor ID: 0x1002
      Device ID: 0x679e
      Subsystem Vendor ID: 0x106b
      Subsystem ID: 0x0125
      Revision ID: 0x0000
      Link Width: x16
      Link Speed: 8.0 GT/s

    AMD FirePro D500:

      Name: ATY,Kani
      Type: Display Controller
      Driver Installed: Yes
      MSI: Yes
      Bus: PCI
      Slot: Slot-1
      Vendor ID: 0x1002
      Device ID: 0x679e
      Subsystem Vendor ID: 0x106b
      Subsystem ID: 0x0126
      Revision ID: 0x0000
      Link Width: x16
      Link Speed: 8.0 GT/s

    pci105a,8760:

      Type: RAID Controller
      Driver Installed: No
      Tunnel Compatible: No
      Pause Compatible: No
      MSI: No
      Bus: PCI
      Slot: Thunderbolt@79,0,0
      Vendor ID: 0x105a
      Device ID: 0x8760
      Subsystem Vendor ID: 0x1c58
      Subsystem ID: 0x42d9
      Revision ID: 0x0001
      Link Width: x4
      Link Speed: 5.0 GT/s

    Radeon RX Vega 64:

      Name: ATY,AMD,RadeonFramebuffer
      Type: Display Controller
      Driver Installed: Yes
      Tunnel Compatible: Yes
      Pause Compatible: No
      MSI: Yes
      Bus: PCI
      Slot: Thunderbolt@60,0,0
      Vendor ID: 0x1002
      Device ID: 0x687f
      Subsystem Vendor ID: 0x1043
      Subsystem ID: 0x04c4
      Revision ID: 0x00c1
      Link Width: x16
      Link Speed: 8.0 GT/s

    pci1002,aaf8:

      Type: Audio Device
      Driver Installed: Yes
      Tunnel Compatible: Yes
      Pause Compatible: No
      MSI: Yes
      Bus: PCI
      Slot: Thunderbolt@60,0,1
      Vendor ID: 0x1002
      Device ID: 0xaaf8
      Subsystem Vendor ID: 0x1002
      Subsystem ID: 0xaaf8
      Revision ID: 0x0000
      Link Width: x16
      Link Speed: 8.0 GT/s

**Comment by mayankk2308** [comment]
Ensure that the eGPU and drives are connected to different thunderbolt controllers: https://support.apple.com/en-us/HT202801

This has nothing to do with the script as it only deals with enabling eGPU support, with no external impact.
