### ISSUE TITLE
Black Screens on Monitors Connected to eGPU

### ISSUE THREAD

**Issue by Blx90** [mayankk2308/purge-wrangler#125]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 15" Mid 2012
- **macOS Version**: 10.13.6 
- **System GPUs**: Intel HD Graphics 4000 1536MB 
- **eGPU**: Razer Core X + Radeon RX 580 
- **Script Version**: [Script](url
[pwlog-2020-12-04-02-40-51.zip](https://github.com/mayankk2308/purge-wrangler/files/5641199/pwlog-2020-12-04-02-40-51.zip)
) version you used.
- **Script Logs**: Attach logs generated by the script.

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
Problem: Black screens on monitors connected to eGPU
Resolution: Use purge-nvda.sh AMD optimizations

### Expected Behavior
The same error appears whether the HDMI 1 cable is connected or not. I have no idea how the resolution is applied. If someone can assist as I have no programming experience. Why would an AMD gpu need to use purge-nvda.sh?

Original Apple cables are used. 

Please help!

![Screen Shot 2020-12-04 at 2 49 55 AM](https://user-images.githubusercontent.com/75469748/101136514-6eebf700-35db-11eb-96f5-330cf006e752.png)

**Comment by mayankk2308** [comment]
> Why would an AMD gpu need to use purge-nvda.sh?

Umm, why not just follow the recommendation in the script? Your Mac has the GT650M discrete chip and that causes issues.
