### ISSUE TITLE
Razer/Nvidia Driver not working

### ISSUE THREAD

**Issue by andyreik** [mayankk2308/purge-wrangler#126]
### System Configuration

- MacBook Pro 13" 2017
- **macOS 10.13.6
- **System GPUs**: 2.3 GHz Intel Core i5 
[GPUs.log](https://github.com/mayankk2308/purge-wrangler/files/5649306/GPUs.log)

- **eGPU**: Razer/ Nvidia Quadro K5000
- **Script Version**: curl -qLs $(curl -qLs https://bit.ly/2WtIESm | grep '"browser_download_url":' | cut -d'"' -f4) > purge-wrangler.sh; sh purge-wrangler.sh; rm purge-wrangler.sh

- **Script Logs**: 11ba 10de
Quadro K5000:GK104GL 

[eGPU.log](https://github.com/mayankk2308/purge-wrangler/files/5649310/eGPU.log)

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
Driver installed on Terminal, not showing in System Info - 

Port:
  Status:	Device connected
  Link Status:	0x2
  Speed:	Up to 20 Gb/s x1
  Current Link Width:	0x2
  Receptacle:	2
  Link Controller Firmware Version:	0.38.0
  
Port:
  Status:	No device connected
  Link Status:	0x7
  Speed:	Up to 40 Gb/s x1
  Current Link Width:	0x1
  Receptacle:	1
  Link Controller Firmware Version:	0.38.0

Core X:

  Vendor Name:	Razer
  Device Name:	Core X
  Vendor ID:	0x127
  Device ID:	0x1
  Device Revision:	0x1
  UID:	0x0127F38F44330D00
  Route String:	1
  Firmware Version:	33.1
  Port (Upstream):
  Status:	Device connected
  Link Status:	0x2
  Speed:	Up to 20 Gb/s x1
  Current Link Width:	0x2
  Link Controller Firmware Version:	0.35.0

### Expected Behavior
eGPU not enabled correctly

**Comment by mayankk2308** [comment]
Could you please share the entire .zip file generated by script logging?

**Comment by andyreik** [comment]
Thanks for your help. Please see attached zip file.

**Comment by mayankk2308** [comment]
I don’t see the file. Please respond directly on GitHub - might be easier to upload that way.

**Comment by andyreik** [comment]
Please see file
[pwlog-2020-12-07-17-44-10.zip](https://github.com/mayankk2308/purge-wrangler/files/5654276/pwlog-2020-12-07-17-44-10.zip)

**Comment by andyreik** [comment]
FYI, now showing in System Info but not entirely sure it's working. What's the best way to test?

**Comment by mayankk2308** [comment]
Ya logs show the GPU has initialized correctly. Try Geekbench compute benchmark which should allow you to choose GPU. However, logs also show Web Drivers being installed. Those should not be required for Kepler GPUs, and macOS-native drivers should be sufficient.

**Comment by mayankk2308** [comment]
Is there any update to this issue? Will close in a couple days if not.

**Comment by andyreik** [comment]
Thanks, not sure I have an update at present but thanks for your help.

**Comment by mayankk2308** [comment]
The Geekbench test did not work for you? Everything seemed right for your configuration. Consider reaching out on eGPU.io for further assistance from more people if needed. For now, I am closing the issue as the problem does not seem to be with the script itself (it worked fine in enabling the GPU in macOS). Cheers.
