### ISSUE TITLE
purge-wrangler "Setup eGPU" and "Add AMD Legacy Support"No such file or directory

### ISSUE THREAD

**Issue by panc-86** [mayankk2308/purge-wrangler#127]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 13.3" Mid-2020
- **macOS Version**: Big Sur 11.1 (20C69)
- **System GPUs**: Intel Iris Plus Graphics 1536 MB
- **eGPU**: Razer core x chroma + AMD RX 6800 xt 
- **Script Version**: PurgeWrangler (6.3.3)
- **Script Logs**: rsync: link_stat "/Volumes/Macintosh HD 1/Library/Application Support/Purge-Wrangler/io.egpu.purge-wrangler.config.plist" failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release

### Issue Description
1、When I "Setup eGPU" and "Add AMD Legacy Support", failed with "No such file or directory",it occur every time.
2、I can't find file "Macintosh HD 1"in my MBP,only "Macintosh HD".

### Screenshots
<img width="1130" alt="WeChat58191e0bbab8425a6e625b0df50b1c1d" src="https://user-images.githubusercontent.com/76073556/102278004-0817f780-3f64-11eb-8ab6-cb73fe1727e9.png">
<img width="1130" alt="WeChate3a3a437a2bd1cff61c6ff53f7884a5d" src="https://user-images.githubusercontent.com/76073556/102278145-42819480-3f64-11eb-8721-3bf1a39cedcc.png">

**Comment by panc-86** [comment]
[pwlog-2020-12-16-05-30-33.zip](https://github.com/mayankk2308/purge-wrangler/files/5698988/pwlog-2020-12-16-05-30-33.zip)

**Comment by mayankk2308** [comment]
Big Navi is not supported on macOS at this time. If and when it is, your Mac will not need this script (only TB1/2 Macs need it for AMD GPUs). However, I'm glad you filed this issue as it demonstrates some other problems with the script which I will address in a future release.

**Comment by norf0000** [comment]
> ### System Configuration
> 
> Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
> 
> - **Mac**: MacBook Pro 13.3" Mid-2020
> 
> - **macOS Version**: Big Sur 11.1 (20C69)
> 
> - **System GPUs**: Intel Iris Plus Graphics 1536 MB
> 
> - **eGPU**: Razer core x chroma + AMD RX 6800 xt 
> 
> - **Script Version**: PurgeWrangler (6.3.3)
> 
> - **Script Logs**: rsync: link_stat "/Volumes/Macintosh HD 1/Library/Application Support/Purge-Wrangler/io.egpu.purge-wrangler.config.plist" failed: No such file or directory (2)
> 
> rsync error: some files could not be transferred (code 23) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-55/rsync/main.c(996) [sender=2.6.9]
> 
> Executing: /usr/bin/kmutil showloaded
> 
> No variant specified, falling back to release
> 
> 
> 
> ### Issue Description
> 
> 1、When I "Setup eGPU" and "Add AMD Legacy Support", failed with "No such file or directory",it occur every time.
> 
> 2、I can't find file "Macintosh HD 1"in my MBP,only "Macintosh HD".
> 
> 
> 
> ### Expected Behavior
> 
> 
> 
> 
> 
> ### Screenshots
> 
> If applicable, add screenshots to help explain your problem.
> 
> <img width="1130" alt="WeChat58191e0bbab8425a6e625b0df50b1c1d" src="https://user-images.githubusercontent.com/76073556/102278004-0817f780-3f64-11eb-8ab6-cb73fe1727e9.png">
> 
> <img width="1130" alt="WeChate3a3a437a2bd1cff61c6ff53f7884a5d" src="https://user-images.githubusercontent.com/76073556/102278145-42819480-3f64-11eb-8721-3bf1a39cedcc.png">
> 
>

**Comment by mayankk2308** [comment]
This issue may sometimes happen if the root volume is not set correctly. One workaround is to restart the system via System Preferences > Startup Disk choosing your boot disk for restart. Additionally, there is now a far better solution for eGPUs. Please migrate to Kryptonite: https://github.com/mayankk2308/kryptonite
