### ISSUE TITLE
Issue booting 2013 Mac Pro 10.15.7 , Sonnet 350, RX 580

### ISSUE THREAD

**Issue by Ericklee84** [mayankk2308/purge-wrangler#128]
First off I want to thank you so much for your time and effort helping people out! Any suggestions are greatly appreciated.

Current setup:
Mac Pro 6, 1
10-Core OWC upgrade
Dual D500s
64 GB RAM
Catalina 10.15.7

eGPU:
Sonnet 350W
XFX Radeon RX 580
Apple TB 3>TB 2 adapter
Apple TB2 cable.

Process:
1. Disconnected all TB devices
2. Disabled SIP, restart
3. Ran Purge-wrangler, select “1” and connected egpu when prompted. Script loads fine then auto-restarts
4. Stuck in boot loop and no Apple logo shown on screen

After this is seems I’m only sometimes able to correctly boot after disconnecting egpu. Sometimes can’t boot at all then time machine snapshots stopped working. I’m now starting over via time machine backup. Now I’m in a real time loop as I’ve been trying the process over and over...

Any clues to what might be happening? Should I have any displays plugged into egpu? If so when should I plug them in? Where should my display be plugged into Mac? Currently it’s in the HDMI since I unplugged my other monitor from a TB port.

Thank you,
Erick

**Comment by mayankk2308** [comment]
Plug in the eGPU to the bottom two TB ports. IIRC the Mac Pro has issues booting when eGPU is plugged into the other ports. You can find more information on eGPU.io.

**Comment by Ericklee84** [comment]
Thanks I will try this another today. Do I need to patch the Ti82 driver?

**Comment by Ericklee84** [comment]
Just tried with eGPU TB plugged in bus 0 (bottom row). Still suck in boot loop...

**Comment by Ericklee84** [comment]
I also noticed pet of my Mac petition is I mounted and I can’t seem to get it mounted again

![Uploading 6F3A83C7-BDCD-4D3B-8F26-F523C1FF35BA.jpeg…]()

**Comment by Ericklee84** [comment]
Time machine snap shot failing to reload. Could it have something to do with partition being un-mounted?

![601B4270-8932-4D0F-BA1F-47576B1C6DC0](https://user-images.githubusercontent.com/76209420/102702950-8f43c480-421d-11eb-87d9-96ebb0f5f9c0.jpeg)

**Comment by Ericklee84** [comment]
I was able to repair disk and successfully startup. However, GFX cards are not recognized (sonnet recognized). See screenshots below.

![Screen Shot 2020-12-19 at 5 39 18 PM](https://user-images.githubusercontent.com/76209420/102703233-278f7880-4221-11eb-842e-50d63feaf35d.png)

![Screen Shot 2020-12-19 at 5 38 20 PM](https://user-images.githubusercontent.com/76209420/102703238-2fe7b380-4221-11eb-8797-978ab5159d5f.png)

![Screen Shot 2020-12-19 at 5 38 26 PM](https://user-images.githubusercontent.com/76209420/102703244-3f66fc80-4221-11eb-9dfb-966e45dce26d.png)

**Comment by Ericklee84** [comment]
Repatched purge wrangler and this time *DID NOT plug in gpu when prompted in step 1. Restart machine and boot loop is back. Restored from time machine snap shot and back to square 1. Possible DOA graphics card?

**Comment by Ericklee84** [comment]
Card used from New Egg:


XFX GTS Black Edition RX 580 8GB OC+ 1425MHz RX-580P8DBD6 DDR5 3xDP HDMI DVI With XFX Custom Backplate
https://www.newegg.com/xfx-rx-580/p/1DW-000W-00026?Item=1DW-000W-00026&utm_medium=TraEmail&utm_source=TEMC-Shipping-New-Tracking-Notification-Responsive-US&cm_mmc=TEMC-Shipping-New-Tracking-Notification-Responsive-US-_-1DW-000W-00026

**Comment by mayankk2308** [comment]
@Ericklee84 sorry for the late follow-up. I’m not exactly sure what the issue might be, but in the past, XFX has typically caused issues in macOS. If it is not too much trouble, consider trying a different card.

**Comment by mayankk2308** [comment]
Hi, any updates on this?

**Comment by Ericklee84** [comment]
Thanks for checking in. I’m returning the XFX card. I’m now realizing many people are having issues with the MacPro on Catalina. If I come across a guide with a similar setup as mine or a working guide in Big Sur (if that makes a difference?) I will try again.

**Comment by mayankk2308** [comment]
Closing issue as problem unrelated to script. Feel free to update this thread as you find more details. Cheers!
