### ISSUE TITLE
Alternative donation option requested

### ISSUE THREAD

**Issue by lundstrj** [mayankk2308/purge-wrangler#129]
Hello,

I find your tool quite useful and I'd like to make a donation.
However, Paypal has always been awful to me (and apparently quite a few other people around the internet too). Just recently they not only closed my account but also charged me for being inactive.

Is there by any chance some other way of showing my appreciation in the form of send you a bit of money? If not, would you be open to adding an alternative payment provider?

**Comment by mayankk2308** [comment]
@lundstrj thank you for your consideration! You should be able to donate via PayPal without an account (on donation page) if you use a credit/debit card I believe. At this time, I haven’t yet looked into alternative donation solution and I’m not sure when I’ll follow up on this script/project next. But I really do appreciate the gesture and understand PayPal is not for you. Your consideration is more than enough for me, thank you. 

If you don’t mind me asking however, what did eGPU enable you to accomplish? I’m always curious about what use cases this project has enabled for users and love hearing/reading about them, hence the question.
