### ISSUE TITLE
Need help！MacBook Pro2017 without touchbar+10.13.6（17G65）+XG station Pro+ASUS 1060ti 6G  

### ISSUE THREAD

**Issue by wangshunye12109** [mayankk2308/purge-wrangler#13]
I got some problems when I use egpu on my Macbook Pro，when I plug in my egpu，my MacBookPro reboot again and over again，when I don't use the egpu，my Mac can boot normally，can someone help me？thanks！
System specs:
1.MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
2.10.13.6 (17G65)
3. CPU 2.3 GHz Intel Core i5
4.8 GB 2133 MHz LPDDR3
5.Intel Iris Plus Graphics 640 1536 MB

eGPU hardware:
ASUS XG Station Pro + ASUS  GTX 1060 Ti 6G+ 1.5m Thunderbolt 3 cable

What I did：（setup by setup）
1.plug egpu 
2.I used Benjamin Dobell's script. 
3.i installed Purge-Wrangler for Nvidia eGPU. 
followed the setup on GitHub，
①Disable system integrity protection for macOS using Terminal in Recovery
②install the latest version of purge-wrangler.sh.
③Enable NVIDIA eGPUs 
④reboot system and my system reboot again and over again

**Comment by mayankk2308** [comment]
Uninstall everything - use **purge-wrangler** system recovery option.
Reboot and see if everything is fine. Try plugging in/unplugging eGPU (without the patches) and ensure system is working fine. Then, don't use Benjamin's script, and only use purge-wrangler.sh. It should install web drivers too.

**Comment by wangshunye12109** [comment]
Thank you for your reply！  I followed the steps of your response，But my computer still doesn't work.it still restarting over and over again   :(

**Comment by mayankk2308** [comment]
Could you test on a clean install (I recommend using an external drive for this)? Also what GPU is this - **1060 Ti**? Haven't heard of it - do you mean **1060**? I haven't seen this problem pop up before. Typically it's either the eGPU not functioning (nothing happening) or it works. One case where the system hangs/crashes is when the GPU is faulty (I experienced this with an AMD card - had malfunctioned - started crashing macOS).

**Comment by wangshunye12109** [comment]
I don't understand what you mean “clean install”.Yes, my graphics card is 1060，I haven’t used it since I bought it.I have tried many methods，but doesn’t work，I am a newbie，I hope you can help me, thank you.

**Comment by mayankk2308** [comment]
Clean install refers to a fresh installation of macOS (without your user files, etc.) as if it was a new system. You can search the web for how to install macOS on an external drive.

**Comment by wangshunye12109** [comment]
Ok, I know how to do it, I reinstall it and reply to you.

**Comment by wangshunye12109** [comment]
> Clean install refers to a fresh installation of macOS (without your user files, etc.) as if it was a new system. You can search the web for how to install macOS on an external drive.

i find another MacBookPro 2017 without touch

bar ，The same problem has occurred.  I find graphics card docking(XG station Pro) fan does not turn，only fan on the graphics card work normal，is this normal?Do I still need to reinstall the system?

**Comment by wangshunye12109** [comment]
### After I restart the computer, the system reports this error message.This may help.

Anonymous UUID:       FE0DB470-13B7-31C6-79E3-1687D26A250E
Sat Sep 15 09:33:48 2018
*** Panic Report ***
panic(cpu 0 caller 0xffffff7f8dfd25b7): NVRM[0/133:0:0]: Read Error 0x00627018: CFG 0xffffffff 0xffffffff 0xffffffff, BAR0 0x93000000 0xffffff914e7df000 0x136000a1, D0, P0/4
Backtrace (CPU 0), Frame : Return Address
0xffffff916538b950 : 0xffffff800aa6c1c6 
0xffffff916538b9a0 : 0xffffff800ab95274 
0xffffff916538b9e0 : 0xffffff800ab87544 
0xffffff916538ba50 : 0xffffff800aa1e1e0 
0xffffff916538ba70 : 0xffffff800aa6bc3c 
0xffffff916538bba0 : 0xffffff800aa6b9fc 
0xffffff916538bc00 : 0xffffff7f8dfd25b7 
0xffffff916538bc80 : 0xffffff7f8e0c41f0 
0xffffff916538bce0 : 0xffffff7f8e6837b8 
0xffffff916538bd20 : 0xffffff7f8e678d71 
0xffffff916538bd80 : 0xffffff7f8e735189 
0xffffff916538bdf0 : 0xffffff7f8e0fa2c8 
0xffffff916538be10 : 0xffffff7f8dfd90e6 
0xffffff916538bed0 : 0xffffff800b099785 
0xffffff916538bf30 : 0xffffff800b097ef2 
0xffffff916538bf70 : 0xffffff800b09752c 
0xffffff916538bfa0 : 0xffffff800aa1d557 
      Kernel Extensions in backtrace:
         com.nvidia.web.NVDAResmanWeb(10.3.3)[37FC338B-1C2C-3C37-8DAD-576DB29CC7F4]@0xffffff7f8df73000->0xffffff7f8e5ebfff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[AEA4C7F5-CCB0-338B-B471-CF28A9792522]@0xffffff7f8b294000
            dependency: com.apple.iokit.IONDRVSupport(519.20)[64AB0898-0DF1-32DF-850A-8840C3478439]@0xffffff7f8be33000
            dependency: com.apple.iokit.IOGraphicsFamily(519.20)[0E507098-E375-39B7-9AE2-AFF2C7A5D961]@0xffffff7f8ba4c000
            dependency: com.apple.AppleGraphicsDeviceControl(3.20.13)[55E796DB-EFBA-34DB-8148-E834A4383AD2]@0xffffff7f8be0c000
         com.nvidia.web.NVDAGP100HalWeb(10.3.3)[66B299E8-CBF2-398B-A290-781A4F8C589C]@0xffffff7f8e5ec000->0xffffff7f8e791fff
            dependency: com.nvidia.web.NVDAResmanWeb(10.3.3)[37FC338B-1C2C-3C37-8DAD-576DB29CC7F4]@0xffffff7f8df73000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[AEA4C7F5-CCB0-338B-B471-CF28A9792522]@0xffffff7f8b294000

BSD process name corresponding to current thread: kernel_task

Mac OS version:
17G65

Kernel version:
Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
Kernel UUID: 1AE5ACFD-3B6F-3D74-AD52-31F1430DBC6F
Kernel slide:     0x000000000a800000
Kernel text base: 0xffffff800aa00000
__HIB  text base: 0xffffff800a900000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)

System uptime in nanoseconds: 30332481785
last loaded kext at 10543455841: com.apple.driver.AudioAUUC 1.70 (addr 0xffffff7f8dbbf000, size 32768)
loaded kexts:
com.nvidia.web.GeForceWeb 10.3.3
com.nvidia.web.NVDAGP100HalWeb 10.3.3
com.nvidia.web.NVDAResmanWeb 10.3.3
com.nvidia.NVDAStartupWeb 10.3.3
com.apple.driver.AudioAUUC 1.70
com.apple.filesystems.autofs 3.0
com.apple.driver.AGPM 110.23.37
com.apple.driver.ApplePlatformEnabler 2.7.0d0
com.apple.driver.X86PlatformShim 1.0.0
com.apple.driver.AppleUpstreamUserClient 3.6.5
com.apple.driver.AppleHDAHardwareConfigDriver 281.52
com.apple.driver.AppleHDA 281.52
com.apple.driver.AppleGraphicsDevicePolicy 3.20.13
com.apple.AGDCPluginDisplayMetrics 3.20.13
com.apple.driver.AppleHV 1
com.apple.iokit.IOUserEthernet 1.0.1
com.apple.iokit.IOBluetoothSerialManager 6.0.7f10
com.apple.driver.AppleIntelKBLGraphics 10.3.6
com.apple.driver.pmtelemetry 1
com.apple.Dont_Steal_Mac_OS_X 7.0.0
com.apple.driver.AppleIntelPCHPMC 2.0.1
com.apple.driver.ACPI_SMC_PlatformPlugin 1.0.0
com.apple.driver.AppleThunderboltIP 3.1.1
com.apple.driver.AppleIntelKBLGraphicsFramebuffer 10.3.6
com.apple.driver.AppleFIVRDriver 4.1.0
com.apple.driver.eficheck 1
com.apple.driver.AppleOSXWatchdog 1
com.apple.driver.AppleSMCLMU 211
com.apple.driver.AppleIntelSlowAdaptiveClocking 4.0.0
com.apple.driver.AppleCameraInterface 6.01.2
com.apple.driver.AGDCBacklightControl 3.20.13
com.apple.driver.AppleBacklight 170.12.6
com.apple.driver.AppleMCCSControl 1.5.5
com.apple.filesystems.apfs 748.51.0
com.apple.driver.AppleFileSystemDriver 3.0.1
com.apple.filesystems.hfs.kext 407.50.6
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless 1.0.0d1
com.apple.BootCache 40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib 1.0.0
com.apple.AppleSystemPolicy 1.0
com.apple.driver.AppleTopCaseHIDEventDriver 133
com.apple.driver.AirPort.BrcmNIC 1241.31.1a9
com.apple.driver.AppleSmartBatteryManager 161.0.0
com.apple.driver.AppleACPIButtons 6.1
com.apple.driver.AppleRTC 2.0
com.apple.driver.AppleSMBIOS 2.1
com.apple.driver.AppleACPIEC 6.1
com.apple.driver.AppleAPIC 1.7
com.apple.nke.applicationfirewall 183
com.apple.security.TMSafetyNet 8
com.apple.security.quarantine 3
com.apple.kext.triggers 1.0
com.apple.driver.DspFuncLib 281.52
com.apple.kext.OSvKernDSPLib 526
com.apple.driver.AppleGraphicsControl 3.20.13
com.apple.iokit.IOAVBFamily 680.2
com.apple.plugin.IOgPTPPlugin 680.15
com.apple.iokit.IOEthernetAVBController 1.1.0
com.apple.driver.AppleSSE 1.0
com.apple.iokit.IOBluetoothHostControllerUARTTransport 6.0.7f10
com.apple.iokit.IOBluetoothHostControllerTransport 6.0.7f10
com.apple.driver.IOPlatformPluginLegacy 1.0.0
com.apple.AppleGPUWrangler 3.20.13
com.apple.driver.AppleHDAController 281.52
com.apple.iokit.IOHDAFamily 281.52
com.apple.iokit.IOAudioFamily 206.5
com.apple.vecLib.kext 1.2.0
com.apple.iokit.IOAcceleratorFamily2 378.26
com.apple.iokit.IOSurface 211.15
com.apple.driver.AppleSMBusPCI 1.0.14d1
com.apple.driver.AppleIntelLpssUARTv1 3.0.60
com.apple.driver.AppleIntelLpssUARTCommon 3.0.60
com.apple.driver.AppleOnboardSerial 1.0
com.apple.iokit.IOSkywalkFamily 1
com.apple.iokit.IOSerialFamily 11
com.apple.driver.X86PlatformPlugin 1.0.0
com.apple.driver.IOPlatformPluginFamily 6.0.0d8
com.apple.iokit.IOSlowAdaptiveClockingFamily 1.0.0
com.apple.driver.AppleThunderboltEDMSink 4.1.4
com.apple.driver.AppleThunderboltDPOutAdapter 5.5.5
com.apple.AppleGraphicsDeviceControl 3.20.13
com.apple.driver.AppleBacklightExpert 1.1.0
com.apple.iokit.IONDRVSupport 519.20
com.apple.driver.AppleSMBusController 1.0.18d1
com.apple.iokit.IOGraphicsFamily 519.20
com.apple.driver.usb.IOUSBHostHIDDevice 1.2
com.apple.driver.usb.cdc 5.0.0
com.apple.driver.usb.networking 5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice 1.2
com.apple.driver.usb.AppleUSBHub 1.2
com.apple.driver.AppleThunderboltPCIUpAdapter 2.1.3
com.apple.driver.AppleThunderboltDPInAdapter 5.5.5
com.apple.driver.AppleThunderboltDPAdapterFamily 5.5.5
com.apple.driver.AppleThunderboltPCIDownAdapter 2.1.3
com.apple.driver.AppleHPM 3.1.3
com.apple.driver.AppleIntelLpssI2CController 3.0.60
com.apple.driver.AppleXsanScheme 3
com.apple.filesystems.hfs.encodings.kext 1
com.apple.driver.AppleActuatorDriver 1404.4
com.apple.driver.AppleHIDKeyboard 205
com.apple.driver.AppleHSBluetoothDriver 133
com.apple.driver.IOBluetoothHIDDriver 6.0.7f10
com.apple.iokit.IOBluetoothFamily 6.0.7f10
com.apple.driver.AppleMultitouchDriver 1404.4
com.apple.driver.AppleInputDeviceSupport 1404.3
com.apple.driver.AppleHSSPIHIDDriver 53
com.apple.driver.AppleHSSPISupport 53
com.apple.driver.AppleThunderboltNHI 4.7.2
com.apple.iokit.IOThunderboltFamily 6.7.8
com.apple.driver.AppleIntelLpssSpiController 3.0.60
com.apple.driver.AppleIntelLpssDmac 3.0.60
com.apple.iokit.IONVMeFamily 2.1.0
com.apple.iokit.IO80211Family 1200.12.2
com.apple.driver.mDNSOffloadUserClient 1.0.1b8
com.apple.driver.corecapture 1.0.4
com.apple.driver.AppleIntelLpssI2C 3.0.60
com.apple.driver.AppleIntelLpssGspi 3.0.60
com.apple.driver.usb.AppleUSBXHCIPCI 1.2
com.apple.driver.usb.AppleUSBXHCI 1.2
com.apple.driver.usb.AppleUSBHostPacketFilter 1.0
com.apple.iokit.IOUSBFamily 900.4.1
com.apple.driver.AppleEFINVRAM 2.1
com.apple.driver.AppleEFIRuntime 2.1
com.apple.iokit.IOSMBusFamily 1.1
com.apple.iokit.IOHIDFamily 2.0.0
com.apple.security.sandbox 300.0
com.apple.kext.AppleMatch 1.0.0d1
com.apple.driver.DiskImages 480.60.1
com.apple.driver.AppleFDEKeyStore 28.30
com.apple.driver.AppleEffaceableStorage 1.0
com.apple.driver.AppleKeyStore 2
com.apple.driver.AppleUSBTDM 439.70.3
com.apple.driver.AppleMobileFileIntegrity 1.0.5
com.apple.iokit.IOUSBMassStorageDriver 140.70.2
com.apple.iokit.IOSCSIBlockCommandsDevice 404.30.2
com.apple.iokit.IOSCSIArchitectureModelFamily 404.30.2
com.apple.iokit.IOStorageFamily 2.1
com.apple.driver.AppleCredentialManager 1.0
com.apple.driver.KernelRelayHost 1
com.apple.iokit.IOUSBHostFamily 1.2
com.apple.driver.usb.AppleUSBCommon 1.0
com.apple.driver.AppleBusPowerController 1.0
com.apple.driver.AppleSEPManager 1.0.1
com.apple.driver.IOSlaveProcessor 1
com.apple.iokit.IOReportFamily 31
com.apple.iokit.IOTimeSyncFamily 680.15
com.apple.iokit.IONetworkingFamily 3.4
com.apple.driver.AppleACPIPlatform 6.1
com.apple.driver.AppleSMC 3.1.9
com.apple.iokit.IOPCIFamily 2.9
com.apple.iokit.IOACPIFamily 1.4
com.apple.kec.pthread 1
com.apple.kec.Libm 1
com.apple.kec.corecrypto 1.0

EOF
Model: MacBookPro14,1, BootROM MBP141.0178.B00, 2 processors, Intel Core i5, 2.3 GHz, 8 GB, SMC 2.43f6
Graphics: Intel Iris Plus Graphics 640, Intel Iris Plus Graphics 640, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445364533303445422D45474347202020
Memory Module: BANK 1/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445364533303445422D45474347202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x170), Broadcom BCM43xx 1.0 (7.77.37.31.1a9)
Bluetooth: Version 6.0.7f10, 3 services, 27 devices, 1 incoming serial ports
Network Service: USB Ethernet, Ethernet, en5
Network Service: USB 10/100/1000 LAN, Ethernet, en6
Network Service: Wi-Fi, AirPort, en0
Network Service: Thunderbolt Bridge, Ethernet, bridge0
USB Device: USB 3.0 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc., 33.1

**Comment by wangshunye12109** [comment]
I followed your advise and clean installed the system, but it still not work.......

**Comment by mayankk2308** [comment]
I see you tried testing on another Mac as well and it didn't work. Couldn't it be a hardware issue with your eGPU? Look into that.

**Comment by wangshunye12109** [comment]
I use another GPU（gtx 1070）and the question has been solved，thank you！O(∩_∩)O谢谢
