### ISSUE TITLE
No network access after running script on Big Sur

### ISSUE THREAD

**Issue by mikemosh** [mayankk2308/purge-wrangler#130]
I’m running Purge Wrangler on a 2015 MacBook Air On OS 11.1. Connections and cars are all working and recognized, but I cannot reach external networks after I run the script. I can still connect to WiFi or Ethernet but it will not connect to any external network.

**Comment by mayankk2308** [comment]
The script does nothing related to networks and the problem is probably elsewhere. No one else has reported the issue so I believe it may be a unique/coincidental issue on your system. You can try debugging it by creating a fresh install of macOS and testing there: https://support.apple.com/en-us/HT208891

**Comment by mikemosh** [comment]
This is definitely a purge wrangler issue that is changing something in the system configuration. I have attempted all the troubleshooting solutions I know of to bypass this issue and as soon as I run the GPU setup and the system restarts the network connectivity goes away, and returns whenever I uninstall and restart (Usually I have to go back to recovery and re-enable SIP/ART). Just very confusing what it would be shutting off to eliminate network connectivity even with Ethernet and WiFi being recognized and working on bootcamp. I have the system running perfectly on my bootcamp partition but lose network connectivity every time on my MacOS.

**Comment by mayankk2308** [comment]
@mikemosh feel free to browse the codebase if you believe this script modifies network-related configurations (spoiler: it doesn't). Of the troubleshooting solutions you tried, did you try my suggestion above? Does it happen immediately after running the script or is it when you actually have an eGPU plugged in that the network fails to function? What do you mean by "unable to connect to external network"  - is it an issue with the device connecting to router (DHCP), DNS resolution, or something else? There are many questions that need answering and the easiest way to start testing is with a clean install. 

I reiterate, and you can verify in the codebase - no network related components are modified in this script. You can see here most things the script cares about/may alter: https://github.com/mayankk2308/purge-wrangler/blob/master/purge-wrangler.sh#L99

**Comment by Mompel226** [comment]
Dear @mayankk2308, I have had the same issue mentioned by @mikemosh, and I can confirm it has been caused by purge-wrangler set-up. I did run the code just after updating to Big Sur and my internet connection is down, although, I can connect to my WiFi. I am not saying Purge-Wrangler code has changed any network related components but, somehow, it has definitely affected my access to the Internet. I will try to fix this issue by myself but I thought it was worth letting you know. Thank you very much for your code and all of your effort. All the best.

**Comment by mayankk2308** [comment]
@Mompel226 thanks for sharing your experience. "Internet is down" is too vague as a problem description to narrow down the actual issue and I don't even know what your system configuration (Mac model, Ethernet adapter, etc.) is. It also depends on what device/driver is used for Ethernet. Plus, before running the script, disabling SIP/ART is required. Did you test internet connectivity after this step and before executing the script? Also we should determine what "connectivity down" means. Is the system having trouble connecting to and receiving an IP from your router on Ethernet, or DNS, or something else? You can try resetting your network interface via `ifconfig`. I'm too busy to look further into this unfortunately so cannot help further at this time.

**Comment by Mompel226** [comment]
Dear @mayankk2308, I wasn't asking for help. I was informing you that it was not an isolated case. Now, I have figured out that the VPN I am using to access my research centre network was causing the issue. Therefore, I will advise anyone with a similar issue to uninstall all VPNs installed in their system before or after running the script (it doesn't matter). I hope this might help someone else. Thank you for your fast reply :)

**Comment by mayankk2308** [comment]
@Mompel226 cheers and thanks for sharing your experience!

**Comment by mikemosh** [comment]
@Mompel226 thanks for the suggestion! That is the one thing I didn’t try. I’ll give it a shot and see if that is what was blocking the connection after the script. I was assuming it had something to do with routing over the Thunderbolt port, I’ll uninstall my VPN and see if that solves it.
