### ISSUE TITLE
eGPU crashes when plugged in -  Radeon 5500XT, Macbook Pro 2015 (AMD dGPU) MacOS 10.15.6

### ISSUE THREAD

**Issue by OscarJsson** [mayankk2308/purge-wrangler#131]
MacBook Pro 15" 2015 (M370X)
MacOS 10.15.6
AMD Radeon R9 M370X 2 GB
Gigabyte Radeon 5500XT 8GB + Akitio Thunder 2 with 500W PSU
PurgeWrangler 6.3.3

My eGPU has stopped working, probably since updating from Mojave to Catalina. Now the system crashes whenever I plug the eGPU in - no matter if I first install the Purge Wrangler (manually, according to the Beginner's Guide) or not. If I leave the eGPU plugged in I get stuck in a boot loop - the system repeatedly crashes before reaching the login screen. 

I expect the eGPU to either get autodetected by the script or being able to enable it through manual installation (since I've read that the 5X00 GPUs can sometimes cause system crashes when hot-plugged).

I'll be happy to provide any logs that may be found helpful - be it PurgeWrangler logs or system logs. 

Many thanks in advance!

**Comment by mayankk2308** [comment]
Hi, I hope this isn't the case but if you manually set up eGPU support without connecting the eGPU (as per guide) and the GPU is still causing crashes, it could possibly be a DOA GPU (I've seen crashes with 5700 XTs). Otherwise I hope everything is set up correctly hardware-wise (power cables connected to GPU, etc.). Please let me know if you have since tried a different GPU.

**Comment by mayankk2308** [comment]
Closing as no response provided from user.

**Comment by OscarJsson** [comment]
Hi, sorry for the delay in getting back to you, I've been busy with finishing my uni thesis. Is there a way for me to test whether it's a hardware fault or something else?

As I mentioned, this GPU has worked at one point and I used it for GPU rendering. I think it stopped working after upgrading my OS (although I'm not a 100% sure). The Akitio hardware is set up as I've had it for several years and I've double checked that everything is connected properly. 

Do you think I should try upgrading to Big Sur and see if it works there? Is it of any help if I provide crash logs etc?
