### ISSUE TITLE
Script won t install from Terminal with error message "Please disable System Integrity Protection" even though SIP and ART are disabled

### ISSUE THREAD

**Issue by nico2555** [mayankk2308/purge-wrangler#132]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 13" early-2015 (working normal; all Thunderbolt 2 devices such as an external screen were disconnected prior to run the script. 
- **macOS Version**: 11.1
- **System GPUs**: Intel Iris Graphics 6100 
- **eGPU**:Sonnet eGFX Breakaway Box 350 TB 3 with ASUS Geforce GTC 1060 DUAL OC 6GB .
- **Script Version**: 6.3.3
- **Script Logs**: 
- 
You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
Script can t be executed in terminal "Please disable System Integrity Protection". SPI and ART are disabled.

### Expected Behavior
exectution of the script.

**Comment by mayankk2308** [comment]
What's your output for `csrutil status`.

**Comment by mayankk2308** [comment]
No response from user. Closing.
