### ISSUE TITLE
update to OS 10.15.7 - after SIP disabled, macbook won't restart

### ISSUE THREAD

**Issue by mikeyb411** [mayankk2308/purge-wrangler#135]
Hi realizing this isn't a purge wrangler issue, wondering if anyone else is having this issue after updating an older macbook to 10.15.7.  I go into terminal disable SIP, and macbook won't restart, it hangs during boot up.  

Thoughts?

**Comment by mayankk2308** [comment]
Interesting predicament, usually people have trouble starting up after _enabling_ SIP. Simple solution would be install macOS over your existing install (no data lost) with SIP disabled. Should work after that. Otherwise I suggest checking forums as this isn’t the place for this issue.
