### ISSUE TITLE
curl: no URL specified!

### ISSUE THREAD

**Issue by Vihangasamaradiwakara** [mayankk2308/purge-wrangler#136]
my issue is purge-wrangler not downloading to my MacBook Pro (MacBook Pro (Retina, 15-inch, Mid 2014)
This message appears
What should I do?

![Screenshot 2021-03-13 at 8 26 29 PM](https://user-images.githubusercontent.com/15066293/111039230-f6ef6180-8452-11eb-9abd-5d6c364ba1bb.jpg)

**After disabling the ISP and the ART curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information**

**Comment by Vihangasamaradiwakara** [comment]
My Os is macOS Big Sur (11.0.1) but **Manual Installation** also doesn't work
This message appears
![Screenshot 2021-03-13 at 11 44 44 PM](https://user-images.githubusercontent.com/15066293/111039886-7d597280-8456-11eb-807a-891afcd225ee.jpg)

**Comment by Vihangasamaradiwakara** [comment]
I found another terminal code by you ( https://github.com/mayankk2308/set-egpu )
after using this code this message appears

**External GPU must be plugged in for set-eGPU on macOS 10.14+.
![Screenshot 2021-03-14 at 1 39 00 AM](https://user-images.githubusercontent.com/15066293/111042996-10e66f80-8466-11eb-8ac2-c84466000ff9.jpg)**

then I connect my egpu and run the code again after few seconds I MacBook restart and this appears

**your computer restarted because of a problem press any key or wait a few seconds to continue starting up**
![IMG_20210314_012910](https://user-images.githubusercontent.com/15066293/111043108-ce716280-8466-11eb-8296-6b03249101c7.jpg)

this message came again and again until I unplug the egpu from my MacBook

What should I do?

**Comment by mayankk2308** [comment]
Set-eGPU requires working eGPU which yours isn’t as you haven’t yet set it up with purge-wrangler. Please fill in the issue template (shown when creating a bug report). I need to know what eGPU you are using. With respect to the installation issue, I will have to check, not sure what’s going on there.

**Comment by mayankk2308** [comment]
You are using an old version of purge-wrangler. Please use latest version for manual installation, then follow the guide on the wiki.

**Comment by Vihangasamaradiwakara** [comment]
I tried new releases ( https://github.com/mayankk2308/purge-wrangler/releases/tag/6.3.3 ) with the manual method **it works!** Anyway, my Setup is **Macbook pro 2014 retina 15.6 16GB, and my Egpu is Razer Core X with AMD Radeon RX 5500XT on macOS Big Sur** 

Thank you so much!

![Screenshot 2021-03-14 at 11 53 09 AM](https://user-images.githubusercontent.com/15066293/111059474-de676180-84bb-11eb-9a90-ddc6a4b29a1d.jpg)
