### ISSUE TITLE
No icon in the menu bar

### ISSUE THREAD

**Issue by sebastiannorrby** [mayankk2308/purge-wrangler#139]
I have installed the script and the Macbook pro is recognizing the egpu when i check system settings/about this computer. But i dont get the icon in the menu bar and it seems like its not running. I have disabled the AMD m370x. 
I have also tried to uninstall Purge-Wrangler a couple of times with no luck at all. Anyone of you that have a good answer on this one? 

Macbook pro mid 2015 with M370X
Big Sur 11.2.3
eGPU - Akitio Node TB3 with Nvidia 780

[eGPU.log](https://github.com/mayankk2308/purge-wrangler/files/6563286/eGPU.log)
[Extensions.log](https://github.com/mayankk2308/purge-wrangler/files/6563287/Extensions.log)
[GPUs.log](https://github.com/mayankk2308/purge-wrangler/files/6563289/GPUs.log)
[Kextstat.log](https://github.com/mayankk2308/purge-wrangler/files/6563290/Kextstat.log)
[Mac.log](https://github.com/mayankk2308/purge-wrangler/files/6563291/Mac.log)

**Comment by mayankk2308** [comment]
Known behavior for NVIDIA cards - you won't see the menu icon and can't eject NVIDIA GPUs, although the GPU should work fine.
