### ISSUE TITLE
Cannot Uninstall Due to Security Profiles

### ISSUE THREAD

**Issue by mmcdonnell-mulesoft** [mayankk2308/purge-wrangler#141]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)
- **macOS Version**: 11.4
- **System GPUs**: Intel Iris Graphics 655 1536 MB & AMD 5600
- **eGPU**: Razer Core v1
- **Script Version**: latest
- **Script Logs**: 

```
Kryptonite is now the successor of PurgeWrangler.

Please see this for more information: https://rb.gy/rlvozf

Proceeding...

Please disable Authenticated Root.
```

### Issue Description
I need to uninstall Purge-Wrangler but no longer have the permissions on my computer since the upgrade to Big Sur. It happens every single time. I do not have the means to disable FileVault, which means I can't disable Authenticated Root.

### Expected Behavior
Looking for a way to just do an uninstall without having to be able to "run purge-wrangler". Sorry if this is a dupe, but my company apparently uses jamf profiles and even when I'm "root" I'm not really "root" anymore.

**Comment by mayankk2308** [comment]
If you updated macOS, you don't need to uninstall anything and your system is clean. If you want to remove the script itself, see the advanced handbook which should have the information.
