### ISSUE TITLE
Cryptocurrency Address for Donations

### ISSUE THREAD

**Issue by ozum** [mayankk2308/purge-wrangler#144]
Hi,

Thanks for this great work.

PayPal is not allowed in some countries. Would you like to provide a cryptocurrency address for those who cannot use PayPal?

I suggest a USDT address over TRX/TRC network. Other networks have high transfer costs.

Best,

**Comment by mayankk2308** [comment]
At the moment, I’m not considering adding a crypto address.

If you were planning to donate, then I really appreciate the gesture. Cheers.

**Comment by ozum** [comment]
I came here to donate and opened this case to find a way other than PayPal. PayPal is not operating in my country and does not allow me to open an account or pay with a credit card. Using PayPal here is impossible.

If PayPal starts to operate here, I will donate. Currently, all I can do is starring the repository, and thanking you.

Best,

**Comment by mayankk2308** [comment]
@ozum I really appreciate the gesture and support, thank you, but don't worry about donating. I'm just happy you found my software useful. Initially I didn't even have Paypal until a lot of people insisted (I already had Paypal account so just linked that). If I add a crypto address, I'll update this issue.
