### ISSUE TITLE
egpu doesn't work

### ISSUE THREAD

**Issue by nicomsprod** [mayankk2308/purge-wrangler#146]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: Mac Pro (Late 2013)
- **macOS Version**: 12.0.1  2,7 GHz Intel Xeon E5 12 cœurs
- **System GPUs**: AMD FirePro D700 6 Go
- **eGPU**: Sonnet Breakaway 750 + saphir nitro+ radeon RX6700XT
- **Script Version**: pure wrangler 6.3.4
- **Script Logs**: Attach logs generated by the script.

>> Setup eGPU
Plug-in eGPU. Press ESC if you are not plugging in eGPU.
External GPU
GPU Arch
Thunderbolt
Radeon RX 6700/6700 XT / 6800M
Navi 22
Backing up.
rsync:
link_stat"/Volumes/MacintoshHD1/System/Library/Extensions/NVDAStartup.
kext"
failed: No such file or directory (2)
sync error:
some files
could not be transferred (code 23) at /System/Volumes/Da
ta/SWE/macOS/BuildRoots/b8ff8433dc/Library/Caches/com.apple.xbs/Sources/rsync/rs
ync-55/rsync/main. c(996) (sender=2.6.9]
Backup refreshed.
Patching for AMD eGPUs...
Patches applied.
Analyzing system..
No resolutions to any anomalies if present. See README.
Sanitizing system.
System sanitized
Restarting now.Mac-Pro-10:~ msprods (

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

>> System Diagnosis
Analyzing system
No resolutions to any anomalies if present. See README.
>> System Log
Generating system log.
Executing: /usr/bin/kmutil showloaded
No variant specified, falling back to release
Log generated on the Desktop.
Open an issue on Github and share this file.
Back to menu? [Y/NI: (

Thank you for your help

Nicolas Bossard 
MSPROD

**Comment by mayankk2308** [comment]
6700 XT is not supported by Apple (no drivers).
