### ISSUE TITLE
Blackscreen with TB1, macOS Catalina 10.15.7, Racer Core X, AMD Radeon RX 580

### ISSUE THREAD

**Issue by ALittleMoreMax** [mayankk2308/purge-wrangler#148]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 15" Mid-2012 Unibody
- **macOS Version**: 10.15.7
- **System GPUs**: Intel HD Graphics 4000 & NVIDIA GeForce GT 650M
- **eGPU**: Rauer Core X + AMD Radeon RX 580
- **Script Version**: PurgeWrangler (6.3.4)
- **Script Logs**:
[pwlog-2022-01-05-01-13-38.zip](https://github.com/mayankk2308/purge-wrangler/files/7811197/pwlog-2022-01-05-01-13-38.zip)

### Issue Description
There is a Black Screen on my Monitors Connected via eGPU. The Skript tried to use purge-nvda.sh AMD optimizations. After trying that the Skript told me to open an issue on Github and share this file.

### Expected Behavior
I Expected to get the eGPU running like it's supposed to... The Monitors and the eGPU is recognized successfully by the system settings

**Comment by mayankk2308** [comment]
It only suggested it, not execute it. Read the wiki before opening issues.

**Comment by ALittleMoreMax** [comment]
I read the Wiki but couldn't find an answer for that problem. The is no problem like that in the FAQ for my case
