### ISSUE TITLE
can't enable ti82 

### ISSUE THREAD

**Issue by ahmaddoobi1234** [mayankk2308/purge-wrangler#149]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 15" Mid-2014, Mac Mini Mid-2018, etc.
- **macOS Version**: 10.13.4, 10.14.5, etc.
- **System GPUs**: Intel Iris & NVIDIA GT 750M, etc.
- **eGPU**: Sonnet Breakaway 650 + RX Vega 64, etc.
- **Script Version**: Script version you used.
- **Script Logs**: Attach logs generated by the script.

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
Describe your problem. Does it occur every time?

### Screenshots
[pwlog-2022-01-29-11-48-24.zip](https://github.com/mayankk2308/purge-wrangler/files/7963341/pwlog-2022-01-29-11-48-24.zip)

**Comment by mayankk2308** [comment]
Fill the template. Anyway, M1 macs don’t support egpus.
