### ISSUE TITLE
Mac Mini 2018

### ISSUE THREAD

**Issue by 8291estudio** [mayankk2308/purge-wrangler#150]
Hi, my names is Raúl Mendoza.

### System Configuration

- Mac:Mac Mini 2018 3GHz 
- macOS Version: 12.3.1
- System GPUs**: Intel Core i5 8 GB
- eGPU: Razer Core X
- Script Version: curl -qLs $(curl -qLs https://bit.ly/2WtIESm | grep '"browser_download_url":' | cut -d'"' -f4) > purge-wrangler.sh; sh purge-wrangler.sh; rm purge-wrangler.sh

- Script Logs: Attached

### Issue Description
[pwlog-2022-06-24-11-52-58.zip](https://github.com/mayankk2308/purge-wrangler/files/8978673/pwlog-2022-06-24-11-52-58.zip)

Describe your problem. Does it occur every time?
I have followed all the steps but the graphics card is still not recognized when the computer is restarted after installation.

Expected Behavior
The external graphics card icon appeared in the menu bar.

### Screenshots
![Captura de Pantalla 2022-06-24 a la(s) 12 04 16](https://user-images.githubusercontent.com/71191255/175608817-79d62602-7ca0-4c95-9053-f32d0f33126c.png)

Thanks a lot.

**Comment by 8291estudio** [comment]
![Captura de Pantalla 2022-06-24 a la(s) 12 05 44](https://user-images.githubusercontent.com/71191255/175609004-4f3966ac-c761-418c-b1f2-8b3979888de8.png)

**Comment by mayankk2308** [comment]
You don’t need this script, I don’t even understand why you’re trying. 2018 Mac mini has native support for RX 580 gpu. If it doesn’t work, reach out to Apple/Razer support. I would try a different Thunderbolt cable to see if that helps.
