### ISSUE TITLE
Can´t use Purge Wrangler with my Setup (Mac Pro (end 2013) + 5700XT), please help me

### ISSUE THREAD

**Issue by Matterhorn1865** [mayankk2308/purge-wrangler#151]
System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- Mac Pro (End 2013)
- macOS Version 12.6 (21G115)
- System GPUs: 3 GHz 8-Core Intel Xeon E5
- eGPU: Razer Core X + AMD 5700XT 50th Anniversary Edition

Issue Description
I tried to install Purge Wrangler on my Mac but it shows me this now.

Expected Behavior
Please help me to solve this problem that I can use my eGPU with my Mac. Thanks 

Screenshots

![Bildschirmfoto 2022-09-20 um 22 51 09](https://user-images.githubusercontent.com/114028481/191363397-b2b1d378-598e-489f-8435-bdb717fc9720.png)

**Comment by mayankk2308** [comment]
This script is deprecated and I offer no further support, apologies.
