### ISSUE TITLE
only show NVIDIA Chip Model

### ISSUE THREAD

**Issue by wangshunye12109** [mayankk2308/purge-wrangler#16]
hi I got another new problem 
last time I use gtx1070,and eveything is fine.  
I bought another new 1060,and when I use the 1060,i get a problem.
I use：
1.MacBook2017 13 
2.macOS High Sierra 10.13.6 17G65
3.ASUS 1060 6G
4.ASUS XG station Pro
5.I use purge-wrangler->2.Enable NVIDIA eGPUs and then NVIDIA Patch: Enabled 
6.nvidia web driver is installed

 my problem：
1.my gpu can't be recognized ,the card is detected as Nvidia Chip Model.
2.the fans of GPU don't work
![image](https://user-images.githubusercontent.com/30544001/46254188-c81ce500-c4bd-11e8-883d-e4a513c6a8db.png)

**Comment by wangshunye12109** [comment]
My external display is black。
![wechatimg28](https://user-images.githubusercontent.com/30544001/46257701-b6a10080-c4f0-11e8-8f83-2c13d5f82efd.jpeg)
![wechatimg27](https://user-images.githubusercontent.com/30544001/46257706-c3bdef80-c4f0-11e8-90cf-03ddf0a21586.jpeg)

**Comment by mayankk2308** [comment]
Nothing on the script end can be done to resolve this problem. Try uninstall/reinstall. Consider trying a different vendor for the 1060 if it still doesn’t work.
