### ISSUE TITLE
Turning the internal display off on MBP 17

### ISSUE THREAD

**Issue by ogecgel** [mayankk2308/purge-wrangler#19]
Thanks so much for this. It works great. 
I was just wondering why the internal display doesnt turn off when I close the clamshell. 
High sierra 13.06
1060 6gb, Sonnet Enclosure
Using with 2 external monitors connetected to egpu.  

When I close the clamshell, the backlight turns off but the internal display is still on and some windows pops up on the internal display. 
Is there a solution for this without using switchresx or disable monitor?

**Comment by mayankk2308** [comment]
Unfortunately there isn’t that I know of. Clamshell mode + eGPU seems to only work with AMD eGPUs and Thunderbolt 3 macs (not older macs either). There might be workarounds if someone investigated, but that would be low on the priority list of workarounds to find. Using SwitchResX or DisableMonitor at the moment is the most optimal solution.
