### ISSUE TITLE
Nvidia eGPU not working on 10.14.4

### ISSUE THREAD

**Issue by shawnlinboy** [mayankk2308/purge-wrangler#21]
### Problem
I followed all the steps and installed all the drivers successfully. However, when I connect my eGPU to my monitor with a DP cable, the monitor flashed a message with "DP Signal Connected" and the screen was still black.

### Some diagnostics:

1. The `System info` app shows there were 2 Graphic cards connected.
![](http://ww1.sinaimg.cn/large/7adcb3b9gy1g24zva22srj21by0wyngj.jpg)
2. The "About this Mac" shows that only my eGPU was connected.
![](http://ww1.sinaimg.cn/large/7adcb3b9gy1g24zww60fkj20wo0dejxb.jpg)
3. There was no ![](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/il/macos-egpu-device-status-bar-icon.png) icon at menu bar for me to select my eGPU

### More Context
`Status Result`
```
>> System Status

Legacy AMD eGPUs  Disabled 
TB1/2 AMD eGPUs   Disabled
NVIDIA eGPUs      Enabled
Ti82 Devices      Enabled
```

`Anomaly Detection`
```
>> Anomaly Detection

Anomaly Detection will check your system to find
potential hiccups based on the applied system patches.

Patches made from scripts such as purge-nvda.sh
are not detected at this time.

Discrete GPU: None

No expected anomalies with current configuration.
```

### Just guessing

Is it possible that NVIDIA Web Drivers for Mojave has not been released caused this?

**Comment by mayankk2308** [comment]
As clearly mentioned in the documentation, there need to be Web Drivers for Mojave. Your guess is correct.
