### ISSUE TITLE
MacOS Won't boot after rebuilding kernel cache by LittleSnitch

### ISSUE THREAD

**Issue by karek314** [mayankk2308/purge-wrangler#23]
### Problem
I installed purge-wrangler while ago and it works nice, after installing I re-enabled SIP and system behaved correctly. Along with purge-wrangler kext I also use some other software which requires kext, like LittleSnitch. After updating LittleSnitch, my system wouldn't boot(loading bar was 100% and nothing happened for an hour), I dig around and found out that system wouldn't boot because of improperly signed purge-wrangler kext.

Not entirely sure why, but after mounting drive and running and running `kextcache -i /` system booted correctly and works fine, either with SIP enabled or disabled.

Any ideas what happened and how I can avoid such problems when rebuilding kext cache by other software?

### System Configuration
 - OS: 10.14.4

**Comment by mayankk2308** [comment]
As mentioned clearly in the documentation post-install:

> After installing the script, all settings as described in pre-requisites must persist. For instance, system integrity protection must remain disabled as long as the system is in the patched state.

Rebuilding kext cache will mostly resolve issue for only one boot when SIP is enabled. Keep it disabled while using purge-wrangler.sh.

**Comment by karek314** [comment]
Well, it works just fine with SIP enabled, after I ran kextcache -i / after updating LittleSnitch, it works fine. Reboots correctly.

**Comment by karek314** [comment]
If anyone encounters such issue, check out simple guide I made. Lifesaver.
https://gist.github.com/karek314/d9f8f862c3e3663513cce98249b4af0c
