### ISSUE TITLE
HDMI and TB2 ports not detecting external displays

### ISSUE THREAD

**Issue by Zack0611** [mayankk2308/purge-wrangler#24]
My eGPU works great and purge-wrangler is an indispensable tool, however, I've come into a hiccup if I want to connect my MBP to another external display say my tv downstairs. The HDMI port and TB2 ports don't recognize a connection. To be clear, I'm not connected to the eGPU, I'm just trying to go straight from MBP to my TV using either TB2 to HDMI or HDMI to HDMI. The ports worked fine before I initiated the script.

MBP Mid 2015

**Comment by mayankk2308** [comment]
Please state complete configuration information. 

Does the system work as expected after uninstalling the script?

Did you by chance use any other scripts? If so, which?

**Comment by mayankk2308** [comment]
Please respond soon. This issue will otherwise be closed for inactivity.
