### ISSUE TITLE
webdrv-release.sh HTTP404

### ISSUE THREAD

**Issue by elliottd** [mayankk2308/purge-wrangler#25]
I tried to follow the **Note About NVIDIA Setups** section of `README.md` but the mentioned file does not exist in the resources directory of the Master branch of this repository.

```
$ curl -s https://raw.githubusercontent.com/mayankk2308/purge-wrangler/master/resources/webdrv-release.sh | bash
bash: line 1: 404:: command not found
$
```

**Comment by mayankk2308** [comment]
Sorry about that. I plan on redoing the README very soon with an upcoming major release. This section would be removed then. Basic idea is: if you have Mojave and are trying to use a xx or later NVIDIA GPU won’t work.

**Comment by mayankk2308** [comment]
I have updated the command for the time being.
