### ISSUE TITLE
tbolt 1 unlock does not work with Catalina release

### ISSUE THREAD

**Issue by rkitover** [mayankk2308/purge-wrangler#31]
### System Configuration
- **Mac**: macbook air 2011
- **macOS Version**: 10.15 Catalina release installed with dosdude patcher
- **System GPUs**: Intel HD 3000
- **eGPU**: Akitio Node + tbolt 3 adapter + RX570
- **Script Version**: master

### Issue Description
Unlock patch does not work.
On boot system report shows "External GPU".
Works fine on 10.13 High Sierra with the same hardware configuration.
If I had to guess, I'd say the kext binary changed and needs a new binary patch, but I have no idea.

### Expected Behavior
Mac to boot to displaying from eGPU on monitor.

**Comment by mayankk2308** [comment]
@rkitover Dosdude-patched systems are not supported #28.

**Comment by rkitover** [comment]
Sorry I should have guessed that was the issue, I sent dosdude1 a tweet maybe he'll have some ideas.
