### ISSUE TITLE
SIP-is-disabled detection does not support custom configuration

### ISSUE THREAD

**Issue by Willian-Zhang** [mayankk2308/purge-wrangler#32]
### System Configuration
- **Mac**: MacBook 13,3
- **macOS Version**: 10.13.6
- **System GPUs**: Irrelevant
- **eGPU**: Irrelevant 
- **Script Version**: 6.0.2

### Issue Description
purge-wrangler does not detect system SIP as disabled if only "kext"  is disabled (which should be the one only required for purge-wrangler to function correctly)

### Expected Behavior
after 
``` bash
# csrutil enable --without kext --without debug
```
purge-wrangler should not return `disable SIP` message on first time install  

### More Context
https://github.com/mayankk2308/purge-wrangler/blob/5d7a1b06a8001184332c8f8140da511a67778b4a/purge-wrangler.sh#L317

**Comment by mayankk2308** [comment]
The script requires file system access and in one case NVRAM access as well, so it is simpler to just have it entirely disabled. I will not be changing this for now.

**Comment by jcbbuller** [comment]
How dangerous is it to leave your SIP disabled?

**Comment by mayankk2308** [comment]
I’ll just repost my Reddit response here:
> Even without SIP, modifying system files still requires administrative privileges. Issues can also occur due to developer oversight (bad software) as was the rare case with Google Chrome recently (off-topic: I don’t recommend google software anyway). However, user must grant permission (type in their password) voluntarily (even for a privileged daemon at least once at time of install) to facilitate any system modifications (hence purge-wrangler requests it). 

> SIP safeguards against situations where users mistakenly provide permission to potentially malicious apps (which is great, yes). If security is an important concern to you, then don’t use workarounds and buy a new system that meets your needs. Or find ways to bypass SIP, which is non-trivial - and if you can do it, malware can too, making it pointless.

> If you want to continue using this configuration, the only thing you should care about is ensuring that you know exactly what you are granting privileged permissions for (though you should do this even with SIP enabled). This is, after all, how many have used Macs before macOS El Capitan anyway.

**Comment by molle186** [comment]
@mayankk2308 :
tried to install the script but it occurs an error, that SIP is still enabled because of Bussystem verification is also still enabled.
All other features are disabled.
Do you have any suggestions?

**Comment by mayankk2308** [comment]
@molle186 sip needs to be completely disabled.
