### ISSUE TITLE
Unintended consequences

### ISSUE THREAD

**Issue by jcp-123** [mayankk2308/purge-wrangler#33]
This issue hit me... in October. If you disable SIP and install Google s/w - beware!

https://derflounder.wordpress.com/2019/09/25/google-keystone-update-breaks-macs-ability-to-boot-if-system-integrity-protection-is-disabled/

**Comment by mayankk2308** [comment]
Thank you for bringing up the issue here and linking to a thorough report and fix. Sadly since those scenarios are beyond the script’s control, I’ll have to close this as an issue. However, having it here for reference is great!
