### ISSUE TITLE
Doesn't recognize gpu with 10.15.1 Beta (19B77a)

### ISSUE THREAD

**Issue by ticotoo** [mayankk2308/purge-wrangler#34]
MacBook ProMacBook Pro (Retina, 15-inch, Mid 2014),2.8 GHz Intel Core i7 16 GB NVIDIA GeForce GT 750M 2048 MB, Intel Iris Pro 1536 MB
Mantiz Venus RX VEGA64  8 gb
 10.15.1 Beta (19B77a)
### Expected Behavior
After running the latest purge-wrangler script to use a AMD & external monitor & rebooting, the Vega64 is not recognized in the Mac system report.

### More Context
this setup has worked fine through all the Catalina Betas through GM release and 10.15.1 beta 1.

**Comment by mayankk2308** [comment]
Straight from the documentation:
> WARNING: Avoid macOS 10.15.1 beta. This release has disabled purge-wrangler AMD patches. Stay tuned for updates.

https://egpu.io/forums/mac-setup/script-enable-egpu-on-tb1-2-macs-on-macos-10-13-4/
