### ISSUE TITLE
False-positive script notification on an already-patched system

### ISSUE THREAD

**Issue by rkaregaran** [mayankk2308/purge-wrangler#36]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro (Retina, 13-inch, Late 2013)
- **macOS Version**: 10.15 (19A602)
- **System GPUs**: Intel Iris
- **eGPU**: Razor Core X + Radeon RX 580
- **Script Version**: 6.0.1

### Issue Description
See thread here with @mac_editor: 
https://egpu.io/forums/mac-setup/state-of-egpu-for-macs-catalina-10-15-update/paged/2/#post-67345

1. Upgraded to Mac OS 10.15
2. Reset eGPU configuration with Purge Wrangler
3. Installed Mac OS supplemental update to version (19A602)
4. After reboot, eGPU is still working, however, Purge Wrangler thinks settings have been reset even though system is still patched.

### Expected Behavior
Dialog should not appear.

**Comment by mayankk2308** [comment]
Thanks for posting it here. This issue is under investigation.
