### ISSUE TITLE
only getting less than half of the performance 

### ISSUE THREAD

**Issue by 1thinkdifferent** [mayankk2308/purge-wrangler#37]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 13 inch mid 2014.
- **macOS Version**: 10.15.
- **System GPUs**: Intel Iris & Nvidia GTX 680.
- **eGPU**: Akitio thunderbolt 2.
- **Script Version**: 6.0.2

### Issue Description
first of all I'm really glad that there's such a script to allow me to use the graphics card on Mac OS, ty guys so much. 
I'm only getting less than half of the performance for example I'm using hash cat on both windows and Mac using the same graphics card. 
on windows I get 50000 H/s 
on Mac OS I get 21000 H/s 

also noticeable FPS on the same game on Mac OS and windows 
for example 
Rocket league on windows I'm getting around 240 FPS 
on Mac OS it's unplayable 

also there's a screenshots from my system report show's that the link speed is only 2.5.

![Screen Shot 2019-10-24 at 3 02 33 AM](https://user-images.githubusercontent.com/16667244/67444801-e266bb00-f60a-11e9-9023-fcf5597ee559.png)
![Screen Shot 2019-10-24 at 3 02 53 AM](https://user-images.githubusercontent.com/16667244/67444802-e266bb00-f60a-11e9-9574-977ec21f5d95.png)

**Comment by mayankk2308** [comment]
Script cannot and does not affect GPU performance - that solely depends on drivers. Bandwidth is correct.

**Comment by 1thinkdifferent** [comment]
> Script cannot and does not affect GPU performance - that solely depends on macOS drivers. Bandwidth is correct.

I'm sorry to bother you, but you know why it's only working with half performance on Mac OS ? and how to fix it ?

**Comment by mayankk2308** [comment]
As said before, performance depends on drivers, but also on apps and what APIs they use. Rocket League is horrible on all GPUs on macOS. Try comparing other benchmarks such as Luxmark.
