### ISSUE TITLE
Random Restart 

### ISSUE THREAD

**Issue by 1thinkdifferent** [mayankk2308/purge-wrangler#38]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 13 inch Mid-2014.
- **macOS Version**: 10.15.
- **System GPUs**: Intel Iris.
- **eGPU**: Akitio Thunderbolt 2 + Nvidia GTX 680.
- **Script Version**:6.0.2.

### Issue Description
Random Restarts mostly on idle.

### More Context
panic(cpu 0 caller 0xffffff7f93fbb306): NVRM[0/193:0:0]: Read Error 0x00000200: CFG 0xffffffff 0x118010de 0x00100000, BAR0 0xb1000000 0xffffff914ae96000 0x0e4000a2, D0, P3/4
Backtrace (CPU 0), Frame : Return Address
0xffffff915b6328e0 : 0xffffff801353f98b 
0xffffff915b632930 : 0xffffff8013676c15 
0xffffff915b632970 : 0xffffff801366861e 
0xffffff915b6329c0 : 0xffffff80134e6a40 
0xffffff915b6329e0 : 0xffffff801353f077 
0xffffff915b632ae0 : 0xffffff801353f45b 
0xffffff915b632b30 : 0xffffff8013cd2d89 
0xffffff915b632ba0 : 0xffffff7f93fbb306 
0xffffff915b632c20 : 0xffffff7f9408811b 
0xffffff915b632c80 : 0xffffff7f966656cb 
0xffffff915b632cf0 : 0xffffff7f9668506d 
0xffffff915b632d30 : 0xffffff7f94150c14 
0xffffff915b632d50 : 0xffffff7f940869a1 
0xffffff915b632d90 : 0xffffff7f9667ef4c 
0xffffff915b632e40 : 0xffffff7f9411bc9b 
0xffffff915b632e70 : 0xffffff7f966801c3 
0xffffff915b632e90 : 0xffffff7f965b7e99 
0xffffff915b633040 : 0xffffff7f965d9251 
0xffffff915b6330b0 : 0xffffff7f96663726 
0xffffff915b633150 : 0xffffff7f940e1af0 
0xffffff915b6331a0 : 0xffffff7f940e1a52 
0xffffff915b6331f0 : 0xffffff7f96630f48 
0xffffff915b633250 : 0xffffff7f93fa2b66 
0xffffff915b633290 : 0xffffff7f93fa1e1e 
0xffffff915b633330 : 0xffffff7f940a2280 
0xffffff915b633390 : 0xffffff7f93f8a4b7 
0xffffff915b633430 : 0xffffff7f93f82370 
0xffffff915b633490 : 0xffffff7f93f823df 
0xffffff915b6334c0 : 0xffffff7f93f7fb72 
0xffffff915b633560 : 0xffffff7f93fbfb1c 
0xffffff915b6336e0 : 0xffffff7f93fc058d 
0xffffff915b6337d0 : 0xffffff7f9446298e 
0xffffff915b633820 : 0xffffff7f944309ab 
0xffffff915b633850 : 0xffffff7f944320c2 
0xffffff915b633880 : 0xffffff7f94432d0c 
0xffffff915b6338a0 : 0xffffff7f94487473 
0xffffff915b6338c0 : 0xffffff7f944280a0 
0xffffff915b6338e0 : 0xffffff7f94397ea4 
0xffffff915b633900 : 0xffffff7f9434ae88 
0xffffff915b633930 : 0xffffff7f9434ad5c 
0xffffff915b633950 : 0xffffff7f94369733 
0xffffff915b633980 : 0xffffff7f94373a42 
0xffffff915b6339c0 : 0xffffff8013c694b1 
0xffffff915b633a70 : 0xffffff8013c67b74 
0xffffff915b633ac0 : 0xffffff7f94375072 
0xffffff915b633b10 : 0xffffff7f94472bd8 
0xffffff915b633b60 : 0xffffff8013c70a73 
0xffffff915b633ca0 : 0xffffff8013626672 
	Backtrace continues...
      Kernel Extensions in backtrace:
         com.apple.nvidia.driver.NVDAResman(14.0)[ECB33CB3-2FE3-3E99-A4E6-ED7C5DA6D543]@0xffffff7f93f4e000->0xffffff7f94225fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[E6E855AD-A5B2-3518-A997-1384B4360708]@0xffffff7f93e65000
            dependency: com.apple.iokit.IONDRVSupport(558.3)[5BB372D5-4650-3EC3-B11B-CE5ECFA446BC]@0xffffff7f93f32000
            dependency: com.apple.iokit.IOGraphicsFamily(558.3)[23A17FD4-B8DA-3D9D-8AC5-D05039DF41ED]@0xffffff7f93ed3000
            dependency: com.apple.AppleGraphicsDeviceControl(4.1.46)[0266F94C-3545-376D-AF0F-802F6D340F1C]@0xffffff7f93f42000
         com.apple.nvidia.driver.NVDAGK100Hal(14.0)[D9BD5415-852D-3F99-B5D9-9E4FD7CABEEC]@0xffffff7f9656b000->0xffffff7f96716fff
            dependency: com.apple.nvidia.driver.NVDAResman(14.0.0)[ECB33CB3-2FE3-3E99-A4E6-ED7C5DA6D543]@0xffffff7f93f4e000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[E6E855AD-A5B2-3518-A997-1384B4360708]@0xffffff7f93e65000
         com.apple.GeForce(14.0)[96FF3A54-CD72-3035-9AFD-2E6EDA9D3310]@0xffffff7f94421000->0xffffff7f944bdfff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[E6E855AD-A5B2-3518-A997-1384B4360708]@0xffffff7f93e65000
            dependency: com.apple.iokit.IOSurface(269.6)[1B464F27-3144-32F7-83F5-22B06E67D8D0]@0xffffff7f93ea2000
            dependency: com.apple.iokit.IONDRVSupport(558.3)[5BB372D5-4650-3EC3-B11B-CE5ECFA446BC]@0xffffff7f93f32000
            dependency: com.apple.nvidia.driver.NVDAResman(14.0.0)[ECB33CB3-2FE3-3E99-A4E6-ED7C5DA6D543]@0xffffff7f93f4e000
            dependency: com.apple.iokit.IOGraphicsFamily(558.3)[23A17FD4-B8DA-3D9D-8AC5-D05039DF41ED]@0xffffff7f93ed3000
            dependency: com.apple.iokit.IOAcceleratorFamily2(438.1.23)[95FE222A-D225-3208-87A9-C2691A025BE7]@0xffffff7f94349000

BSD process name corresponding to current thread: mediaanalysisd

Mac OS version:
19A583

Kernel version:
Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64
Kernel UUID: 70EDD61F-86EE-3E1B-873F-98D909B78160
Kernel slide:     0x0000000013200000
Kernel text base: 0xffffff8013400000
__HIB  text base: 0xffffff8013300000
System model name: MacBookPro11,1 (Mac-189A3D4F975D5FFC)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 44873437589315
last loaded kext at 33241927190563: com.adguard.nfext	26 (addr 0xffffff7f98471000, size 184320)
last unloaded kext at 334622894408: @filesystems.msdosfs	1.10 (addr 0xffffff7f98471000, size 61440)
loaded kexts:
com.adguard.nfext	26
org.virtualbox.kext.VBoxNetAdp	6.0.14
org.virtualbox.kext.VBoxNetFlt	6.0.14
org.virtualbox.kext.VBoxUSB	6.0.14
org.virtualbox.kext.VBoxDrv	6.0.14
com.tuxera.filesystems.tuxera_ntfs	2017.12.18
com.realtek.driver.RtWlanU	1830.32.b7
>!A!BMultitouch	97
@fileutil	20.036.15
@filesystems.autofs	3.0
>AGPM	111.1.18
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
>!AHDA	283.14
>!AGraphicsDevicePolicy	4.1.46
@GeForce	14.0.0
@AGDCPluginDisplayMetrics	4.1.46
>!A!IHD5000Graphics	14.0.0
>!AUpstreamUserClient	3.6.8
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.0f8
>pmtelemetry	1
>!ABacklight	170.18
>eficheck	1
>!AMCCSControl	1.12
>!ALPC	3.1
@Dont_Steal_Mac_OS_X	7.0.0
>!ASMCLMU	212
>!A!IFramebufferAzul	14.0.0
>!A!ISlowAdaptiveClocking	4.0.0
>!ACameraInterface	7.6.0
>!AThunderboltIP	3.1.3
>AudioAUUC	1.70
>MaxTranserSizeOverrideDriver	489.11.2
>!UCardReader	489.11.2
>!UTCButtons	255
>!UTCKeyboard	255
>!AVirtIO	1.0
@filesystems.hfs.kext	522.0.9
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@filesystems.apfs	1412.11.7
>AirPort.BrcmNIC	1400.1.1
@private.KextAudit	1.0
>!ASmartBatteryManager	161.0.0
>!ARTC	2.0
>!AACPIButtons	6.1
>!AHPET	1.8
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	302
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
>IO!BHIDDriver	7.0.0f8
>!AMultitouchDriver	3400.35
>!AInputDeviceSupport	3400.27
@kext.triggers	1.0
|IOUSBUserClient	900.4.2
>DspFuncLib	283.14
@kext.OSvKernDSPLib	529
>X86PlatformPlugin	1.0.0
>!AGraphicsControl	4.1.46
|IOAVB!F	800.17
>!ASSE	1.0
@nvidia.driver.NVDAGK100Hal	14.0.0
@nvidia.driver.NVDAResman	14.0.0
>!ABacklightExpert	1.1.0
|IONDRVSupport	558.3
>!ASMBus!C	1.0.18d1
>IOPlatformPlugin!F	6.0.0d8
>!AHDA!C	283.14
|IOHDA!F	283.14
@!AGPUWrangler	4.1.46
@!AGraphicsDeviceControl	4.1.46
|IOAccelerator!F2	438.1.23
|IOSlowAdaptiveClocking!F	1.0.0
|IOGraphics!F	558.3
@plugin.IOgPTPPlugin	800.14
|IOEthernetAVB!C	1.1.0
|Broadcom!BHost!CUSBTransport	7.0.0f8
|IO!BHost!CUSBTransport	7.0.0f8
|IO!BHost!CTransport	7.0.0f8
|IO!B!F	7.0.0f8
|IO!BPacketLogger	7.0.0f8
>!UMultitouch	264
>usb.IOUSBHostHIDDevice	1.2
>!UAudio	320.47
|IOAudio!F	300.2
@vecLib.kext	1.2.0
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>usb.!UHub	1.2
>!AThunderboltDPOutAdapter	6.2.3
>!AThunderboltDPInAdapter	6.2.3
>!AThunderboltDPAdapter!F	6.2.3
>!AThunderboltPCIUpAdapter	2.5.2
>!AThunderboltPCIDownAdapter	2.5.2
|IOSerial!F	11
@filesystems.hfs.encodings.kext	1
|IOSurface	269.6
|IONVMe!F	2.1.0
>!AThunderboltNHI	5.5.8
|IOThunderbolt!F	7.4.5
|IO80211!F	1200.12.2b1
>mDNSOffloadUserClient	1.0.1b8
>corecapture	1.0.4
|IOSkywalk!F	1
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>DiskImages	493.0.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AKeyStore	2
>!UTDM	489.11.2
|IOSCSIBlockCommandsDevice	422.0.2
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOUSBMass!SDriver	157.11.2
|IOSCSIArchitectureModel!F	422.0.2
|IO!S!F	2.1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
|CoreAnalytics!F	1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|IOTimeSync!F	800.14
|IONetworking!F	3.4
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.Libm	1
@kec.corecrypto	1.0

**Comment by mayankk2308** [comment]
How often does this occur?

**Comment by 1thinkdifferent** [comment]
> How often does this occur?

sometimes it happens like three four times a day. 
and sometimes it's just once or twice a day.

**Comment by mayankk2308** [comment]
Ok. Does this happen only when system goes to/tries to wake up from sleep, or have you had this happen while on the desktop (idle) with system awake?

**Comment by 1thinkdifferent** [comment]
So after paying more attention to this issue, it happens after 15-20 minutes of idle, then the PSU of the EGPU fan speed up a bit like there's some sort of a load on the EGPU, if i move the cursor the fan gets back to the regular and nothing happens. If not , the computer will restart.

it took me a while to test that I hope it was clear, glad to share anything might help you.

**Comment by 1thinkdifferent** [comment]
I found something interesting here the last restart happened exactly at the time shown in this screenshots 
![Screen Shot 2019-10-27 at 3 17 29 PM](https://user-images.githubusercontent.com/16667244/67635212-0ce79b00-f8cd-11e9-9cad-24b5d897dcbd.png)

**Comment by mayankk2308** [comment]
Thank you for the logs! It *may* then have to do with the newly introduced clamshell patch for NVIDIA eGPUs. If disabling this patch does not fix the issue, then it may be bad drivers in Catalina (though I have a feeling the clamshell patch is to blame here). You can:
- Wait for script `6.0.3` where I shall decouple eGPU and clamshell patch for NVIDIA eGPUs (so latter may be optionally applied separately).
- Uninstall all patches and then try `5.1.3` which does not have clamshell patch. Don’t install web drivers when asked.

Thank you again for providing the logs.

**Comment by mayankk2308** [comment]
Hopefully removal of clamshell patch in `v6.1.0` addresses the problem. If problem still persists, then its cause may be beyond scope for this script. To apply the changes, uninstall patches, then reinstall with the latest script.
