### ISSUE TITLE
6.1.0 on 10.15.1 gets an error about TB 1/2

### ISSUE THREAD

**Issue by jwilker** [mayankk2308/purge-wrangler#39]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: Mac mini (Late 2012)
- **macOS Version**: 10.15.1
- **System GPUs**: Intel HD Graphics 4000 1536 MB
- **eGPU**: Sonnet eGFX Breakaway Puck RX 570
- **Script Version**: 6.1.0

### Issue Description
I just updated to 10.15.1 Didn't get the expected alert about re-running purge-wrangler so did it manually and got this error.

Patching for AMD eGPUs...
Unable to patch for TB1/2 AMD eGPUs.
Please file a Github issue.

### Expected Behavior
Install patch like previous versions.

**Comment by mayankk2308** [comment]
@jwilker Thank you for the report. Everything seems optimal so it is difficult to pinpoint the problem. I have the following suggestions:
- Run recovery in the script. Reboot. Retry patching.
- Install script again from README (long command) and try.

If those don't work:
- Uninstall any patches. Reboot and ensure system is working fine.
- Completely remove purge-wrangler via Terminal as follows:
```bash
sudo rm /usr/local/bin/purge-wrangler
sudo rm -rf /Library/Application\ Support/Purge-Wrangler
```
- Reinstall [macOS 10.15.1 update](https://support.apple.com/kb/DL2022?viewlocale=en_US&locale=en_US).
- Reinstall script from README and retry.

There has been [reported success](https://egpu.io/forums/builds/2013-27-imac-gtx-780m-4th-4c-amd-radeon-vii-10gbps-tb1-sonnet-breakaway-650-macos-10-15-1-pascalb/) on 10.15.1 with script 6.1.0 already so I am unable to determine why it would be different on your system. The error reported by the script implies that it was unable to find the section of a binary that it wished to patch. I might need additional information from you to debug this issue which I shall ping you on if you are okay with it.

**Comment by jwilker** [comment]
![Screen Shot 2019-11-06 at 10 21 00 AM](https://user-images.githubusercontent.com/527599/68321574-2f24aa00-007f-11ea-8bb4-28c501f106d4.png)
![Screen Shot 2019-11-06 at 10 18 48 AM](https://user-images.githubusercontent.com/527599/68321575-2f24aa00-007f-11ea-9964-e0c6bd1b1591.png)


Happy to provide anything you need. Tried a few variations. Will attempt to reinstall 10.14.1 now. Did the uninstall and rm with reinstall, no joy. 

Unplugged and reconnected the ePGU just in case. Noticed that the system sees it, but isn't showing the icon in the menu bar and obviously PW sees but can't path. 

Let me know what else you might need. Screen shots are attached in case they help.

**Comment by jwilker** [comment]
Ok FWIW. Ran the rm's again and reinstalled 10.15.1 then ran the install command from the readme.

Success. Just rebooted, icon for eGPU is in the menubar. I'll leave this open in case you want anything else from me, otherwise can close it.

**Comment by mayankk2308** [comment]
@jwilker Could I have screenshots of About This Mac (blur out serial number) and PCI section in System Report as well? To clarify, version to install is **10.15.1** not _10.14.1_. Let me know how the reinstall goes.

At any point did you do the following:
- After updating macOS to **10.15.1**, ran purge-wrangler in Single User Mode.
- After updating macOS to **10.15.1**, ran purge-wrangler **Recovery** option.

I would like to investigate the offending kexts. I will need the following:
Compress the following items (zip) and share here:
```
/Library/Application Support/Purge-Wrangler
/System/Library/Extensions/AppleGraphicsControl.kext
```
For the kext, first make a copy on the desktop, then compress.

**Comment by mayankk2308** [comment]
The following could be the problems here:
1. When updating to macOS 10.15.1, some/all kexts were not replaced.
2. purge-wrangler overwrote some kexts from its backup after updating.

**1** should not be the case as typically macOS updates rewrite extensions. However, I did come across a similar issue where it seemed kexts weren't overwritten causing another problem with the script - #36.

**2** cannot be done without user intervention - automatic execution of the script is not possible at this time.

This issue will merit further investigation if it occurs again.

**Comment by jwilker** [comment]
I did do the recovery actually, so that might be the culprit!

**Comment by mayankk2308** [comment]
@jwilker Ah now it makes sense! Did you get a warning while attempting recovery? If the script detects version discrepancy while doing recovery (such as recovering **10.15** kexts to **10.15.1**), you would get the following message:
```
System may already be clean.
Still attempt recovery?
```

**Comment by jwilker** [comment]
(Blush) yeah I did get the warning, but didn’t think it through enough and
just hit yes vs. trying to install.

John Wilker
Founder, 360|Conferences
twitter: jwilker
Chicago Roboto <http://chicagoroboto.com> | 360|iDev <http://360idev.com> |
360IAnDev <http://360andev.com>

Remember that bad times, are just times that are bad.

On November 6, 2019 at 11:28:10 AM, Mayank Kumar (notifications@github.com)
wrote:

@jwilker <https://github.com/jwilker> Ah now it makes sense! Did you get a
warning while attempting recovery? If the script detects version
discrepancy while doing recovery (such as recovering *10.15* kexts to
*10.15.1*), you would get the following message:

System may already be clean.
Still attempt recovery?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mayankk2308/purge-wrangler/issues/39?email_source=notifications&email_token=AAEAZ34PD322B4RU3WI6QBDQSMEDRA5CNFSM4JJXY4B2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDHQZOQ#issuecomment-550440122>,
or unsubscribe

**Comment by mayankk2308** [comment]
@jwilker Roger that. Perhaps the script/README should explain its use more clearly. For future reference, recovery should be relied on in cases when the system is unbootable. I knew having the feature to attempt recovery is a **double-edged sword** - on the one hand it helps those who have an unbootable system (even older kexts can boot newer OSes - as you saw), but can cause problems such as these :p - perhaps I'll re-evaluate this.

**Comment by jwilker** [comment]
Makes sense. I saw recovery and definitely thought it was “recover non
working patch" vs. the actual use case.

Thanks for all the help! Much obliged and glad it came down to PEBKAC

John Wilker
Founder, 360|Conferences
twitter: jwilker
Chicago Roboto <http://chicagoroboto.com> | 360|iDev <http://360idev.com> |
360IAnDev <http://360andev.com>

Remember that bad times, are just times that are bad.

On November 6, 2019 at 11:33:37 AM, Mayank Kumar (notifications@github.com)
wrote:

@jwilker <https://github.com/jwilker> Roger that. Perhaps the script/README
should explain its use more clearly. For future reference, recovery should
be relied on in cases when the system is unbootable. I knew having the
feature to attempt recovery is a *double-edged sword* - on the one hand it
helps those who have an unbootable system (even older kexts can boot newer
OSes - as you saw), but can cause problems such as these :p - perhaps I'll
re-evaluate this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mayankk2308/purge-wrangler/issues/39?email_source=notifications&email_token=AAEAZ35YKPF5RDDCQKOT6E3QSMEYDA5CNFSM4JJXY4B2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDHRJWA#issuecomment-550442200>,
or unsubscribe
