### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by chrisheninger** [mayankk2308/purge-wrangler#4]
Wanted to drop you a message to say thank you!

I installed v1.x last night– on my mid-2015 MacBook Pro that I had accidentally updated to 10.13.4– and it worked great.

Since that worked, I just updated my second laptop (same model) to 10.13.4 and proceeded to install v2.0.0 purge-wrangler. It too worked flawlessly.

<img width="487" alt="screen shot 2018-04-10 at 4 49 06 pm" src="https://user-images.githubusercontent.com/5051745/38589318-269aa462-3cdf-11e8-828f-9ec9c8366784.png">

I was extremely disappointed that Apple had inexplicably decided to drop TB2 support after it had worked fine in beta for months. You are a hero– thank you thank you thank you again! 🙏

**Comment by mayankk2308** [comment]
Glad it worked for you! Thanks for trying out v2.0.0. Much appreciated

In the future, please report findings (and thank yous ;)) like these on the [egpu.io](egpu.io/forums) forums. This area is only for "Issues".
