### ISSUE TITLE
Doesn't supported 60hz in 10.15.1

### ISSUE THREAD

**Issue by JuJin1324** [mayankk2308/purge-wrangler#41]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 15" Mid-2015
- **macOS Version**: 10.15.1
- **System GPUs**: Intel Iris Pro, Radeon R9 M370X
- **eGPU**: Razer Core X(thunderbolt2) + Radeon RX 590
- **Script Version**: 6.2.0
- **Script Logs**: [pwlog-2019-11-16-13-22-06.zip](https://github.com/mayankk2308/purge-wrangler/files/3853813/pwlog-2019-11-16-13-22-06.zip)

### Issue Description
The purge-wrangler has supported on 10.14.6(Mojave) with LG 34WK95U(5120x2160 60hz).
But on 10.15.1(Catalina), it dosen't support 60hz, only worked in 30hz every time I reboot macOS.

### Expected Behavior
Monitor has to be worked 60hz.

### Screenshots
<img width="667" alt="스크린샷 2019-11-16 오후 1 32 48" src="https://user-images.githubusercontent.com/16306672/68988100-96a7da00-0875-11ea-98c9-2dc2cbefe214.png">

주사율 is frequency. and I can't change 30hz to 60hz.

**Comment by mayankk2308** [comment]
**Script does not affect display resolution or refresh rate**. The issue is with macOS itself. Try other scaled resolutions and request help on egpu.io if required.

**Comment by mayankk2308** [comment]
https://egpu.io/forums/mac-setup/missing-scaled-resolution-w-vega-64-tb3-lg-34wk95u-w/
