### ISSUE TITLE
Restart issues with SIP enabled after installing script. 

### ISSUE THREAD

**Issue by jcbbuller** [mayankk2308/purge-wrangler#42]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 15" Mid-2015
- **macOS Version**: 10.14.6
- **System GPUs**: Intel Iris Pro 1536
- **eGPU**: AMD Radeon 580
- **Script Version**: 6.2.0
- **Script Logs**: None

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
After disabling SIP and downloading Purge-Wrangler, when I enabled SIP and restart my computer I can get to the login screen, but when I try and log in under my account the load bar either freezes about 1/3rd of the way up or is loading extremely slow. If I restart in Recover Mode and deactivate SIP it'll start up like normal. Do you have to keep SIP disabled all the time to use Purge-Wrangler? Are there risks in that? 

### Expected Behavior
I'd like to have Purge-Wrangler installed and SIP-enabled and still be able to login to my computer.

**Comment by mayankk2308** [comment]
Already discussed in #32 and mentioned in FAQ. Please read that before opening issues.
