### ISSUE TITLE
MacOS freezes as soon as I plugin an HDMI 2K display on the external eGPU

### ISSUE THREAD

**Issue by dademo-1999** [mayankk2308/purge-wrangler#43]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: iMac (27-inch, Late 2012)
- **macOS Version**: 10.15.2
- **System GPUs**: NVIDIA GeForce GTX 680MX 2 GB
- **eGPU**: Razer Core X Chroma + Powercolor Red Dragon XT 5700
- **Script Version**: 6.2.0
- **Script Logs**: pwlog-2019-12-12-13-47-15.zip

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
MacOS freezes as soon as I plugin an HDMI 2K display on the external eGPU
[pwlog-2019-12-12-13-47-15.zip](https://github.com/mayankk2308/purge-wrangler/files/3955829/pwlog-2019-12-12-13-47-15.zip)

### Expected Behavior
Should work on external display

### Screenshots
Cannot take screenshot. MacOS became unstable

**Comment by mayankk2308** [comment]
Known issue already mentioned in documentation: https://github.com/mayankk2308/purge-wrangler#hardware-chart
