### ISSUE TITLE
 GPU model is not recognized

### ISSUE THREAD

**Issue by logographer** [mayankk2308/purge-wrangler#46]
### **System Configuration**
Mac: MacBook Pro 15" Late-2013
macOS Version: 10.14.6
System GPUs: Intel HD Graphics 4000 1536 MB+NivdiaGT750M
eGPU: Akitio Node  +  AMD Radeon RX 580
Script Version: PurgeWrangler (6.2.2)
Script Logs: Attach logs generated by the script.
[pwlog-2020-02-12-14-52-58.zip](https://github.com/mayankk2308/purge-wrangler/files/4190270/pwlog-2020-02-12-14-52-58.zip)

>> System Status
Ti82 Devices      Enabled
TB1/2 AMD eGPUs   Enabled
Legacy AMD eGPUs  Enabled
NVIDIA eGPUs      Disabled
Web Drivers       Absent

>> System Diagnosis
Problem     Black screens on monitors connected to eGPU.
Resolution  Use purge-nvda.sh AMD optimizations.

### **Issue Description**
Mac dont' recognize my EGPU

### **Screenshoot**
<img width="921" alt="1" src="https://user-images.githubusercontent.com/36191925/74310744-d6b12700-4da8-11ea-9773-803db7505d58.png">
<img width="1016" alt="2" src="https://user-images.githubusercontent.com/36191925/74310749-d87aea80-4da8-11ea-936a-bb56acec7c9f.png">
<img width="1016" alt="3" src="https://user-images.githubusercontent.com/36191925/74310821-ffd1b780-4da8-11ea-877e-390afa8148ff.png">

**Comment by mayankk2308** [comment]
Please try connecting eGPU without any external display (if present). Ensure that power cables for the GPU are attached completely and reseat the GPU into the enclosure. Everything else seems ok in the logs.

**Comment by mayankk2308** [comment]
@logographer Any updates on the issue?

**Comment by logographer** [comment]
@mayankk2308  Thank you for your reply. I tried to connect the eGPU without external displays, but it still can't recognize. I think there is something wrong with my graphics card, I am going to try RX590，and see if it will be ok.

**Comment by mayankk2308** [comment]
@logographer cool - keep me updated on how it goes.

**Comment by logographer** [comment]
@mayankk2308  I change my graphic card to RX590, and it goes well. I ran purge-nvda that my display works,but my laptop's screen can't turn off when I close my lid.

**Comment by mayankk2308** [comment]
@logographer thats a known issue with purge-nvda (read its doc). Marking resolved.
