### ISSUE TITLE
Mac Mini won't finish booting with purge-wrangler installed

### ISSUE THREAD

**Issue by Madlan1** [mayankk2308/purge-wrangler#47]
### Issue Description
Since installing purge-wrangler every time I've shutdown and restarted my Mac it has become stuck on the boot screen with the progress bar at full. This is the second time occurring and I can't remember how I fixed it the first time.

### Expected Behavior
I would expect it to boot without any issues.

### System Configuration
- **Mac**: Mac mini late 2012
- **macOS Version**: 10.15.3
- **System GPUs**: Intel HD Graphics 4000
- **eGPU**: Zotac AMP Box Mini + amd radeon rx 580 4gb
- **Script Version**: Script version you used.

Currently I am unable to use my Mac Mini as a result.

**Comment by mayankk2308** [comment]
Are you booting with eGPU connected? Please try without it. If it’s still an issue, you can use script recovery: https://github.com/mayankk2308/purge-wrangler/wiki/Beginner's-Guide#recovery

**Comment by Madlan1** [comment]
I've tried with and without. 
When trying the script recovery it asks the questions as seen below under ">> Recovery".  I'm not sure what these do but hitting return causes it to run as shown and then restart. However it gets stuck again with full progress bar. (done without the eGPU connected)

![IMG_9849](https://user-images.githubusercontent.com/61136834/74632224-fc786a80-51b2-11ea-9fb5-0a14b6d674b7.jpg)

**Comment by mayankk2308** [comment]
Please disable system integrity protection.

**Comment by Madlan1** [comment]
I have and the line second from the bottom of the image says "( SIP is DISABLED)?

**Comment by mayankk2308** [comment]
@Madlan1 yes was editing my response above after I saw that. Anyway, to get back a working system, use Recovery boot and install macOS on top of existing install (no data loss).

**Comment by Madlan1** [comment]
Cheers, trying that now.

I think this may be how I fixed it when it first occurred, is there a way to prevent this happening?

**Comment by mayankk2308** [comment]
@Madlan1 this seems to be an isolated issue so I will need more information to understand why it is happening on your system.
1. **AMDLegacySupport.kext** should not have been installed in the first place as it is not required for RX 580. Did you manually install this via script? Automatic mode would have skipped it. 
2. When setting up the system with script, did everything go normally?
3. Perform verbose boot (CMD+V) of failed boot and share video capture. 
4. Test with an extra installation of macOS: https://support.apple.com/en-us/HT208891
     If extra install works as expected, then there must be something on your primary install that is  affecting normal operation with script.

You can try and manually remove **AMDLegacySupport.kext**  by booting into Single User Mode (as you did for recovery), then typing in the following commands:
```
mount -uw /
rm -rf ‘/Library/Extensions/AMDLegacySupport.kext’
kextcache -i /
```
Note that when booting into single user mode and while typing commands, you might see some activity that might cause some messages to show up as you type the command. In such a case, just delete whatever was typed, press enter multiple times, and on a fresh line try the command. Ensure that the `mount` command is executed properly. 

If you have familiarity with command line, you can even perform recovery manually as script stores original untouched kexts in **/Library/Application Support/Purge-Wrangler/Kexts/**.

**Comment by Madlan1** [comment]
I did not manually install it. I've just uninstalled and re-installed purge-wrangler as is wasn't allowing me to re-set up the eGPU. When executing the set up the script appears to have automatically downloaded the AMDLegacySupport.kext as shown in the image below.

Are you able to explain step 3. further please? Same with step 4.

What I've done previously is after purge-wrangler has been installed and set up is I've gone and enabled SIP. I'm thinking that this is why I've had difficulties booting after I've shutdown. Although I had tried disabling SIP again when booting failed this time and it didn't make a difference.

![IMG_9851](https://user-images.githubusercontent.com/61136834/74638106-65fe7600-51bf-11ea-9ceb-2535c941281a.jpg)

**Comment by Madlan1** [comment]
Sorry for the delayed response

**Comment by Moisie2000** [comment]
Hello:

With apologies if I'm contaminating the thread rather than providing any useful feedback...

I've posted this on the eGPU forum - but I suspect it's relevant here too: https://egpu.io/forums/mac-setup/os-x-10-14-6-security-update-december-10th-2019-egpu-is-no-longer-working/#post-74205

Short version:
- 2013 Mac Pro
- Sonnet EGFX Breakaway Box
- Radeon RX580
- Stopped working after the 2020-001 10.14.6 Security Update: the Mac now doesn't boot with the eGPU connected (usually the progress bar doesn't even start).

Unfortunately I'm not near the Mac in question at the moment, but I've brought the eGPU to another identical Mac, set it up identically - but this one is working as expected...

For the record, I ran the purge-wrangler 6.2.2 script automatically, and I had AMDLegacySupport.kext installed into /Library/Extensions.

Hope that's of _some_ help...

**Comment by mayankk2308** [comment]
I have figured out why **AMDLegacySupport.kext** is being installed for Polaris GPUs. The following line in code must be changed: https://github.com/mayankk2308/purge-wrangler/blob/5896876809048da6907da95a5c47057bcae2cb9e/purge-wrangler.sh#L78

Will test recovery system when I'm home after work today.

Instead of **Polaris**, array should have **Ellesmere**.

@Moisie2000 With Mac Pro, ensure you use only the bottom two Thunderbolt ports. Not sure why boot issues are occurring with your system.

@Madlan1 Sure:
3. https://www.idownloadblog.com/2015/08/17/how-to-boot-your-mac-in-verbose-mode/
4. Not sure what explanation is required - just create an extra install of macOS and try script there (follow that link).

**Comment by Moisie2000** [comment]
Hello:

> However, even if present, the kext should not be causing boot problems.

According the System Information, that AMDLegacySupport.kext wasn't loaded - so I guess you're right - it wasn't causing problems.

> @Moisie2000 With Mac Pro, ensure you use only the bottom two Thunderbolt ports. Not sure why boot issues are occurring with your system.

Bingo - that was it! Many thanks indeed!!!! Sorry if this information is obvious somewhere, but I couldn't find it for looking...

**Comment by Moisie2000** [comment]
Hello again:

And - for the record - I've just installed macOS 10.15.3 on the 2013 Mac Pro with eGPU connected: it booted just fine, and once I'd applied the purge-wrangler patches, it still booted just fine. (I know this isn't the same Mac, but I thought it useful to try with the same eGPU and macOS version.)

@Madlan1 - I suspect your issues are more 10.15.3 related, rather then eGPU related. :-( You might want to try reinstalling the OS as @mayankk2308 suggested, repairing the filesystem, or booting into Safe Mode to clear the caches...

**Comment by mayankk2308** [comment]
> What I've done previously is after purge-wrangler has been installed and set up is I've gone and enabled SIP. I'm thinking that this is why I've had difficulties booting after I've shutdown.

https://github.com/mayankk2308/purge-wrangler/wiki/FAQ#can-i-enable-system-integrity-protection-after-running-the-patch

Please read FAQ. SIP must remain disabled **at all times**.

@Moisie2000 the legacy kext won’t show up as loaded as its codeless, but either way it is not supposed to make system unbootable.

**Comment by mayankk2308** [comment]
All discussed issues should be resolved in **6.2.3**. Booting with SIP enabled is **not a supported configuration** and not deemed a valid issue.

**Comment by doanhai2401** [comment]
@mayankk2308 Could you help me out bellow problem?
I did according to your link:
https://github.com/mayankk2308/purge-wrangler/wiki/Beginner's-Guide#recovery
I did it carefully, step by steb: disable SIP, disabling secure Boot... but the final step, system responed that "No patch required for this Mac". you can see bellow picture.
<img width="571" alt="Screen Shot 2020-04-13 at 22 13 52" src="https://user-images.githubusercontent.com/63600530/79136947-08139680-7ddc-11ea-9fbc-b9da507f51b5.png">
Pls help me out! tks so much in advance.
My congiguration:
Mac mini 2018 + 10.15.1 + Sonnet box 550w + RX570.
hope hearing your response.

**Comment by mayankk2308** [comment]
@doanhai2401 Why are you even running this script?? Mac mini 2018 has native support for eGPU.

**Comment by doanhai2401** [comment]
> @doanhai2401 Why are you even running this script?? Mac mini 2018 has native support for your eGPU.

because I had a problem when I restart my mini, the screen turned dark. so I want to fix this. pls help me.

**Comment by mayankk2308** [comment]
@doanhai2401 that's not a problem this script solves. It is an issue on Apple's end.

**Comment by doanhai2401** [comment]
Oh, so how can i solve this problem? Do you have any suggestion?

Đoàn Thanh Hải
