### ISSUE TITLE
Radeon HD 8670 /R7 250/350 not working

### ISSUE THREAD

**Issue by Connor2007** [mayankk2308/purge-wrangler#49]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- iMac 21.5 inch, Late 2012
- macOS Catalina 10.15.3
- NVIDIA GeForce GT 640m 512 MB
- Akitio ThunderBolt 2
- 6.2.3
-[pwlog-2020-02-22-16-25-44.zip](https://github.com/mayankk2308/purge-wrangler/files/4239992/pwlog-2020-02-22-16-25-44.zip)

Thanks :)

**Comment by mayankk2308** [comment]
@Connor2007 This is not how issues are opened. You are supposed to describe your problem as well as have an appropriate title for issues. Example: #44 

Anyway, looking at the logs, you are using an Oland XT era AMD GPU. Not all AMD GPUs are guaranteed to be supported. I suggest upgrading to RX 460 or newer.

**Comment by Connor2007** [comment]
Okay thanks! Do you think a RX 550 4gb would work?
