### ISSUE TITLE
Nvidia 1080 and Mac Os Catalina

### ISSUE THREAD

**Issue by ASacoor** [mayankk2308/purge-wrangler#50]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 13" 2016, 4 Thunderbolts 3 Ports 
- **macOS Version**: 10.15.3
- **System GPUs**: Intel Iris 
- **eGPU**: Mantiz Venus + Nvidia GTX 1080
- **Script Version**: 6.2.3
- **Script Logs**: Attach logs generated by the script.
[pwlog-2020-02-23-09-26-53.zip](https://github.com/mayankk2308/purge-wrangler/files/4240687/pwlog-2020-02-23-09-26-53.zip)

### Issue Description
The GPU is showing connected but the screen stays black 

### Expected Behavior
The external screen must show MacOS , it only showing a blank screen

### Screenshots
<img width="1440" alt="Screenshot 2020-02-23 at 09 33 08" src="https://user-images.githubusercontent.com/61373584/75105733-b7738e80-561f-11ea-899e-1d7c34282409.png">

<img width="1440" alt="Screenshot 2020-02-23 at 09 33 22" src="https://user-images.githubusercontent.com/61373584/75105738-c4907d80-561f-11ea-92ee-5ad0f78ba4a4.png">

**Comment by mayankk2308** [comment]
NVIDIA Pascal cards are not supported in macOS Mojave or newer: https://github.com/mayankk2308/purge-wrangler/wiki/FAQ#why-do-patched-nvidia-drivers-not-work-on-macos-mojave-or-later
