### ISSUE TITLE
eGPU issue and freezes Random icons get large and giant

### ISSUE THREAD

**Issue by rickyashe** [mayankk2308/purge-wrangler#52]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: Mac Mini Late 2012 
- **macOS Version**: 10.15.3.
- **System GPUs**: Intel HD 4000
- **eGPU**: AKiTiO Thunder2 PCIe Box with Dell Power Supply Mod
- **Script Version**: 6.2.3
- **Script Logs**: Attached with Video

[pwlog-2020-03-04-16-31-32.zip](https://github.com/mayankk2308/purge-wrangler/files/4296057/pwlog-2020-03-04-16-31-32.zip)
[pwlog-2020-03-04-16-43-25.zip](https://github.com/mayankk2308/purge-wrangler/files/4296058/pwlog-2020-03-04-16-43-25.zip)
[IMG_0418.MOV.zip](https://github.com/mayankk2308/purge-wrangler/files/4296059/IMG_0418.MOV.zip)

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
Its Random cursor freezes get large like and bit icon and the spinning beach ball gets large also
### Expected Behavior
not to freeze up

### Screenshots
Added Video using Belkin ThunderBolt express dock also with the eGPU

**Comment by mayankk2308** [comment]
Why close #51 and open a new one? You could have edited the old one.

eGPU must be first device in Thunderbolt chain according to Apple. Logs indicate that you are connecting via a Belkin Dock. Please connect eGPU directly to mac and not via dock and report back if issue occurs.

**Comment by rickyashe** [comment]
Apologies I did not follow the proper format so I wanted to make sure the issue had been looked at

**Comment by rickyashe** [comment]
[pwlog-2020-03-05-20-23-57.zip](https://github.com/mayankk2308/purge-wrangler/files/4296154/pwlog-2020-03-05-20-23-57.zip)
still random  freezing attached files as requested again. I am using a Belkin thunderbolt 1 dock and the PCIe aikido biz is a thunder bolt 2 I ordered a new thunderbolt 2.0 dock to see if that helps it did it with my mid 2015 MacBook Pro also

**Comment by mayankk2308** [comment]
@rickyashe Thank you for the logs. Please try without the dock connected - just GPU. It may be that the Thunderbolt connection is being saturated.

**Comment by rickyashe** [comment]
This is promising my CPU temps have dropped 30+ degrees since I have unplugged the Thunderbolt hub... looks like I will be getting Powered usb 3.0 hubs to plug in my hard drives now.  checking the thunder bolt hub that's all I have plugged in.... weird I will stress test it some more and see how it hold ups

**Comment by rickyashe** [comment]
I think we are good you are correct the Thunderbolt 1 connection was be saturated Ive ran the metal app and stress tested it with ZERO freezing.
