### ISSUE TITLE
Individual configuration issue for MacPro6,1+GTX680

### ISSUE THREAD

**Issue by megaworm-dotcom** [mayankk2308/purge-wrangler#53]
### System Configuration
- **Mac**: Mac Pro 6,1 (Late 2013) 3.7 GHz Quad-Core Intel Xeon E5 64 GB 1866 MHz DDR3
- **macOS Version**: 10.13.6 Security patch 2020-01
- **System GPUs**: AMD FirePro D300 2048 MB
- **eGPU**: Sonnet Breakaway 550 + NVIDIA GTX 680
- **Script Version**: 6.2.3
- **Script Logs**: Attached

### Issue Description
I recently downgraded from Mojave to High Sierra (by first installing the original Mavericks with cmd+opt+shift+R then upgrading to High sierra from there). My intention is to be running Daz Studio and utilizing CUDA with my Nvidia GTX 680, on my Mac Pro 2013 through my Sonnet breakaway box and TB2 -> TB3 adapter. Not the finest card but better than CPU-only rendering. I had this setup working previously, with Daz studio recognizing the card as a CUDA device. However, after 2 days of trying to get this to work, I am having issues:

1. The eGPU disconnect icon does not appear in the menu.

2. The GPU is not recognized in the Displays window of About This Mac. Connecting a display after hotplugging the Thunderbolt to the external GPU results in no signal being output, and no additional monitor being added to the Displays preference pane. Connecting a display before hotplugging results in a red screen and a kernel panic.

3. The card is displayed in the Graphics tab of System Profiler. Purge-wrangler reports a successful patch. Nvidia web drivers detect the GPU and install successfully. CUDA drivers install successfully but then CUDA does not work.

4. CUDA driver system preference pane displays there is an update required, but there is no update available.

5. Security update 2020-01 is safe, according to the recent posts on this forum. It is installed, but CUDA does not seem to be happy with my installation.

With all the above issues, Daz studio is also not seeing the device as a CUDA rendering device. I assume fixing the above issues will fix this issue.

### Expected Behavior
CUDA should be working as reported by other users in insanelymac forums and daz3d forums with similar setups.

### Screenshots
Attached.
![Screen Shot 2020-03-14 at 3 08 27 PM](https://user-images.githubusercontent.com/62189549/76690835-f5097d00-6609-11ea-930f-61b176909917.png)
![Screen Shot 2020-03-14 at 3 08 33 PM](https://user-images.githubusercontent.com/62189549/76690836-f5a21380-6609-11ea-8813-ff002f21cbb9.png)
![Screen Shot 2020-03-14 at 3 08 38 PM](https://user-images.githubusercontent.com/62189549/76690837-f63aaa00-6609-11ea-9a6a-3faadc299483.png)
![Screen Shot 2020-03-14 at 3 08 46 PM](https://user-images.githubusercontent.com/62189549/76690838-f6d34080-6609-11ea-94ba-ac9ece78b70f.png)
![Screen Shot 2020-03-14 at 3 08 52 PM](https://user-images.githubusercontent.com/62189549/76690840-f6d34080-6609-11ea-8367-6acdb649e7ce.png)
![Screen Shot 2020-03-14 at 3 09 10 PM](https://user-images.githubusercontent.com/62189549/76690841-f6d34080-6609-11ea-973d-f6e6c3c4f1c3.png)
![Screen Shot 2020-03-14 at 3 10 27 PM](https://user-images.githubusercontent.com/62189549/76690842-f76bd700-6609-11ea-8441-368e886a1b67.png)
![Screen Shot 2020-03-14 at 3 11 23 PM](https://user-images.githubusercontent.com/62189549/76690843-f76bd700-6609-11ea-8c54-656fadd604ce.png)

[pwlog-2020-03-14-15-29-08.zip](https://github.com/mayankk2308/purge-wrangler/files/4333369/pwlog-2020-03-14-15-29-08.zip)

**Comment by mayankk2308** [comment]
GTX 680 does not require NVIDIA Web Drivers to function. But perhaps it’s required for CUDA (I don’t remember). Can you show me output for when you execute purge-wrangler to set up eGPU? Uninstall everything with the script and try.

**Comment by megaworm-dotcom** [comment]
```
>> PurgeWrangler (6.2.3)

 1. Setup eGPU
 2. System Status
 3. Uninstall

 4. More Options
 5. Donate
 6. Quit

>> Setup eGPU

Plug-in eGPU. Press ESC if you are not plugging in eGPU.

External GPU	GeForce GTX 680
GPU Arch	GK104 
Thunderbolt	2

Backing up...
Backup complete.

Patching for NVIDIA eGPUs...
Patches applied.

Analyzing system...
No resolutions to any anomalies if present. See README.

Sanitizing system...
System sanitized.
Modifications complete.

Reboot to apply changes.

Rebooting...
```

**Comment by mayankk2308** [comment]
Please try setting up the eGPU without connecting it. It seems you will need Web Drivers to get CUDA working as expected:
1. Uninstall everything via the script.
2. Remove/Uninstall NVIDIA Web Drivers as well as CUDA.
3. Run the script, but **don't connect** the eGPU. Set it up manually.
4. For Ti82, choose no.
5. For GPU vendor, choose NVIDIA.
6. For web drivers, choose yes, and follow instructions from there.
7. Ensure GPU is functioning normally and using NVIDIA Web Drivers.
8. Install CUDA and see if it is working as expected.

**Comment by mayankk2308** [comment]
@megaworm-dotcom Any updates?

**Comment by mayankk2308** [comment]
Closed due to inactivity.
