### ISSUE TITLE
6.2.3 on 10.15.3 ends with Unable to patch for TB 1/2 AMD

### ISSUE THREAD

**Issue by Sl4uGh7eR** [mayankk2308/purge-wrangler#54]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 17" Early-2011
- **macOS Version**: 10.15.3 dosdude1 patched
- **System GPUs**: Intel HD 3000 + Disabled 6750M via MacBook Pro dGPU Disabler (from dosdude1).
- **eGPU**: OWC Mercury Helios FX + RX 580
- **Script Version**: 6.2.3
- **Script Logs**: [pwlog-2020-03-21-10-25-08.zip](https://github.com/mayankk2308/purge-wrangler/files/4362681/pwlog-2020-03-21-10-25-08.zip)

### Issue Description
Just updated to Catalina 10.15.3 from High Sierra 10.13.6 and the script doesn't work anymore (could be a result of disabling the AMD dGPU in my MacBook (crucial to get Catalina working with full acceleration).

### Expected Behavior
Install patch like with previous versions of MacOS

**Comment by mayankk2308** [comment]
Dosdude patched systems are not supported.
