### ISSUE TITLE
eGPU not activating on Mac at all

### ISSUE THREAD

**Issue by bergenbill** [mayankk2308/purge-wrangler#55]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: iMac Pro (2017).
- **macOS Version**: 10.13.5
- **System GPUs**: Radeon Pro Vega 64,
- **eGPU**: Razer Core X Aluminum External GPU Enclosure (eGPU): Compatible w/Windows & Mac Thunderbolt 3 Laptops - NVIDIA/AMD PCIe Support - 650W PSU with a EVGA GeForce GTX TITAN X 12GB GAMING, Play 4k with Ease Graphics Card 12G-P4-2990-KR inside.
- **Script Version**: Purge-wrangler  6.2.3
- **Script Logs**: https://drive.google.com/file/d/1ACG8DcxBoUcU9mVcBOiqFIhieFWkjWVn/view?usp=sharing

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
The eGPU does not power on and is not recognized at all by the mac. 

### Expected Behavior
Once the script is followed and fully ran, the computer should see the nvidia cuda card.

### Screenshots
https://drive.google.com/file/d/1jYqL6xB9ywFlC7zzRnECHUD3jTd7UMXC/view?usp=sharing

**Comment by mayankk2308** [comment]
Were the logs taken when the eGPU was plugged into your Mac and powered on? 

If **yes**, it seems that the GPU is not being detected at all by macOS. Check and ensure that GPU has been plugged into enclosure correctly. Also verify that all power cables are plugged into the GPU properly. Razer Core X should have been visible in the logs irrespective of GPU being functional.

If **no**, then please provide logs with the eGPU connected to the Mac.

Your screenshot however does indicate that the script was unable to detect the GPU (I presume you plugged it in during the countdown). I recommend the following:
1. Uninstall everything using the script's **Uninstall** option.
2. Reboot your system and just connect the Razer Core X.
3. Check if you see Razer Core X in **System Report** (Apple Logo > About This Mac > System Report > Thunderbolt).
4. Check PCI section as well to see if there's anything there.

Screenshots of Step 3 and 4 would be great (you can upload them here - no need to use Drive). Once we ensure that macOS can see both the Razer Core X and GPU, we can move forward from there.

**Comment by bergenbill** [comment]
Thank you! I have not ruled out the possibility that the egpu is just defective and will not turn on. I have yet to see any indication that it boots. I do not have a PC to test it on. I'm currently setting up my macbook to test it there too.

**Comment by bergenbill** [comment]
No success on the macbook either :( You have me convinced its the egpu. I have never seen it power up. I'll look into getting a replacement. Thank you!!!

**Comment by mayankk2308** [comment]
Let me know if the replacement works out. Closing as of now.
