### ISSUE TITLE
Colors are saturated on hdr monitor

### ISSUE THREAD

**Issue by skurlow** [mayankk2308/purge-wrangler#56]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 15" Mid-2014
- **macOS Version**: 10.15.4
- **System GPUs**: Intel Iris & NVIDIA GT 750M, etc.
- **eGPU. AMD RX580
- **Script Version**: Script version you used.
- **Script Logs**: Attach logs generated by the script.

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
Colors are saturated due to new HDR feature in MacOS with a 4K hdr lg monitor. Turning off the new macOS display hdr feature still results in over saturated colors. I reset firmware using control+shift+option+power and the colors were fine after boot but then I put the displays to sleep using control+shift+power and then color saturation again happened.

Colors are not saturated on my other 4K non-hdr monitor.

### Expected Behavior
Normal colors and no color saturation.

**Comment by mayankk2308** [comment]
Sadly this issue is not related to the script so I cannot do anything about it. This seems like a more general macOS problem. Consider searching eGPU.io for similar cases.
