### ISSUE TITLE
No actively from egpu  

### ISSUE THREAD

**Issue by bergenbill** [mayankk2308/purge-wrangler#58]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro (15-inch, 2017)
 **macOS Version**: 10.13.6 (17G66)
- **System GPUs**: EVGA GeForce GTX TITAN X 12GB GAMING, Play 4k with Ease Graphics Card 12G-P4-2990-KR
- **eGPU**: Razer Core X Aluminum External GPU Enclosure (eGPU): Compatible w/Windows & Mac Thunderbolt 3 Laptops - NVIDIA/AMD PCIe Support - 650W PSU
- **Script Version**: RELEASE
V6.2.3
- **Script Logs**: Attach logs generated by the script.

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
eGPU seems to have power. At least when I turn it on, the lights in my house do that flick thing. I have went through the process probably 7 times. Have used the uninstalled many times as well.

### Expected Behavior
eGPU to be found as accessible.

Thunderbolt reports nothing is connected.
Same with PCI

### Screenshots
[pwlog-2020-03-31-21-34-24.zip](https://github.com/mayankk2308/purge-wrangler/files/4412813/pwlog-2020-03-31-21-34-24.zip)
[IMG_7282.pdf](https://github.com/mayankk2308/purge-wrangler/files/4412815/IMG_7282.pdf)

**Comment by mayankk2308** [comment]
In the image, your power cables are not installed correctly. The cables should completely slot into the GPU. The 2-pin connector of the 6+2pin connector is not appropriately slotted.

**Comment by bergenbill** [comment]
Will do! Hopefully that is it!

**Comment by mayankk2308** [comment]
Any updates?

**Comment by bergenbill** [comment]
Yes, thank you! I got it to register on my macbook. I still need to try it on my imac though. I'll let you know how that goes! :)
