### ISSUE TITLE
Mid-2015 MBP does not boot properly when eGPU attached

### ISSUE THREAD

**Issue by DPassarelli** [mayankk2308/purge-wrangler#6]
## Problem
After downloading and running `purge-wrangler.sh` (v3.0.2), the eGPU works flawlessly. But when I try to restart the system, it hangs at Apple icon. I can only login if the eGPU is disconnected.

## Steps to Reproduce
1. While computer is running, physically connect eGPU.
2. eGPU is successfully identified by computer.
3. Enjoy accelerated graphics 🎉
4. Shut down system for the night, leaving eGPU connected.
5. Restart the next morning, no bueno.

## Expected Behavior
System should reboot normally without having to physically disconnect, then login, then reconnect eGPU.

### MBP
* Model Identifier: MacBookPro11,4 (mid-2015, 15" Retina with Intel Iris Pro)
* Processor Name: Intel Core i7
* Processor Speed: 2.2 GHz
* O/S: macOS High Sierra 10.13.4
* Using official Apple TB2/TB3 adapter.

### eGPU
* Model:  MANTIZ MZ-02 (VENUS)
* Graphics: Radeon RX 570 8192 MB

### purge-wrangler
1. Downloaded from GitHub.
2. Followed instructions in README (very well done, BTW): `csrutil disable` in Recovery mode, script option # 1, also # 8 (disable hibernation). 

## More Context
If you need additional info, please just let me know. Thanks!

**Comment by MattyBalaam** [comment]
As far as I've been able to tell, this is an issue that Apple would need to fix.

**Comment by DPassarelli** [comment]
I forgot to mention that after I lock the screen using Cmd-Shift-Eject, the attached displays do not come back when I unlock the machine (via my watch). I have to physically disconnect (or just power cycle) the eGPU in order to see anything.

The attached displays are a pair of Dell U2715H, connected to the eGPU via DisplayPort.

**Comment by mayankk2308** [comment]
Thank you for the report. Can you boot in verbose mode and share logs for when boot hangs at Apple logo with eGPU plugged in? Ideally should not be a problem. You may try resetting SMC.

**Comment by DPassarelli** [comment]
Sorry for not responding sooner. I was not able to boot into verbose mode nor capture any logs, even after resetting the SMC. I finally decided that the problem might actually be hardware-related, so I uninstalled purge-wrangler, and I'll look at this again when I have a new box to play with.

Thanks for your help, nonetheless!

**Comment by DPassarelli** [comment]
Just as a follow-up, yes, the problem seems to have been hardware-related. I'm using the same video card in a different enclosure, and it works perfectly fine when attached to a Mac mini that has purge-wrangler installed.

**Comment by mayankk2308** [comment]
Thank you for the update. Surprising to see the Venus cause such an isolated problem. Perhaps it's a matter of firmware.
