### ISSUE TITLE
Kernel Panic after Security Update 2020-002 on High Sierra , MacMini 2012

### ISSUE THREAD

**Issue by wilcom2003** [mayankk2308/purge-wrangler#60]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 15" Mid-2014, Mac Mini Mid-2018, etc.
- **macOS Version**: 10.13.4, 10.14.5, etc.
- **System GPUs**: Intel Iris & NVIDIA GT 750M, etc.
- **eGPU**: Sonnet Breakaway 650 + RX Vega 64, etc.
- **Script Version**: Script version you used.
- **Script Logs**: Attach logs generated by the script.

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
Describe your problem. Does it occur every time?

**Comment by mayankk2308** [comment]
Nothing has been described and all I see is the issue template.
