### ISSUE TITLE
Version 6.2.3 on 10.15.1 gets an error about TB 1/2

### ISSUE THREAD

**Issue by krad1495** [mayankk2308/purge-wrangler#61]
### System Configuration
- **Mac**: MacBook Pro 13" Early 2011
- **macOS Version**: 10.15.4
- **System GPUs**: Intel HD Graphics 3000
- **eGPU**: Razer Core X with AMD Radeon RX 5700 XT
- **Script Version**: 6.2.3
- **Script Logs**: 
>> Setup eGPU

Plug-in eGPU. Press ESC if you are not plugging in eGPU.

External GPU	Radeon RX 5600 OEM/5600 XT / 5700/5700 XT
GPU Arch	Navi 10 
Thunderbolt	1

Backing up...
Backup refreshed.

Patching for AMD eGPUs...
Unable to patch for TB1/2 AMD eGPUs.
Generating system log...
Log generated on the Desktop.

Open an issue on Github and share this file.

### Issue Description
Have followed your fix instructions from Nov 2019 - https://github.com/mayankk2308/purge-wrangler/issues/39

 @jwilker Thank you for the report. Everything seems optimal so it is difficult to pinpoint the problem. I have the following suggestions:

Run recovery in the script. Reboot. Retry patching.
Install script again from README (long command) and try.

I have not tried reinstalling the OS yet, I would prefer not to if possible. Any help would be much appreciated.

**Comment by mayankk2308** [comment]
Dosdude patched Macs are not supported.
