### ISSUE TITLE
iMac Pro Strange Behavior

### ISSUE THREAD

**Issue by weisso5** [mayankk2308/purge-wrangler#62]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: iMac Pro
- **macOS Version**: 10.15.4
- **System GPUs**: Vega 56
- **eGPU**: Gigabyte Aorius + GTX 1070
- **Script Version**: 6.2.3
- **Script Logs**: 
[pwlog-2020-04-13-18-42-08.zip](https://github.com/mayankk2308/purge-wrangler/files/4472220/pwlog-2020-04-13-18-42-08.zip)

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
Disclaimer: Working Perfectly on my MBP15,2 with same eGPU setup and script version (never get black screen or need to power cycle)

1. Reboot with no TB3 peripherals SIP and Secure Boot Disabled
2. run Script
3. Successfully Detects eGPU
4. Reboot 
5. Black Screen after Login
6. Force Restart
7. eGPU not detected
8. Power Cycle eGPU (occasionally 2-3 times, waiting 10secs between cycle)
9. eGPU now detected.

### Expected Behavior
1. eGPU works correctly like MBP

### Screenshots

<img width="664" alt="Screen Shot 2020-04-13 at 6 31 39 PM" src="https://user-images.githubusercontent.com/1953387/79168131-1bf8d180-7db7-11ea-8107-4c028cadc6ef.png">

<img width="287" alt="Screen Shot 2020-04-13 at 6 53 43 PM" src="https://user-images.githubusercontent.com/1953387/79168521-223b7d80-7db8-11ea-8c4a-7785ecede72b.png">
<img width="346" alt="Screen Shot 2020-04-13 at 6 53 37 PM" src="https://user-images.githubusercontent.com/1953387/79168527-26679b00-7db8-11ea-8281-7f9f7dba48d2.png">

**Comment by mayankk2308** [comment]
Modern NVIDIA GPUs are not supported on macOS Mojave or later.

https://github.com/mayankk2308/purge-wrangler/wiki/FAQ

**Comment by weisso5** [comment]
Thanks, I wasn't sure what 'Modern' is considered, maybe adding some examples would point people in the right Google direction.

**Comment by mayankk2308** [comment]
Done - rephrased the question in FAQ.
