### ISSUE TITLE
Could not download AMDLegacySupport

### ISSUE THREAD

**Issue by yunfanfan** [mayankk2308/purge-wrangler#65]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: Mac Mini Mid-2018
- **macOS Version**: 10.15.4
- **System GPUs**: Intel Iris & Intel UHD Graphics 630 1536 MB. 
- **eGPU**: Gigabyte Gaming Box+R9 nano.
- **Script Version**: 6.2.3.
- **Script Logs**: https://drive.google.com/file/d/1vUw9rM7rLTOF5e9O0MYP7n_LDVq3AV5_/view?usp=sharing

### Issue Description
I can't download AMDLegacySupport

![couldnotdownloadAMDLegacySupport](https://cdn.jsdelivr.net/gh/yunfanfan/OSS@master/uPic/2020/04/couldnotdownloadAMDLegacySupport.png)

**Comment by mayankk2308** [comment]
Go to **[4] More Options** and install legacy support from there manually. Does it work?

**Comment by yunfanfan** [comment]
> Go to **[4] More Options** and install legacy support from there manually. Does it work?

It doesn't work. I got the same result.
![2020-04-24 09.44.23](https://cdn.jsdelivr.net/gh/yunfanfan/OSS@master/uPic/2020/04/屏幕快照%202020-04-24%20下午09.44.23%20上午.png)

**Comment by yunfanfan** [comment]
Can I download AMDLegacySupport from other place?

**Comment by yunfanfan** [comment]
I already download AMDLegacySupport from your link:"https://raw.githubusercontent.com/mayankk2308/purge-wrangler/6.2.3/resources/AMDLegacySupport.kext.zip"
How can I go directly to the next step？

**Comment by yunfanfan** [comment]
1. I unzip `AMDLegacySupport.kext.zip` into `/Library/Extensions/`
2. ###  [[ ${binpatch_enabled} == "1" || ${amdlegacy_enabled} == "1" ]] && printfn "System has previously been modified. Uninstall first." && return
3. success! Thank you!
![2020-04-24 10.58.31上午](https://cdn.jsdelivr.net/gh/yunfanfan/OSS@master/uPic/2020/04/屏幕快照%202020-04-24%20下午10.58.31%20上午.png)

**Comment by mayankk2308** [comment]
@yunfanfan good to see you fixed the issue but I would have expected the script to work. Do you have custom shasum binary?

What is your output for:
```
which shasum
```

**Comment by yunfanfan** [comment]
> @yunfanfan good to see you fixed the issue but I would have expected the script to work. I ran 6.2.3 on my system and it works fine. Do you have custom shasum binary?
> 
> What is your output for:
> 
> ```shell
> which shasum
> ```

I think it may be is network problem. I am not sure.
I'm sorry, I don't know where I can find `shasum`?
In terminal, I just looked at this, if this is the `shasum` you said?
![](https://cdn.jsdelivr.net/gh/yunfanfan/OSS@master/uPic/2020/04/屏幕快照%202020-04-25%20下午12.32.40%20下午.png)

**Comment by mayankk2308** [comment]
@yunfanfan Can you just run the above command: `which shasum` and share output?

**Comment by yunfanfan** [comment]
> @yunfanfan Can you just run the above command: `which shasum` and share output?
> 
> If it is a network problem, your eGPU name (Fiji) would not have been detected as that also requires network.

The output is "/usr/bin/shasum"
![屏幕快照2020-04-26下午10.49.42上午](https://cdn.jsdelivr.net/gh/yunfanfan/OSS@master/uPic/2020/04/屏幕快照%202020-04-26%20下午10.49.42%20上午.png)

**Comment by mayankk2308** [comment]
@yunfanfan Looks good. Can you do the same for `curl`?
```
which curl
```

**Comment by yunfanfan** [comment]
> @yunfanfan Looks good. Can you do the same for `curl`?
> 
> ```
> which curl
> ```

```
/usr/bin/curl
```
