### ISSUE TITLE
"Black screens/slow performance with eGPU"

### ISSUE THREAD

**Issue by JSunRae** [mayankk2308/purge-wrangler#66]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro (15-inch, 2016)
- **macOS Version**: 10.15.4 (19E287)
- **System GPUs**: IRadeon Pro 460 4 GB, Intel HD Graphics 530 1536 MB
- **eGPU**: Razer X with GTX 1080Ti
- **Script Version**: `curl -s "https://api.github.com/repos/mayankk2308/purge-wrangler/releases/latest" | grep '"browser_download_url":' | sed -E 's/.*"([^"]+)".*/\1/' | xargs curl -L -s -0 > purge-wrangler.sh && chmod +x purge-wrangler.sh && ./purge-wrangler.sh && rm purge-wrangler.sh`
- **Script Logs**: See attached.

### Issue Description
Tried to install for the first time and the GPU does not appear in the 'about Mac'. Also a monitor I have connected to the eGPU is not showing anything. Although the 'displays' menu does seem to recognize that there is a monitor, just doesn't show anything.

<img width="449" alt="Screen Shot 2020-04-27 at 1 29 36 pm" src="https://user-images.githubusercontent.com/61567145/80331544-b105cb00-888b-11ea-9d29-82c7ac243a7a.png">
[pwlog-2020-04-27-13-05-54.zip](https://github.com/mayankk2308/purge-wrangler/files/4537304/pwlog-2020-04-27-13-05-54.zip)
<img width="688" alt="Screen Shot 2020-04-27 at 1 30 59 pm" src="https://user-images.githubusercontent.com/61567145/80331568-bbc06000-888b-11ea-876b-ffa7df2f935e.png">
[pwlog-2020-04-27-13-20-40.zip](https://github.com/mayankk2308/purge-wrangler/files/4537309/pwlog-2020-04-27-13-20-40.zip)
[pwlog-2020-04-27-13-20-40.zip](https://github.com/mayankk2308/purge-wrangler/files/4537310/pwlog-2020-04-27-13-20-40.zip)

**Comment by mayankk2308** [comment]
https://github.com/mayankk2308/purge-wrangler/wiki/FAQ#are-maxwell-or-newer-nvidia-gpus-supported-on-macos

**Comment by JSunRae** [comment]
Hi. Sorry but I must be missing something I thought my 1080Ti is not that new. Where do I find a list of supported NVIDA GPU's? I've tried reading the wiki project and everywhere but found nothing.

**Comment by JSunRae** [comment]
> https://github.com/mayankk2308/purge-wrangler/wiki/FAQ#are-maxwell-or-newer-nvidia-gpus-supported-on-macos

Hi. Sorry but I must be missing something I thought my 1080Ti is not that new. Where do I find a list of supported NVIDA GPU's? I've tried reading the wiki project and everywhere but found nothing about which gpu's are supported.
