### ISSUE TITLE
Problem Black screens on monitors connected to eGPU.

### ISSUE THREAD

**Issue by ninediam0nd** [mayankk2308/purge-wrangler#68]
### System Configuration
- **Mac**: MacBook Pro 15" Mid-2014
- **macOS Version**: 10.15.4
- **System GPUs**: Intel Iris & NVIDIA GT 750M,
- **eGPU**: Sonnet Breakaway 650 + RX Vega 64,
- **Script Version**: 6.2.5
- **Script Logs**: Attach logs generated by the script.
[pwlog-2020-05-10-00-17-20.zip](https://github.com/mayankk2308/purge-wrangler/files/4604187/pwlog-2020-05-10-00-17-20.zip)

### Issue Description
Problem     Black screens on monitors connected to eGPU.
Resolution  Use purge-nvda.sh AMD optimizations.

the eGPU can recognised with my MacBook Pro but it had Black screens on another monitor (Dell UP2516D) was connected to eGPU

### Expected Behavior
is it possible to fix this problem on Catalina 10.15.4 ? if not, can you recommended how to make gpu work with my MacBook Pro 15", please

**Comment by mayankk2308** [comment]
It SAYS right in the script output what the resolution is. Read the complications table.
