### ISSUE TITLE
eGPU display issues and freezing 

### ISSUE THREAD

**Issue by cmoleka** [mayankk2308/purge-wrangler#69]
**System Configuration**
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.

**Mac:** MacBook Air (11-inch, Early 2015)
**macOS Version:** 10.15.4
**System GPUs:** Intel HD Graphics 6000 & MSI Radeon Rx 570 8GB GPU.
**Secondary Monitor:** DELL U3818DW
**eGPU:** Mantiz Venus MZ-02
**Script Version:** 6.2.5.
**Script Logs:** Attach logs generated by the script.
[pwlog-2020-05-09-05-14-10.zip](https://github.com/mayankk2308/purge-wrangler/files/4604220/pwlog-2020-05-09-05-14-10.zip)
[pwlog-2020-05-09-13-41-21.zip](https://github.com/mayankk2308/purge-wrangler/files/4604221/pwlog-2020-05-09-13-41-21.zip)

You can generate logs from the script by choosing **More Options > System Diagnosis & Logging.**

**Issue Description**
Freezing and display artifacts are appearing on both displays. The performance also appears to either slow down or freeze on windows switch and application launch.

Prior to the current state, the OS would mirror the Dell monitor on the Built-in-Display and cause the all system to look infested with artifacts. Disabling display mirror appears to have fixed that part. 

**Expected Behavior**
No artifacts, no freeze nor performance loss.

**Screenshots**
![IMG_0637](https://user-images.githubusercontent.com/38387370/81481089-8e64a200-91fb-11ea-9cbe-a807f71747a9.JPG)
![IMG_0638](https://user-images.githubusercontent.com/38387370/81481091-8f95cf00-91fb-11ea-9084-a308071fb101.JPG)
![IMG_0639](https://user-images.githubusercontent.com/38387370/81481092-90c6fc00-91fb-11ea-991d-416ccd75b4ef.JPG)
![IMG_6174](https://user-images.githubusercontent.com/38387370/81481097-93295600-91fb-11ea-9d27-a7a5c4e17c78.JPG)

**Comment by mayankk2308** [comment]
This script is only responsible for eGPU detection and does not dictate anything else. Change your  cables (HDMI/DP) etc. and see what works best.
