### ISSUE TITLE
AMD eGPU partially detected

### ISSUE THREAD

**Issue by konmouz** [mayankk2308/purge-wrangler#7]
### Problem
The eGPU is partially detected by the system after following the AMD patch guide. The eGPU is connected via a USB-C to Thunderbolt 2 adapter. As you can see from the screenshot below, the eGPU is not listed in the system overview, however, it is listed under Graphics in the system report. In addition, when the eGPU is connected the disconnect eGPU icon is available and successfully disconnects the eGPU when triggered, but it seems that the system is not using the card at all.

### Screenshots

<img width="596" alt="screen shot 2018-06-12 at 12 18 47" src="https://user-images.githubusercontent.com/15323961/41294852-f427c958-6e50-11e8-94ea-8268ea4fe1ca.png">

<img width="918" alt="screen shot 2018-06-12 at 12 18 56" src="https://user-images.githubusercontent.com/15323961/41294863-fa59137c-6e50-11e8-9931-1fed3b9854d3.png">

![screen shot 2018-06-12 at 12 20 43](https://user-images.githubusercontent.com/15323961/41294872-fd666902-6e50-11e8-93c6-af0c3fcab921.png)

### System Configuration
 - OS: macOS High Sierra 10.13.5
 - MacBook Pro (Retina, 15-inch, Mid 2015)
 - Internal graphics card: Intel Iris Pro 1536 MB
 - eGPU box: [Razer Core X](https://www.razer.com/gaming-laptops/razer-core-x)
 - eGPU card: [Sapphire Radeon RX 580 8GB](https://www.amazon.co.uk/Sapphire-11265-01-20G-Radeon-backplate-Graphics/dp/B071Y7CKM2/)

**Comment by mayankk2308** [comment]
Do you mean a **Thunderbolt 3 to Thunderbolt 2** adapter? USB-C itself is not certified for eGPUs. Thunderbolt is a requisite. They are different things.

Are you using an external display? If so, please make that the primary display in **System Preferences > General > Displays**. If not, then the internal display is by default, accelerated using the iGPU - so the above is normal. Apps can still use the eGPU if they have been coded to do so (**example**: Geekbench for compute, LuxMark for compute, and DaVinci Resolve). You can monitor GPU activity in **Activity Monitor > GPU History (Press CMD+4)**.

**Comment by konmouz** [comment]
@mayankk2308 thanks for the help, issue solved!
