### ISSUE TITLE
Disconnecting From eGPU causes computer to crash

### ISSUE THREAD

**Issue by WINNERHOUZ** [mayankk2308/purge-wrangler#70]
I use a Mid-2015 MBP w/ an eGPU Sonnet Breakaway with a Radeon RX580 4gb card. 
The first time I patched using Purge Wrangler I had no issues. I could connect to the EGPU and dissconnect as I wished. 

I ran an update on my computer to a newer version of Mojave and now, when I try to dissconnect from the eGPU, my computer is unable to switch back to it's internal GPU and the computer shuts down. 

Is there a fix for this? 

### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 15" Mid-2014, Mac Mini Mid-2018, etc.
- **macOS Version**: 10.13.4, 10.14.5, etc.
- **System GPUs**: Intel Iris & NVIDIA GT 750M, etc.
- **eGPU**: Sonnet Breakaway 650 + RX Vega 64, etc.
- **Script Version**: Script version you used.
- **Script Logs**: Attach logs generated by the script.

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
Describe your problem. Does it occur every time?

**Comment by mayankk2308** [comment]
Umm, please fill in the template? It’s there for a reason.

I don’t have a fix for that problem. Consider upgrading to Catalina and testing.
