### ISSUE TITLE
Output to an external Display from eGPU using Razer Core X + Shaphire Pulse RX580 8GB issue

### ISSUE THREAD

**Issue by Alex3thy** [mayankk2308/purge-wrangler#71]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 15" Late-2013
- **macOS Version**: 10.14.5.
- **System GPUs**: Intel Iris & NVIDIA GT 750M, etc.
- **eGPU**: Razer Core X + Shaphire Pulse RX580 8GB.
- **Script Version**: 6.2.5

- **Script Logs**: Attach logs generated by the script.
[pwlog-2020-05-13-10-04-56.zip](https://github.com/mayankk2308/purge-wrangler/files/4620423/pwlog-2020-05-13-10-04-56.zip).

[pwlog-2020-05-13-10-25-47.zip](https://github.com/mayankk2308/purge-wrangler/files/4620435/pwlog-2020-05-13-10-25-47.zip)
You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
I have a Razer Core X eGPU enclosure with an Shaphire Pulse RX580 8GB.
I have tried many things but I never was able to get an output from the eGPU to the external display. Tried different cables all outputs on the card (HDMi and Display Port).
Display is visible in system report but it won't show and picture.

### Expected Behavior
Be able to use an external display also.

### Screenshots
<img width="583" alt="Screenshot 2020-05-13 at 10 28 28" src="https://user-images.githubusercontent.com/65276519/81783830-9fb3f400-9504-11ea-9c20-79b541a3d5ff.png">

<img width="750" alt="Screenshot 2020-05-13 at 10 30 12" src="https://user-images.githubusercontent.com/65276519/81783940-ca9e4800-9504-11ea-9a24-a3d74dd94b42.png">

**Comment by mayankk2308** [comment]
Read wiki complications and follow script instructions when it informs you of problems.

**Comment by Alex3thy** [comment]
Thanks for your quick reply.
Please advise, where and what to follow?
Sorry but I am a noob user.
