### ISSUE TITLE
Radeon R9 290x Not working

### ISSUE THREAD

**Issue by MrBlaze9081** [mayankk2308/purge-wrangler#72]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 13"
- **macOS Version**: 10.15.4
- **System GPUs**: Intel Iris Plus 655
- **eGPU**: Razer Core X + Sapphire Radeon R9 290X 8GB
- **Script Version**: 6.2.5
- **Script Logs**:
[pwlog-2020-05-13-23-23-02.zip](https://github.com/mayankk2308/purge-wrangler/files/4625917/pwlog-2020-05-13-23-23-02.zip)

### Issue Description
Screen goes black and then comes back as if a display was connected, but the eGPU is never detected, and my external display never shows an output.

**Comment by mayankk2308** [comment]
@MrBlaze9081 unfortunately not all older AMD cards will work as expected. It is recommended to upgrade to an RX 460 or better.
