### ISSUE TITLE
Purge-Wrangler sees Gigabyte Radeon RX580 as NVidia 1050Ti

### ISSUE THREAD

**Issue by PepijnVerhoef** [mayankk2308/purge-wrangler#73]
The moment the script starts detecting a GPU, it thinks I have a NVidia 1050Ti while I'm trying to setup a Gigabyte Radeon RX580. Btw thank you so much for your effort and support!

**Comment by mayankk2308** [comment]
Please fill in the bug report template.

**Comment by mayankk2308** [comment]
Closed as user did not fill in bug report template.
