### ISSUE TITLE
{HELP] Turing/RTX eGPUs are not supported on macOS.

### ISSUE THREAD

**Issue by surajupd** [mayankk2308/purge-wrangler#74]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
- **macOS Version**: 10.15.4
- **System GPUs**: IIntel Iris Plus Graphics 650 1536 MB.
- **eGPU**: Razer Core X Chroma with GEFORCE GTX 1660 Super
- **Script Version**: Followed the Beginners Guide.
- **Script Logs**: 
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
surajprmacbook2:~ suraj$ curl -qLs $(curl -qLs https://bit.ly/2WtIESm | grep '"browser_download_url":' | cut -d'"' -f4) > purge-wrangler.sh; sh purge-wrangler.sh; rm purge-wrangler.sh
Password:

>> PurgeWrangler (6.2.5)

 1. Setup eGPU
 2. System Status
 3. Uninstall

 4. More Options
 5. Donate
 6. Quit

>> Setup eGPU

Plug-in eGPU. Press ESC if you are not plugging in eGPU.

External GPU	GeForce GTX 1660 SUPER
GPU Arch	TU116 
Thunderbolt	3

Backing up...
Backup refreshed.

Turing/RTX eGPUs are not supported on macOS.

Back to menu? [Y/N]: 

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
Please help, How do i install my eGPU for my mac.

**Comment by mayankk2308** [comment]
RTX is not supported - just like the script says. Read the wiki/FAQ before opening issues.

**Comment by surajupd** [comment]
Okay, thank you.

**Comment by surajupd** [comment]
Any suggestions?
