### ISSUE TITLE
Titan x card suddenly not reading and blowing non stop

### ISSUE THREAD

**Issue by bergenbill** [mayankk2308/purge-wrangler#75]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: iMac Pro (2017)
- **macOS Version**: 10.13.6
- **System GPUs**: EVGA GeForce GTX TITAN X 12GB GAMING, Play 4k with Ease Graphics Card 12G-P4-2990-KR
- **eGPU**: Razer Core X Aluminum External GPU Enclosure (eGPU): Compatible w/Windows & Mac Thunderbolt 3 Laptops - NVIDIA/AMD PCIe Support - 650W PSU
- **Script Version**: Current version
- **Script Logs**: Attach logs generated by the script.

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
This problem happens every time. The mac will not recognize the Nvidia card. It can find the eGPU with no problem. What is strange is that it was working just fine for a long time. A few weeks ago I noticed it the card was blowing a lot of air when I wasn't even using the device at all. So I shut it down. Today I tried to use it again for my 3D animation software and the card won't read. Also strange is that the card blows and extreme amount of air as soon as it is turned on and doesn't stop. I don't believe I made any changes to the computer from the last time I used the eGPU. I installed and uninstalled purge-wrangler many times and disables csrutil and T2. I have found the same results on my macbook pro too. 

### Expected Behavior
I plug in the eGPU and it works fine. 
<img width="931" alt="Screen Shot 2020-05-30 at 3 59 11 PM" src="https://user-images.githubusercontent.com/62412502/83343321-98833900-a2ad-11ea-90a4-584b0125da61.png">
<img width="929" alt="Screen Shot 2020-05-30 at 3 59 15 PM" src="https://user-images.githubusercontent.com/62412502/83343323-9d47ed00-a2ad-11ea-80ea-52bd92dd19ea.png">
<img width="935" alt="Screen Shot 2020-05-30 at 3 59 32 PM" src="https://user-images.githubusercontent.com/62412502/83343324-a042dd80-a2ad-11ea-8c14-47ed0bc6612b.png">
[pwlog-2020-05-30-19-30-18.zip](https://github.com/mayankk2308/purge-wrangler/files/4707016/pwlog-2020-05-30-19-30-18.zip)

**Comment by mayankk2308** [comment]
I don't see any Thunderbolt device or eGPU connected to your iMac in the logs. Please provide logs with eGPU connected after running the script setup.

**Comment by bergenbill** [comment]
Thank! The thing is, I did plug it in every time when I was instructed to during the process at the countdown. I would then manually tell it that I was using Nvidia and restart. All while leaving the eGPU connected.

**Comment by mayankk2308** [comment]
@bergenbill Script would have told you that it failed to detect eGPU and hence asked you to choose AMD or NVIDIA, because if it had detected it, then you wouldn't have to choose. Issue is not on script-side. Re-assemble your eGPU and ensure all power cables are connected appropriately.

**Comment by bergenbill** [comment]
Hi! It was connected. I made some recording of me going through the process here. 
https://drive.google.com/open?id=1Ep-0su-nmWV9GlPvqQjsZ4ICwqys7UCZ


Plus another version of the log. 
[pwlog-2020-05-31-13-48-32.zip](https://github.com/mayankk2308/purge-wrangler/files/4708401/pwlog-2020-05-31-13-48-32.zip)

**Comment by mayankk2308** [comment]
It clearly shows in the recording that the script is unable to detect the GPU. PCI section of system report should show something regardless of script if GPU is detected by macOS. So it’s not an issue I can do anything about - it’s on your end.

**Comment by bergenbill** [comment]
Got it, thanks! Is there a way to tell if it's the card or eGPU? As it shows the eGPU as a Thunderbolt connection in the Mac System Report but no card is registering. But then either read from your script. 

And the fact that the card blows so hard as soon as it's plugged in as me really stumped.

**Comment by mayankk2308** [comment]
> PCI section of system report should show something regardless of script if GPU is detected by macOS.

**Comment by bergenbill** [comment]
Ok thanks, that helps! I'll continue to investigate and see if Nvidia has any thoughts on the card blowing.

**Comment by bergenbill** [comment]
Will the script work in Catalina?
