### ISSUE TITLE
blackscreen on external monitor, internal monitor 1fps or less -gtx 1080, osx 10.13.6 (17g6030)

### ISSUE THREAD

**Issue by PIXELMOVER234** [mayankk2308/purge-wrangler#77]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 15" 2016 touchbar. 
- **macOS Version**: 10.13.6(17G6030)
- **system GPU** radeon pro 450.
- **eGPU**: aorus gtx 1080 gaming box
- **Script Version**: 6.2.5
- **Script Logs**:.[pwlog-2020-06-05-23-06-07.zip](https://github.com/mayankk2308/purge-wrangler/files/4739289/pwlog-2020-06-05-23-06-07.zip)

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**

### Issue Description
i run the script and when it reboots i get the usual graphics scramble in the startup, then it boots normally but my external monitor is black and it hardly hits 1fps on the internal monitor. i tried 'sudo pmset -a gpuswitch 0' but it didnt do anyhting. i also tried this with 13.6 17g5019 with the same results. 
plugging in the monitor after i get to login screen and it doesnt pick it up even if i log out and back in. 

if i plug the monitor in further into the boot i get the external monitor as the main display and the roles are reversed. the internal screen is black and the external monitor runs at 1fps. 

### Expected Behavior
i expected to be able to run my internal monitor and as many outputs as i have on my egpu with acceleration. 

### Screenshots
.unable to take screenshots as the problem is in the frame rate.

**Comment by mayankk2308** [comment]
Known issue. See https://egpu.io/forums/mac-setup/automate-egpu-efi-egpu-boot-manager-for-macos-and-windows/ instructions under AMD Macs using NVIDIA eGPUs and start from **step 3**. Nothing else can be done besides those steps. Try timing your eGPU plug in differently.
