### ISSUE TITLE
Purge wrangler not detecting my egpu (Radeon Vega Frontier)

### ISSUE THREAD

**Issue by rayazeed** [mayankk2308/purge-wrangler#78]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 15" Mid-2015
- **macOS Version**: Catalina 10.15.5
- **System GPUs**: Intel Iris
- **eGPU**: razer core x + AMD Radeon vega frontier
- **Script Version**: latest, just downloaded from the site
- **Script Logs**:
[pwlog-2020-06-06-17-51-56.zip](https://github.com/mayankk2308/purge-wrangler/files/4740508/pwlog-2020-06-06-17-51-56.zip)
 

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### purge wrangler does not detect the Radeon Vega Frontier
I'm just installing the new egpu configuration of razer core x and radeon vega frontier and i'm following the instructions of the script. But when detecting the EGPU it fails to detect it. Then I download the AMD Legacy Drivers. But still the egpu is not seen in the system hardware or in the activity monitor and I cannot specify certain apps to use it upon clicking command + I to choose the gpu since it is not found. 

Can you guys please help

**Comment by mayankk2308** [comment]
Logs indicate eGPU was either not connected during log dump, or that macOS is unable to detect a GPU at all. Check PCI section of System Report to ensure GPU is being detected. This is not a problem with the script - check your hardware to ensure macOS detects the device.
