### ISSUE TITLE
Error message during installation

### ISSUE THREAD

**Issue by kiddo71** [mayankk2308/purge-wrangler#79]
[pwlog-2020-06-10-09-19-31.zip](https://github.com/mayankk2308/purge-wrangler/files/4757071/pwlog-2020-06-10-09-19-31.zip)
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacPro  Late 2013
- **macOS Version**: 10.15.5, 
- **System GPUs**:dual AMD FirePro D300
- **eGPU**: Sonnet Breakaway 650 + RX Vega 64
- **Script Version**: 6.2.5 , Latest , downloaded 10 June 2020
- **Script Logs**: Attach logs generated by the script.

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
Errors during installation of the script after System update 

First re-enable (it worked fine till update) result: not working
Removed / redownload /reinstalled , result :  not working

the eGPU icon is non present any more

### Expected Behavior
As usuale that works but I got some few error messages

### Screenshots
This is the terminal screen just before restart:

>> PurgeWrangler (6.2.5)

 1. Setup eGPU
 2. System Status
 3. Uninstall

 4. More Options
 5. Donate
 6. Quit

>> Setup eGPU

Plug-in eGPU. Press ESC if you are not plugging in eGPU.

External GPU	Radeon RX Vega 56/64
GPU Arch	Vega 10 XL/XT 
Thunderbolt	2

Backing up...
Backup refreshed.

Patching for AMD eGPUs...
Patches applied.

Analyzing system...
No resolutions to any anomalies if present. See README.

Sanitizing system...
System sanitized.
Modifications complete.

Reboot to apply changes.

Rebooting...
  
bash-3.2$ osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/QXPScriptingAdditions.osax" cannot be used with the current OS because it has no OSAXHandlers entry in its Info.plist.

**Comment by mayankk2308** [comment]
That's a non-issue and shouldn't affect eGPU functionality (it may stop system from rebooting after running script - but you can do this manually).

**Comment by kiddo71** [comment]
Anyway the eGpu is not recognized.

It just report a generic amd an doesnot show any video

If can help I can do some test

Best regards

Claudio 

Claudio da iPhone

**Comment by mayankk2308** [comment]
Another user reported the same problem. Will investigate when possible. Reference #81.
