### ISSUE TITLE
How to uninstall with the version of 3.0.1?

### ISSUE THREAD

**Issue by teeerrytan** [mayankk2308/purge-wrangler#8]
### Problem
I currently installed with the version of 3.0.1. But I cannot upgrade to the newest version by install script. How can I fix this or how can I uninstall 3.0.1 then install the newest version again?
### System Configuration
 - OS: macOS 10.13.6
 - Version 3.0.1

**Comment by mayankk2308** [comment]
Just run the long command in **Step 2**. It should update your script to the latest version automatically.
