### ISSUE TITLE
Can not work with MBP 13" 2020

### ISSUE THREAD

**Issue by diving20000** [mayankk2308/purge-wrangler#80]
The MBP doesn't recognize eGPU.

**- Mac**: MacBook Pro 13" 2020 w/ 4 TB3 port
**- macOS**: 10.15.5
**- System GPUs**: Intel Iris Plus
**- eGPU**: Razer Core V2 + AMD R9 nano w/ 4G RAM
**- Script Version**: 6.2.5
**- Script Logs**: [pwlog-2020-06-10-18-11-24.zip](https://github.com/mayankk2308/purge-wrangler/files/4757834/pwlog-2020-06-10-18-11-24.zip)

**Issue Description**
My eGPU worked normally when I used MBP 13(2016), but it doesn't work with MBP 13(2020).  
It says "Core - unsupported" in System report-Thunderbolt3.

**Screenshots**
![image](https://user-images.githubusercontent.com/66726316/84257217-96d83180-ab47-11ea-836e-3b95b1cd9a75.png)

**Comment by diving20000** [comment]
I'm sure the eGPU is plug-in when it says "Detection not possible".

**Comment by mayankk2308** [comment]
This is normal - your eGPU has Ti82 chip so detection is not possible. Please read wiki/FAQ.
