### ISSUE TITLE
No option to enable TB1/2 support for AMD

### ISSUE THREAD

**Issue by doom1942** [mayankk2308/purge-wrangler#82]
### System Configuration

- **Mac**: Macmini 2018
- **macOS Version**: 10.15.5
- **System GPUs**: Intel UHD 630
- **eGPU**: Other World Computing Helios + RX 560
- **Script Version**: 6.2.5.
- **Script Logs**: Attached.
### Issue Description
Using a TB1/2 dock with an official mac converter cable,I can see the doc connected. i cannot see my egpu. 

### Expected Behavior
on my old macbook i was able to install this (without the apple tb2->tb3 converter) and i was asked if i wanted to enable TB1/2 support. 
I recon i should be presented with the option to enable support?

[pwlog-2020-06-14-16-29-14.zip](https://github.com/mayankk2308/purge-wrangler/files/4776746/pwlog-2020-06-14-16-29-14.zip)

**Comment by mayankk2308** [comment]
You don’t need this script. Logs indicate that macOS could not detect the eGPU at all, so the issue is something else (try re-assembling, etc.). This script is for older macs (for AMD GPUs).
