### ISSUE TITLE
AMD eGPU fails to install on 2011 17 inch MacBook Pro

### ISSUE THREAD

**Issue by lululombard** [mayankk2308/purge-wrangler#83]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 17" Late-2011
- **macOS Version**: 10.15.5 (19F101)
- **System GPUs**: Intel HD 3000 + a disabled AMD GPU via dosdude1's patch
- **eGPU**: Mantiz Venus + RX580 (using Apple TB3 to TB adapter and TB2 cable)
- **Script Version**: 6.2.5
- **Script Logs**: [pwlog-2020-06-16-20-03-19.zip](https://github.com/mayankk2308/purge-wrangler/files/4789661/pwlog-2020-06-16-20-03-19.zip)

### Issue Description
The installation fails with "Unable to patch for TB1/2 AMD eGPUs.". I tried booting the system with the eGPU plugged in and tried plugging it in when asked by the script, neither works. However, USB ports on the eGPU enclosure do work. And the eGPU works natively on my 2018 MacBook Pro.

### Expected Behavior
Installation that works

### Screenshots
![image](https://user-images.githubusercontent.com/2182934/84840264-0ac57e80-b00d-11ea-90ab-ab2b2cdb364e.png)

**Comment by mayankk2308** [comment]
Dosdude patched systems are not supported. This is explicitly mentioned in the wiki/guide.
