### ISSUE TITLE
EGPU on late 2015 iMac

### ISSUE THREAD

**Issue by Tankist-afk** [mayankk2308/purge-wrangler#85]
### System Configuration
macOS Catalina Version 10.15.5

iMac(Retina 5K, 27-inch, Late 2015)
Proc: 4 GHz Quad-Core Intel Core i7
Memory 32 GB 1867 MHz DDR3
Graphics AMD Radeon R9 M395X 4 GB

eGPU ASUS XG Station Pro + NVIDIA GeForce GTX 1070 Ti

purge-wrangler.sh

This is my first time trying to use an eGPU on mac.
Purchased Thunderbolt 2 cable from Apple, Adapter for Thunderbolt 2 to Thunderbolt 3.

When I follow instructions on patching the Nvidia eGPUs it gets stuck with three dots.
While checking the System Information I am able to see both graphics cards: AMD radeon R9 m395X and below Nvidia GTX 1070 Ti.

However I cannot see the symbol of eGPU in the system menu.

I am sorry, I have tried uninstalling and re-installing it back.

There is a black screen and will not power up when the eGPU Thunderbolt cable is plugged in.

I am trying to make the eGPU work with my iMac, but no luck. Any help would be greatly appreciated.

Thanks!
<img width="2419" alt="Screen Shot 2020-06-30 at 2 02 02 AM" src="https://user-images.githubusercontent.com/67623811/86089835-ff476e00-ba76-11ea-8288-aea537a9e747.png">

[pwlog-2020-06-30-01-48-58.zip](https://github.com/mayankk2308/purge-wrangler/files/4849760/pwlog-2020-06-30-01-48-58.zip)

**Comment by mayankk2308** [comment]
Read the wiki before opening issues.
