### ISSUE TITLE
Nvidia eGPU not working on 10.13.6

### ISSUE THREAD

**Issue by TaylorCawiezell** [mayankk2308/purge-wrangler#9]
Hello,

I have installed the driver successfully on my new 2018 Mac Book Pro 2018. The drivers download and work but my 1070 ti runs so slow it is unusable. I was able to get the mouse to work and open a few programs bringing it down to 30hz and 720p.

Any suggestions on how to fix this issue? It works wonders in Bootcamp.

Thanks,
Taylor

**Comment by mayankk2308** [comment]
Are you using an external display?

Are you mirroring displays? Disable mirroring, and set the external display as the main display.

Please follow the issue template for reporting problems.

**Comment by TaylorCawiezell** [comment]
I am using an external display.

I have set it to mirroring and extend both lag like crazy and the mac screen is black so the extend display option is practically unusable.

Excluding the information already provided here is my what happened. (Trying to follow the format mentioned)

1. I installed the drivers as described. Using the bash script below:

curl -s "https://api.github.com/repos/mayankk2308/purge-wrangler/releases/latest" | grep '"browser_download_url":' | sed -E 's/.*"([^"]+)".*/\1/' | xargs curl -L -s -0 > purge-wrangler.sh && chmod +x purge-wrangler.sh && ./purge-wrangler.sh && rm purge-wrangler.sh

2. I selected option 2 inside the script.

3. I rebooted with the eGPU plugged in and the external monitor plugged in as well.

4. Upon logging in the screen goes crazy and it works but its super slow, I believe its the gpu being slow as the cpu is monitored and showing normal idle speeds.

5. I tried plugging in every different port and selecting and unselected the extend monitor selection with no success.

6. Here is my setup:

2018 i9 MBP
High Sierra 10.13.6
Mantiz eGPU
GTX 1070ti
(Again Bootcamp works great just mac os)

**Comment by mayankk2308** [comment]
Thank you for providing a step-by-step. 

Try plugging in the egpu after booting. Also try logging in and out.

**Comment by TaylorCawiezell** [comment]
Okay, it's working now with no lag. Here is what I did. 

1. Set external monitor as extended and the main display.
2. I plugged in the eGPU after booting.
3. Logged Out and Logged back in

Is this what you have to do every time? 

Is that the state of Nvidia drivers on mac?

Thanks!

**Comment by mayankk2308** [comment]
It really depends. Some setups are straightforward, some aren’t haha. Glad to see it’s fixed for you. The problem is likely your AMD card. That’s why it doesn’t work straightaway with NVIDIA eGPU. You will likely have to always log out/in.

**Comment by TaylorCawiezell** [comment]
You're probably right! Thanks for the help!

**Comment by simleap** [comment]
I'm having the same issue with black out external displays. Egpu and monitors are detected, but only the external display has black out screen.
![screenshot 2018-11-15 12 30 09](https://user-images.githubusercontent.com/1457042/48532269-4698df00-e8d2-11e8-954d-ed583e7d35fe.jpg)
I tried:
1. Set external monitor as extended and the main display.
2. I plugged in the eGPU after booting.
3. Logged Out and Logged back in
Still not working.

My setup:
Macbook pro mid 2014 Nvidia M750
OSX Mojave 10.14.1
GIGABYTE RX 580 8G Graphic Card eGPU

**Comment by mayankk2308** [comment]
@simleap Your Mac also requires [purge-nvda.sh](https://github.com/mayankk2308/purge-nvda). You can read more about it [here](https://egpu.io/forums/mac-setup/nvidia-workaround-for-high-sierra-egpu-acceleration/).

**Comment by simleap** [comment]
@mayankk2308 I tried purge-nvda.sh and it made my mac freeze on boot apple logo. Maybe it doesn’t support 10.14+ ?

**Comment by mayankk2308** [comment]
@simleap Sometimes the NVRAM value isn’t set - this is mentioned in the eGPU.io post I linked to. Please check that. I recall others using it just fine on Mojave. Cannot test myself as I do not have such a Mac anymore.

**Comment by simleap** [comment]
@mayankk2308, it works! thanks

**Comment by mayankk2308** [comment]
@simleap great! 👍

**Comment by allocenx** [comment]
> @simleap great! 👍

Please what was the thing to do? I've literally tried everything, even that purge-nvda.sh thing...the monitor is still black...

**Comment by mayankk2308** [comment]
@allocenx What is your configuration (detailed)?

**Comment by allocenx** [comment]
> @allocenx What is your configuration (detailed)?

Hello, well, i got a macbook pro 13", i7+16gb ram, 2018. And just today i received the Asus XG Pro Station and put my nvidia gtx 1070 into it. I literally have followed every step possible and impossible, even that automatic-efi thing and still wouldnt work.

More than that, the video card is actually recognized into the system report in PCI, but wont work as no eGpu icon the menu bar is shown, neither to say the fact that in Activity Monitor is not shown at all. I do not know what to do anymore...Im feeling disapointed, i really wanted the egpu to work.

Also, i have all the things disabled, sip disabled, alllow bootable extern etc.

Also i am on Mojave 10.14.4.

**Comment by mayankk2308** [comment]
@allocenx Mojave is not supported due to lack of drivers. From the documentation:

> ### Note About NVIDIA Setups
> Modern NVIDIA GPUs (Maxwell or better) depend on NVIDIA Web Drivers which NVIDIA provides > > per macOS release. **Please ensure that there is a driver available for your current system**. You can check that using the following command:

> ```bash
> curl -s https://raw.githubusercontent.com/mayankk2308/purge-wrangler/master/resources/webdrv-release.sh | bash
> ```

> For minor macOS version variations (**10.13.4 -> 10.13.5** for example), you may use **purge-wrangler.sh** to install the drivers patched for your OS automatically, with high chance of success. **10.13 -> 10.14** and other major OS changes usually break web drivers, and patching will not be helpful. The script will provide recommendations (**v4.2.5+**) as needed.

**Comment by allocenx** [comment]
So like now, my best chance which is? Tho, should not that automatic-efi alternative suppose to work either? I mean, neither in windows is working....

**Comment by mayankk2308** [comment]
@allocenx EFI solution will have same limitation. Please read through the forums as your concerns have already been addressed. To set up eGPU in bootcamp, refer to build guides one [egpu.io](https://egpu.io).

**Comment by allocenx** [comment]
> @allocenx EFI solution will have same limitation. Please read through the forums as your concerns have already been addressed. To set up eGPU in bootcamp, refer to build guides on [egpu.io](https://egpu.io).

Will there be a solution something for Mojave > 10.14 for nvidia gpus in the future?

**Comment by mayankk2308** [comment]
@allocenx we are **only waiting on Apple/NVIDIA** for drivers. The patches are functional (you can use a GTX 780 in macOS since the OS includes drivers for Kepler cards).

**Comment by allocenx** [comment]
> @allocenx we are **only waiting on Apple/NVIDIA** for drivers. The patches are functional (you can use a GTX 780 in macOS since the OS includes drivers for Kepler cards).

Damn, thats like an ancient card lol. Yeah, did some research too, seems like everyone is waiting since September last year...why is it taking so long... :(

**Comment by Sykrate** [comment]
Hello. I have the same issue : Black screen and very slow performances ...
I have read all the instructions many times but I really don't understand anything ...
I have a mcbook pro 2014, OS High Sierra 10.13.6. 
Can you help me ?

Thank you so much

**Comment by mayankk2308** [comment]
@Sykrate Please state your entire system configuration. What eGPU are you using with what enclosure? Is your Mac 15" or 13"? Does it have an NVIDIA GPU?

Before debugging software ensure:
- eGPU is assembled correctly and properly installed into PCIe slot.
- ALL power pins are plugged into the GPU as needed.

Then share screenshots of System Report > Graphics/Displays, System Report > PCI, and the script's check patch status output.

**Comment by Sykrate** [comment]
First of all thanks for anwser so fast !

- I have a razer core x, with a MSI RX 580 inside.
- My macbook pro is 15"
- It has NVIDIA GeForce GT 750M
- I checked, the installation is ok.

Here the screenshots :
![Capture d’écran 2019-10-05 à 19 39 14](https://user-images.githubusercontent.com/56201425/66258639-fb1c4780-e7a7-11e9-8dc4-dd6baa3be7ea.png)
![Capture d’écran 2019-10-05 à 19 38 48](https://user-images.githubusercontent.com/56201425/66258640-fc4d7480-e7a7-11e9-9a8a-ba06be741fea.png)


(Sorry for my bad english, as you saw I'm french)
Thanks !

**Comment by mayankk2308** [comment]
This issue is for NVIDIA eGPUs. Anyway, to get output on external monitor connected to eGPU, you need [purge-nvda](https://github.com/mayankk2308/purge-nvda) as stated in the README.

**Comment by Sykrate** [comment]
Ok, so if I understand well, it's about this line : 
<img width="514" alt="Capture d’écran 2019-10-05 à 20 06 13" src="https://user-images.githubusercontent.com/56201425/66258967-a8dd2580-e7ab-11e9-875a-f5240ca5f466.png">

So I had to modifie "-d" by "-s" in this code line ? : curl -qLs $(curl -qLs https://bit.ly/2WtIESm | grep '"browser_download_url":' | cut **-d**'"' -f4) > purge-wrangler.sh; bash purge-wrangler.sh; rm purge-wrangler.sh

Thanks !

**Comment by mayankk2308** [comment]
@Sykrate No. Please see the [Hardware Chart](https://github.com/mayankk2308/purge-wrangler#hardware-chart). *purge-nvda* is a **different script**.

**Comment by Sykrate** [comment]
Ok, I already tried this, I copy-paste the entire code into the Terminal, press enter, enter my password. Then, this message appear : 
<img width="346" alt="Capture d’écran 2019-10-05 à 20 15 12" src="https://user-images.githubusercontent.com/56201425/66259054-f8702100-e7ac-11e9-8c0e-d46dc4cefcea.png">
 Did I do something wrong ?

Thanks for your patience

**Comment by mayankk2308** [comment]
What code? Please follow instructions appropriately. See:
https://github.com/mayankk2308/purge-nvda

Sorry, but I am busy at this time. Please reach out on [eGPU.io](https://egpu.io) if you still can't figure this out.
