### ISSUE TITLE
External Display Black but recognised

### ISSUE THREAD

**Issue by heilinfe** [mayankk2308/purge-wrangler#90]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 13" 2020
- **macOS Version**: 10.15.6
- **System GPUs**: Intel Iris 645
- **eGPU**: Razor Core X + NVIDIA GTX 1060 3GB
- **Script Version**: 6.2.5
- **Script Logs**:  [pwlog-2020-07-24-23-03-05.zip](https://github.com/mayankk2308/purge-wrangler/files/4974245/pwlog-2020-07-24-23-03-05.zip)

### Issue Description
The external display is getting recognized but is black. Backlight turned on and the source is detected. I tried multiple external monitors. About mac shows the Graphics as NVIDIA GTX 1060 3GB. The Display settings are showing the display as well and I can move windows over.

### Expected Behavior
The external monitor should work.

Thanks for your help!

**Comment by mayankk2308** [comment]
Read the FAQ/wiki.
