### ISSUE TITLE
System won't boot after installing script

### ISSUE THREAD

**Issue by ajlowndes** [mayankk2308/purge-wrangler#91]
### System Configuration

- **Mac**: MacBook Air 11" Early 2015
- **macOS Version**: 10.15.6
- **System GPUs**: Intel HD Graphics 6000 1536 MB
- **eGPU**: Sonnet Breakaway 650 + Sapphire Pulse AMD Radeon RX 5700 XT
- **Script Version**: 6.2.5
- **Script Logs**: [pwlog-2020-09-04-16-34-58.zip](https://github.com/mayankk2308/purge-wrangler/files/5173096/pwlog-2020-09-04-16-34-58.zip)

### Issue Description
Related to #44 . Similarly, I had to install manually in order for the script to finish without crashing the system.
However upon rebooting, the system won't progress past the Apple logo. Tried with eGPU connected and not connected, no difference.
Have filmed the system boot while holding CMD+V for verbose booting - you can see it crashes right at the start.

Booting into Recovery partition and following the recovery process does allow the system to boot up again, but I do note that (1) `diskutil apfs mount "Macintosh HD"` command is not recognised, and (2) some errors show up after the last step `kextcache -i /Volumes/Macintosh\ HD`, and the instructions specifically state "# Make sure you don't see any errors" but I can't find any more info on that. See attached screenshot.

### Expected Behavior
System to successfully boot up so I can see if the script worked and the eGPU works.

### Screenshots
Slow-motion video of verbose booting (github won't upload .mp4 and I couldn't make a GIF with resolution that you can read, so it is simply zipped, sorry).
[VID_20200904_164548~3.mp4.zip](https://github.com/mayankk2308/purge-wrangler/files/5173235/VID_20200904_164548.3.mp4.zip)

List of errors after going through the recovery process.
![IMG_20200904_165938](https://user-images.githubusercontent.com/841035/92209779-ee7d0380-eed0-11ea-86a8-16d458a911ea.jpg) and ![IMG_20200904_170032](https://user-images.githubusercontent.com/841035/92209803-f6d53e80-eed0-11ea-9421-c192833d1710.jpg)

**Comment by mayankk2308** [comment]
From your screenshots I see that the kextcache utility spit out some connection issues, but cache was created successfully. That’s why you were able to reboot successfully. Have you tried patching again to see if it works? I am not sure what’s causing the issue. I also presume that you are using the latest release version of the script (installed via beginner’s guide) and not using the Advanced Handbook. I’ll take a look at the script logs shortly.

**Comment by ajlowndes** [comment]
Just to answer the first question - yes I tried twice on separate days (about a week ago, then a second time today), then a third time today to get the screenshots and logs and stuff for this post. 
Each time the behaviour was consistent across the board.
Yes I'm using the latest version of the script, i.e. I followed the beginner's guide. I skipped over the Advanced Handbook but I'll go read that now.

**Comment by mayankk2308** [comment]
No, just make sure to skip the Advanced Handbook. I’ll get to examining the logs soon.

**Comment by mayankk2308** [comment]
Logs looks ok. I am not sure what the issue is. I do suspect some of your other kexts however. Looking at the verbose boot log, it seems like RBIOKitHelper may be interfering. I would try creating an extra installation of macOS and testing the script on that clean install: https://support.apple.com/en-us/HT208891

**Comment by theopape** [comment]
I have this same issue on macOS Big Sur. Don't have RBIOKitHelper as far as I am aware.

**Comment by mayankk2308** [comment]
@theopape Big Sur is not supported yet. Please wait for support or read more on eGPU.io.

**Comment by ajlowndes** [comment]
@mayankk2308 just FYI I am yet to implement your suggested fix, waiting to get some time to fiddle with the MBA in question again (it's my wife's laptop).

**Comment by ajlowndes** [comment]
@mayankk2308 Looks like you were right. I installed macOS on a separate APFS volume and ran the script after booting into that. And the eGPU works! Booting back into the original installation didn't work however, so I had to do the Recovery method again. Bit confusing that, but I guess the apfs-sharing-volumes-thing isn't as "clean" as a straight up partition. Anyway, I'm making a TM backup of the original apfs volume now, will restore onto the new one and delete the original from Disk Utility.

Cheers for your help!

**Comment by mayankk2308** [comment]
> Booting back into the original installation didn't work however, so I had to do the Recovery Process again. Bit confusing that, but I guess the apfs-sharing-volumes-thing isn't as "clean" as a straight up partition, so applying the script on one installation somehow affected the other one as well. Meh, at least the Recovery Process still worked.

It should be fully segregated. Boot may have failed due to some other reason. The script can only impact installations it ran on.
