### ISSUE TITLE
No GPU detected after installation of the script

### ISSUE THREAD

**Issue by Ugory** [mayankk2308/purge-wrangler#92]
### System Configuration
- **Mac**: MacBook Pro 13"
- **macOS Version**: 10.15.6
- **System GPUs**: Intel Iris 
- **eGPU**: AORUS GTX 1080 GAMING BOX 
- **Script Version**: 6.2.5
- **Script Logs**: Attach logs generated by the script

### Issue Description
After a successful installation of the script, there are no observable changes in eGPU recognition. 
I have disabled SIP and FileVault, however, was not able to execute the command "csrutil authenticated-root disable" (command does not exist). 
Prior, I have also installed Nvidia drivers. 
The script executed fine with no errors. But after rebooting the system still did not recognize the connected eGPU as a graphical card.

Thank you in advance for help.

**Comment by Ugory** [comment]
[pwlog-2020-09-08-13-27-04.zip](https://github.com/mayankk2308/purge-wrangler/files/5187838/pwlog-2020-09-08-13-27-04.zip)

**Comment by Ugory** [comment]
Thunderbolt is recognized but not a graphical card. Please, see the attached screenshots.
<img width="577" alt="Screen Shot 2020-09-08 at 13 57 19" src="https://user-images.githubusercontent.com/20989975/92468244-83d30d00-f1db-11ea-8a02-496aa806e17a.png">
<img width="755" alt="Screen Shot 2020-09-08 at 13 57 26" src="https://user-images.githubusercontent.com/20989975/92468259-89c8ee00-f1db-11ea-8a2c-a5d99366b5ba.png">

**Comment by mayankk2308** [comment]
Read the guides/FAQ carefully. From the beginner's guide:

> ⚠️ If you are planning to use an NVIDIA GPU, please note the [restrictions](https://github.com/mayankk2308/purge-wrangler/wiki/FAQ#are-maxwell-or-newer-nvidia-gpus-supported-on-macos). Kepler GPUs may work with limited support.
