### ISSUE TITLE
eGPU is not recognized 

### ISSUE THREAD

**Issue by Ugory** [mayankk2308/purge-wrangler#93]
### System Configuration
- **Mac**: MacBook Pro 13" Mid-2017
- **macOS Version**: 10.13.6
- **System GPUs**: Intel Iris 
- **eGPU**: Aorus GamingBox Nvidia GTX 1080
- **Script Version**: 6.2.5.
- **Script Logs**: Attach logs generated by the script.

### Issue Description
The eGPU is still unrecognized after a successful script installation. SIP disabled, Nvidia drivers installed by the script. 
The eGPU box as always turns its ligth but no access to the eGPU itself. During the installation the script could not recognize the plugged-in eGPU. 

[pwlog-2020-09-10-00-48-24.zip](https://github.com/mayankk2308/purge-wrangler/files/5198122/pwlog-2020-09-10-00-48-24.zip)

<img width="751" alt="Screen Shot 2020-09-10 at 12 46 55 AM" src="https://user-images.githubusercontent.com/20989975/92659049-4caa4c00-f300-11ea-94e0-de856c26fe20.png">

<img width="757" alt="Screen Shot 2020-09-10 at 12 46 42 AM" src="https://user-images.githubusercontent.com/20989975/92659025-40be8a00-f300-11ea-817a-0f4224764c7c.png">

Thanks in advance!

**Comment by mayankk2308** [comment]
1080 is not supported. Please stop opening the same issue and read the docs.

**Comment by mayankk2308** [comment]
Sorry buddy, noticed this is 10.13.6 and not 10.15.6. I’ll take a look at the logs when possible.

**Comment by mayankk2308** [comment]
Ok, saw the logs. From what I see, the GPU inside the AORUS box is not being detected, although the box itself is. Are you sure it is in working condition? Also check that power cables are connected to GTX 1080 correctly.

If the GPU is detected correctly, you will see it in the PCI section of System Information. Basically, if you get the GPU detected, I think it should work for you.\

Again, sorry for the misunderstanding above, totally my bad there :O

**Comment by Ugory** [comment]
Dear mayank2308,

I bought the laptop and eGPU couple years ago for job (to run simulation on eGPU). The script worked amazingly and I finished successfully the simulation. 
Later being naive I updated the MacOS to Mojave and then to Catalina and never checked the eGPU. 
Nowadays, I was planing to use again the eGPU and, since Catalina is not supported, I downgraded to original MacOS High Sierra. 
I am using the eGPU in the same configuration as before, there are AC cable and USB-C with TB3.
Regarding PCI I will check it later today.

Thank you for being you!

**Comment by Ugory** [comment]
This is the PCI section:
<img width="757" alt="Screen Shot 2020-09-10 at 4 04 46 PM" src="https://user-images.githubusercontent.com/20989975/92732858-aef66180-f37f-11ea-8247-f1b9606c3445.png">

**Comment by mayankk2308** [comment]
It’s missing the gfx-controller. The GPU is not being detected. You’ll have to figure out why exactly on your end. Things should work once GPU is detected.

**Comment by Ugory** [comment]
Thanks. Do you have any suggestion in this regard? The GPU was working with the same laptop before. I suppose some drivers are missing.

**Comment by mayankk2308** [comment]
It’s not drivers - macOS physically cannot see your GPU. You can read about this more on eGPU.io but I can’t do anything if the hardware is not detected.

**Comment by Ugory** [comment]
Understood. Thank you!

**Comment by mayankk2308** [comment]
Closing as issue is not with the script itself. Feel free to post an update here if you do get things going.

**Comment by Ugory** [comment]
Hi, 
The problem was with the eGPU. 
After disassembling it and reassembling back, the eGPU works back as before!

Thank you for your time
