### ISSUE TITLE
2013 Mac Pro/Catalina/Razer Core X/AMD Radeon Pro WX 8200 not working

### ISSUE THREAD

**Issue by bsadri** [mayankk2308/purge-wrangler#94]
Nothing is detected during the installation and when I go through manually (AMD drivers with any combination of Legacy and Ti82) nothing really happens when I connect the GPU to my Mac. System Preferences shows up Razer Core X under Thunderbolt but there's no indication of there being an eGPU at all.

1. I have an Apple Thunderbolt 3 to 2 adapter but my Thunderbolt 2 cable is not a genuine Apple one. Could this really cause a problem?

2. Does it matter if the GPU is not connected to a monitor at the time of connecting it to the Mac? 

Any ideas or thoughts would be appreciated.

**Comment by bsadri** [comment]
I'm attaching the generated diagnosis.
[pwlog-2020-09-11-17-06-42.zip](https://github.com/mayankk2308/purge-wrangler/files/5211517/pwlog-2020-09-11-17-06-42.zip)

**Comment by mayankk2308** [comment]
Your Mac needs to detect the eGPU as an GPU controller before anything can work. I can't do anything if your hardware is unable to be physically detected.
1. Maybe.
2. No.

**Comment by bsadri** [comment]
It turns out that the problem was the Thunderbolt cable. I got an Apple brand one and everything worked like a charm.
Thanks for your help.
