### ISSUE TITLE
Force integral gpu on MBP Pro

### ISSUE THREAD

**Issue by ethaniel** [mayankk2308/purge-wrangler#95]
### Feature Description
MBP PRO 2015 (downgraded to 10.13.6) + Razer Core X + 1080ti = works great, but only when i force the internal gpu (Intel Iris Pro) with gfxCardStatus 2.2.1.
If I leave it to MBP to decide which gpu to use (and it uses the discreet AMD Radeon R9 M370X by default), the whole system is extremely slow (like 5 fps). It took me a lot of searching to find the gfxCardStatus solution to the problem.

### Potential Solution
Perhaps there is a way to completely disable the discreet GPU (the AMD Radeon R9 M370X) and force the integrated one (Intel Iris Pro)?

### Alternatives
The only way around is to use gfxCardStatus 2.2.1 (newer versions can't switch on the fly for some reason), but every time I reboot, it takes me a minute or so to be able to switch to the integrated GPU.

### More Context
I think a lot of new people have this problem which steers them away from the egpu solutions for mac.

**Comment by mayankk2308** [comment]
I wrote about this in point 12 here: https://egpu.io/forums/postid/38232/

**Comment by ethaniel** [comment]
> I wrote about this in point 12 here: https://egpu.io/forums/postid/38232/

I don't know if I'm an edge case, but with your `sudo nvram boot-args="-amd_no_dgpu_accel" # disable AMD GPU acceleration` method, my laptop screen gets stuck with the "loading" apple logo, while all other monitors operate normally and the system loads. The gfxCardStatus doesn't have this issue.

**Comment by mayankk2308** [comment]
You also need to switch mux to iGPU.

**Comment by ethaniel** [comment]
> You also need to switch mux to iGPU.

Did both of these commands:
```
sudo nvram boot-args="-amd_no_dgpu_accel" # disable AMD GPU acceleration
sudo nvram fa4ce28d-b62f-4c99-9cc3-6815686e30f9:gpu-power-prefs=%01%00%00%00 # switch mux to iGPU
```

But still stuck with the laptop screen with the apple logo:
![IMG_0967](https://user-images.githubusercontent.com/941973/93172486-239d1780-f755-11ea-9022-e1213e0465bc.JPG)

**Comment by mayankk2308** [comment]
People have had success with those steps so I am not sure what the issue is on your end (maybe the eGPU?). I’m not sure. Reset the NVRAM settings and instead try with the pmset command on this post (might be required every boot tho): https://egpu.io/forums/mac-setup/automate-egpu-efi-egpu-boot-manager-for-macos-and-windows/
