### ISSUE TITLE
The script told me to open an issue...

### ISSUE THREAD

**Issue by lgmchessfan** [mayankk2308/purge-wrangler#96]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 15" Mid-2015
- **macOS Version**: 10.15.6
- **System GPUs**: Intel Iris 
- **eGPU**: GIGABYTE GAMING BOX RX 580
- **Script Version**: 6.2.5
- **Script Logs**: [pwlog-2020-09-16-09-10-50.zip](https://github.com/mayankk2308/purge-wrangler/files/5232722/pwlog-2020-09-16-09-10-50.zip)

You can generate logs from the script by choosing **More Options** > **System Diagnosis & Logging**.

### Issue Description
It seems like everything is ok, but the external monitor gets no image, I'm using the hdmi conector.

**Comment by mayankk2308** [comment]
Everything looks okay in the logs. If your external monitor is not getting an image, try DisplayPort or different HDMI cable. There's not much I can do here except recommend replacement hardware.

**Comment by lgmchessfan** [comment]
Thanks a lot! I'll try ir!
