### ISSUE TITLE
HD 7970 (Atikio Thunder 2) doesn't enable on 2015 MBP, MacOS 10.15.6

### ISSUE THREAD

**Issue by OscarJsson** [mayankk2308/purge-wrangler#97]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- MacBook Pro 15" 2015 - 
- MacOS 10.15.6
- R9 M370X
- Akitio Thunder 2 + Gigabyte HD 7970
- PurgeWrangler 6.2.5

[pwlog-2020-09-19-22-31-57.zip](https://github.com/mayankk2308/purge-wrangler/files/5250571/pwlog-2020-09-19-22-31-57.zip)

[GPU plugging in system log.txt](https://github.com/mayankk2308/purge-wrangler/files/5250574/GPU.plugging.in.system.log.txt)

_Test of how the system behaves when I plug in the eGPU. I physically unplugged the GPU around 21.45.46, plugged it back in around 21.45.51, and the screen briefly blinked around 21.45.56-58._ 

### Issue Description
The problem occurs every time. I've run this script before under High Sierra and everything used to work fine. I'm using an Atikio Thunder 2 box with a Gigabyte HD 7970 card. After upgrading to Mojave, the setup doesn't work well anymore. I'm using the latest script, I've tried uninstalling and reinstalling the script and everything seems to install fine. After rebooting, my eGPU symbol in the menu bar will show up for a split seconds, and then just suddenly disappear again from the menu bar. The fans on the eGPU are spinning throughout.

### Expected Behavior
I expected the GPU to enable and be recognised by the OS as usual after running the script. I use it primarily without a connected display for OpenCL 3D rendering.

**Comment by mayankk2308** [comment]
Can you tell me what happens when you execute the following:
```bash
sudo kextload /Library/Extensions/AMDLegacySupport.kext
```

**Comment by mayankk2308** [comment]
Also, just to be clear - **Mojave** is **10.14.6** - you seem to be running **Catalina** (**10.15.6**). 

Anyway, If my previous suggestion doesn't work, let's try a few things (try after patching system with script). I am attaching a few differently configured AMD legacy kexts. Try out each one. For each one, copy the kext to `/Library/Extensions/`, and then:
```sh
sudo chmod -R 755 /Library/Extensions
sudo chown -R root:wheel /Library/Extensions

# Ensure kextload doesn't give an error
sudo kextload /Library/Extensions/AMDLegacySupport.kext
```

Reboot system and plug in eGPU. Kexts to try: [Legacy Support Kext Configs.zip](https://github.com/mayankk2308/purge-wrangler/files/5250822/Legacy.Support.Kext.Configs.zip)

**Comment by OscarJsson** [comment]
Yeah, my mistake about the OS names, guess I've lost track of those lately. 

I tried both of your suggestions. I got no error back when trying the sudo kextload command, using any of the different AMDLegacySupport.kext versions.

None of the different versions seem to have made any difference to how my system behaves when plugging the GPU in. I tried installing three of them, running the commands you suggested and rebooting. The eGPU still won't enable properly when I plug it in, with the only sign being that the eGPU symbol pops up briefly in the menu bar. 

On a possibly unrelated note, I have had problems with rebooting the system lately and had to force shut-off with the power button after installing each of these scripts. .

**Comment by mayankk2308** [comment]
macOS updates have typically impacted support for eGPUs - and I’ve never seen an HD 7970 functional as an eGPU (or don’t remember) on Catalina. From your logs, I also noticed that there was a problem allocating the necessary driver in macOS when you plugged in the eGPU. You might consider downgrading or switching to Polaris or newer GPUs. It’s also harder for me to come up with a solution to get this card working when I don’t have it on hand to test it + it’s an old card at this point. Apologies but there’s nothing else I can do.

**Comment by OscarJsson** [comment]
Hi, 

I understand. I bought a 5500 XT and it works fine. Thanks anyway for your help!
