### ISSUE TITLE
unable to patch for tb 1/2 AMD

### ISSUE THREAD

**Issue by alanportable** [mayankk2308/purge-wrangler#98]
[pwlog-2020-09-28-22-37-22.zip](https://github.com/mayankk2308/purge-wrangler/files/5295031/pwlog-2020-09-28-22-37-22.zip)
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: MacBook Pro 15" Mid- 2015
- **macOS Version**: 10.13.4
- **System GPUs**: Intel Iris 
Egpu razor core x 
with sapphire rx 580
while installing it says "unable to patch for tb 1/2 AMD

**Comment by mayankk2308** [comment]
Please fill in the whole template.

**Comment by mayankk2308** [comment]
It is not clear what script version you used. Anyway, this issue is the same as #99 so please follow up there. Also try script release **6.3.1**.
