### ISSUE TITLE
mac mini 2011 and radeon vega 64

### ISSUE THREAD

**Issue by fmtvgithub** [mayankk2308/purge-wrangler#99]
### System Configuration
Describe your system configuration here. State any anomalies (USB drives, etc.) involved as well.
- **Mac**: Mac Mini (Mid 2011)
- **macOS Version**: 10.13.6
- **System GPUs**: Intel HD Graphics 3000 512MB
- **eGPU**: Razer Core X Chroma + RX Vega 64
- **Script Version**: 6.2.5
- **Script Logs**: Attached

### Issue Description
Unable to patch for TB1/2. Once this happens, on restarting the computer I get hopelessly stuck on the apple. Had to re-install the OS. I tried three times, and three times I had to re-install.

### Expected Behavior
Well, maybe I am pushing it, but I did expect it to work.
Backstory: I was given a top spec 2019 mac mini for a temporary assignment. With the job finished, six months down the line, I had to return it. 
In the process I got myself an eGPU, thinking I was going to make use of it anyway somehow afterwards.
The idea was to hook it up to a 2015 MBP over TB2 until the next Apple revolution takes form and I can figure out what to buy next and why.
But I thought _let me try it on the old Mini before I do something horrible to the computer that I still use on a daily basis.

### Screenshots
Attached with logs
[ThunderboltDevices.log](https://github.com/mayankk2308/purge-wrangler/files/5295034/ThunderboltDevices.log)
[PCI.log](https://github.com/mayankk2308/purge-wrangler/files/5295035/PCI.log)

![Screen Shot 2020-09-28 at 13 32 58](https://user-images.githubusercontent.com/72047200/94485772-b66e9500-01de-11eb-95f0-3168cb67e9ad.png)

**Comment by mayankk2308** [comment]
Investigating.

**Comment by fmtvgithub** [comment]
I did run csrutil disable from recovery mode terminal as advised.

Some log files didn't attach, I am adding them here

[Mac.log](https://github.com/mayankk2308/purge-wrangler/files/5295131/Mac.log)
[Kextstat.log](https://github.com/mayankk2308/purge-wrangler/files/5295132/Kextstat.log)
[GPUs.log](https://github.com/mayankk2308/purge-wrangler/files/5295134/GPUs.log)
[Extensions.log](https://github.com/mayankk2308/purge-wrangler/files/5295135/Extensions.log)
[eGPU.log](https://github.com/mayankk2308/purge-wrangler/files/5295137/eGPU.log)

**Comment by mayankk2308** [comment]
@fmtvgithub Thanks. I'll investigate this and let you know once I have a fix ready.

**Comment by fmtvgithub** [comment]
Thanks a million, let me know if you need any more info from my side

**Comment by mayankk2308** [comment]
@fmtvgithub I tried script **v6.2.5** on Mojave (exact same patches and code path as High Sierra) and could not reproduce the issue. I will also install High Sierra and test. In the meantime, please test **v6.3.1** of the script and let me know how that goes. Also, if you do get stuck again, instead of reinstalling, please try these [recovery mechanisms](https://github.com/mayankk2308/purge-wrangler/wiki/System-Recovery) first.

**Comment by mayankk2308** [comment]
@fmtvgithub I also tested **v6.3.1** on High Sierra and all seemed to go ok. Please let me know once you try again.

**Comment by fmtvgithub** [comment]
It worked, with some suspence, but it worked. Old mac mini is now running two monitors off the vega64, thanks! 

Everything seemed to be fine, it was sanitizing the system and I was expecting the restart prompt, when the computer restarted on its own - I got the odd centre-screen multi-language notice that it had been restarted because of a problem. 
I thought it was going to get stuck again, but instead it restarted normally and when the wallpaper appeared I had the eGPU icon in the menu bar and all is good. I am impressed with the improvement in performance.

attaching current system log for reference
[ThunderboltDevices.log](https://github.com/mayankk2308/purge-wrangler/files/5295531/ThunderboltDevices.log)
[PCI.log](https://github.com/mayankk2308/purge-wrangler/files/5295532/PCI.log)
[Mac.log](https://github.com/mayankk2308/purge-wrangler/files/5295533/Mac.log)
[Kextstat.log](https://github.com/mayankk2308/purge-wrangler/files/5295534/Kextstat.log)
[GPUs.log](https://github.com/mayankk2308/purge-wrangler/files/5295535/GPUs.log)
[Extensions.log](https://github.com/mayankk2308/purge-wrangler/files/5295536/Extensions.log)
[eGPU.log](https://github.com/mayankk2308/purge-wrangler/files/5295537/eGPU.log)
